WinUI guide updates
MicrosoftDocs/edge-developer pull request #1022
Opened 2020-11-20 19:37 UTC by jasonstephen15

2020-11-20 19:37 UTC, opbld30 commented
Docs Build status updates of commit _[fcff47a](https://github.com/MicrosoftDocs/edge-developer/commits/fcff47a7bfcb91ed96a014b0769ead3f4fe987d2)_: 

:clock10: **Pending**: waiting for processors ([20](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 20 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-11-20 19:41 UTC, opbld32 commented
Docs Build status updates of commit _[fcff47a](https://github.com/MicrosoftDocs/edge-developer/commits/fcff47a7bfcb91ed96a014b0769ead3f4fe987d2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/gettingstarted/winui.md](https://github.com/MicrosoftDocs/edge-developer/blob/usr/jasteph/winuiGuideUpdates/microsoft-edge/webview2/gettingstarted/winui.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winui?branch=pr-en-us-1022) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C20%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202011201937197780-1022%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YiPt89%2FjO9dVu5yab16RK3yIajku0PQ9HwZEe0Fac1E%3D&st=2020-11-20T19%3A36%3A53Z&se=2020-12-21T19%3A41%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-20 20:55 UTC, Reezaali approved these changes

2020-11-20 22:37 UTC, opbld30 commented
Docs Build status updates of commit _[ebdb8fc](https://github.com/MicrosoftDocs/edge-developer/commits/ebdb8fc3cc031195e01b44fa3937bdb207d0f3dc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/gettingstarted/winui.md](https://github.com/MicrosoftDocs/edge-developer/blob/usr/jasteph/winuiGuideUpdates/microsoft-edge/webview2/gettingstarted/winui.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winui?branch=pr-en-us-1022) | [Details](#user-content-3acee4ca-da01c216)

<a id="3acee4ca-da01c216"></a>
### [microsoft-edge/webview2/gettingstarted/winui.md](https://github.com/MicrosoftDocs/edge-developer/blob/usr/jasteph/winuiGuideUpdates/microsoft-edge/webview2/gettingstarted/winui.md)
 - **Line 32, Column 190**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#windows-community-toolkit' in 'webview2/gettingstarted/winui.md'.`````
 - **Line 25, Column 1**: **[Suggestion-[code-block-indented](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```). NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 1**: **[Suggestion-[code-block-indented](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```). NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C20%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202011202236307587-1022%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QXDbQ7daSz19fuz1BW%2F572XtNaGNB6WfYj9%2FepKKv%2Bk%3D&st=2020-11-20T22%3A32%3A03Z&se=2020-12-21T22%3A37%3A03Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-20 23:16 UTC, Reezaali requested changes
Left some feedback. Can you review and address please?

2020-11-20 23:16 UTC, Reezaali commented on microsoft-edge/webview2/gettingstarted/winui.md
> +    - The *C++ (v142) Universal Windows Platform tools* optional component for the Universal Windows Platform workload (see "Installation Details" under the "Universal Windows Platform development" s
This text isn't formatted correctly. Can you review?

2020-11-20 23:16 UTC, Reezaali commented on microsoft-edge/webview2/gettingstarted/winui.md
> +    - The *C++ (v142) Universal Windows Platform tools* optional component for the Universal Windows Platform workload (see "Installation Details" under the "Universal Windows Platform development" s
```suggestion
    - The *C++ (v142) Universal Windows Platform tools* optional component for the Universal Windows Platform workload. For more information,  navigate to Installation Details under the Universal Windows Platform development section, on the right pane.
```

2020-11-20 23:16 UTC, Reezaali commented on microsoft-edge/webview2/gettingstarted/winui.md
> +    - The *C++ (v142) Universal Windows Platform tools* optional component for the Universal Windows Platform workload (see "Installation Details" under the "Universal Windows Platform development" s
Looks like a link is missing in the last sentence?

2020-11-20 23:16 UTC, Reezaali commented on microsoft-edge/webview2/gettingstarted/winui.md
> +4.   Make sure your system has a NuGet package source enabled for **nuget.org**. For more information, see [Common NuGet configurations](/nuget/consume-packages/configuring-nuget-behavior).[Windows C
```suggestion
4.   Make sure your system has a NuGet package source enabled for **nuget.org**. For more information, see [Common NuGet configurations](/nuget/consume-packages/configuring-nuget-behavior) and [Windows Community Toolkit](#windows-community-toolkit).
```

2020-11-20 23:16 UTC, Reezaali commented on microsoft-edge/webview2/gettingstarted/winui.md
> +5.   Download and install the [WinUI 3 Preview 3 VSIX package](https://aka.ms/winui3/preview3-download). This adds both the WinUI 3 project templates and the NuGet package containing the WinUI 3 libr
Can you replace the aka.ms link?

2020-11-20 23:32 UTC, opbld32 commented
Docs Build status updates of commit _[3233d87](https://github.com/MicrosoftDocs/edge-developer/commits/3233d879d2bd6a5639542a554e4952b185ad147b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/gettingstarted/winui.md](https://github.com/MicrosoftDocs/edge-developer/blob/usr/jasteph/winuiGuideUpdates/microsoft-edge/webview2/gettingstarted/winui.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winui?branch=pr-en-us-1022) | [Details](#user-content-3acee4ca-bb69f131)

<a id="3acee4ca-bb69f131"></a>
### [microsoft-edge/webview2/gettingstarted/winui.md](https://github.com/MicrosoftDocs/edge-developer/blob/usr/jasteph/winuiGuideUpdates/microsoft-edge/webview2/gettingstarted/winui.md)
 - **Line 32, Column 194**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#windows-community-toolkit' in 'webview2/gettingstarted/winui.md'.`````
 - **Line 25, Column 1**: **[Suggestion-[code-block-indented](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```). NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 1**: **[Suggestion-[code-block-indented](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```). NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C20%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202011202332062034-1022%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nf9AEsGxQQ6oQPohX35vJbRnJopdoFod59HUu8I0Iyo%3D&st=2020-11-20T23%3A27%3A48Z&se=2020-12-21T23%3A32%3A48Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-20 23:52 UTC, opbld32 commented
Docs Build status updates of commit _[bd961a7](https://github.com/MicrosoftDocs/edge-developer/commits/bd961a7073f9277998c29c31a97bf42ca229c7d1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/gettingstarted/winui.md](https://github.com/MicrosoftDocs/edge-developer/blob/usr/jasteph/winuiGuideUpdates/microsoft-edge/webview2/gettingstarted/winui.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winui?branch=pr-en-us-1022) | [Details](#user-content-3acee4ca-e8303a37)

<a id="3acee4ca-e8303a37"></a>
### [microsoft-edge/webview2/gettingstarted/winui.md](https://github.com/MicrosoftDocs/edge-developer/blob/usr/jasteph/winuiGuideUpdates/microsoft-edge/webview2/gettingstarted/winui.md)
 - **Line 32, Column 194**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#windows-community-toolkit' in 'webview2/gettingstarted/winui.md'.`````
 - **Line 25, Column 1**: **[Suggestion-[code-block-indented](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```). NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 36, Column 1**: **[Suggestion-[code-block-indented](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```). NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C20%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202011202351303713-1022%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CqSAMfZuNZYBr7Odg7fFcedbbRzW1mOR8guBSIbNphs%3D&st=2020-11-20T23%3A47%3A49Z&se=2020-12-21T23%3A52%3A49Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-21 00:10 UTC, opbld30 commented
Docs Build status updates of commit _[39fb8b8](https://github.com/MicrosoftDocs/edge-developer/commits/39fb8b852e7302fefeb6f33c7116ac36c48730cc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/gettingstarted/winui.md](https://github.com/MicrosoftDocs/edge-developer/blob/usr/jasteph/winuiGuideUpdates/microsoft-edge/webview2/gettingstarted/winui.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winui?branch=pr-en-us-1022) | [Details](#user-content-3acee4ca-4f9d7389)

<a id="3acee4ca-4f9d7389"></a>
### [microsoft-edge/webview2/gettingstarted/winui.md](https://github.com/MicrosoftDocs/edge-developer/blob/usr/jasteph/winuiGuideUpdates/microsoft-edge/webview2/gettingstarted/winui.md)
 - **Line 35, Column 197**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#windows-community-toolkit' in 'webview2/gettingstarted/winui.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C21%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202011210009347499-1022%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kk0zmR0lOO9kiUgqD9J5ODkpurYgvS2MEDNirkrXcnA%3D&st=2020-11-21T00%3A05%3A14Z&se=2020-12-22T00%3A10%3A14Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-21 01:01 UTC, opbld32 commented
Docs Build status updates of commit _[c45df31](https://github.com/MicrosoftDocs/edge-developer/commits/c45df317468e711f7cd3b5e15249515e617f8486)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/gettingstarted/winui.md](https://github.com/MicrosoftDocs/edge-developer/blob/usr/jasteph/winuiGuideUpdates/microsoft-edge/webview2/gettingstarted/winui.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winui?branch=pr-en-us-1022) | [Details](#user-content-3acee4ca-5a0f58a6)

<a id="3acee4ca-5a0f58a6"></a>
### [microsoft-edge/webview2/gettingstarted/winui.md](https://github.com/MicrosoftDocs/edge-developer/blob/usr/jasteph/winuiGuideUpdates/microsoft-edge/webview2/gettingstarted/winui.md)
 - **Line 34, Column 205**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#windows-community-toolkit' in 'webview2/gettingstarted/winui.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C21%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202011210100451947-1022%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CbjTKr6mLBs1IO6smXmP079G%2F8Ja5uDBGztfFPBQkOo%3D&st=2020-11-21T00%3A56%3A27Z&se=2020-12-22T01%3A01%3A27Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-21 01:05 UTC, opbld31 commented
Docs Build status updates of commit _[01b65cb](https://github.com/MicrosoftDocs/edge-developer/commits/01b65cb9822b1f7c0fd3e62214570857498f0a03)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/gettingstarted/winui.md](https://github.com/MicrosoftDocs/edge-developer/blob/usr/jasteph/winuiGuideUpdates/microsoft-edge/webview2/gettingstarted/winui.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winui?branch=pr-en-us-1022) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C21%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202011210104147489-1022%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Ej9KuelQW3Oa8IfOD2UfAzm0B4GJBi3X6qs%2FIRpP2SU%3D&st=2020-11-21T01%3A00%3A18Z&se=2020-12-22T01%3A05%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-21 01:09 UTC, opbld33 commented
Docs Build status updates of commit _[9f25d8a](https://github.com/MicrosoftDocs/edge-developer/commits/9f25d8a9dc2a1dc53be80a1d0e48e4a120245ea1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/gettingstarted/winui.md](https://github.com/MicrosoftDocs/edge-developer/blob/usr/jasteph/winuiGuideUpdates/microsoft-edge/webview2/gettingstarted/winui.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winui?branch=pr-en-us-1022) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C21%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202011210108454913-1022%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VoRGYusd%2F5yvtmbVb2a9hkdwqpBRSk2aYTL24nN%2FuvQ%3D&st=2020-11-21T01%3A04%3A19Z&se=2020-12-22T01%3A09%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-21 01:11 UTC, jasonstephen15 commented
#sign-off

2020-11-21 01:12 UTC, jm-trd-ms commented
#sign-off and merged.

2020-11-21 01:13 UTC, jm-trd-ms commented
Acrolinx score: 97

2020-11-21 01:13 UTC, merged