Added Manifest file format
MicrosoftDocs/edge-developer pull request #1267
Opened 2021-06-02 06:02 UTC by gebansal

2021-06-02 06:03 UTC, opbld33 commented
Docs Build status updates of commit _[620dba9](https://github.com/MicrosoftDocs/edge-developer/commits/620dba94ff519c2a687052996589a14c35199933)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/extensions-chromium/getting-started/manifest-format.md](https://github.com/MicrosoftDocs/edge-developer/blob/gebansal-mv3-update/microsoft-edge/extensions-chromium/getting-started/manifest-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/manifest-format?branch=pr-en-us-1267) |
[microsoft-edge/toc.yml](https://github.com/MicrosoftDocs/edge-developer/blob/gebansal-mv3-update/microsoft-edge/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/manifest-format?branch=pr-en-us-1267) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C2%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202106020602352692-1267%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=aRpd1XLU%2BQPqQeSMpvJmDKWTcUIxoJINSvGJqaFphUw%3D&st=2021-06-02T05%3A58%3A17Z&se=2021-07-03T06%3A03%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-02 06:08 UTC, opbld31 commented
Docs Build status updates of commit _[d1ba5c3](https://github.com/MicrosoftDocs/edge-developer/commits/d1ba5c3571380ca28284be43fdb5a73712dadbab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/extensions-chromium/getting-started/manifest-format.md](https://github.com/MicrosoftDocs/edge-developer/blob/gebansal-mv3-update/microsoft-edge/extensions-chromium/getting-started/manifest-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/manifest-format?branch=pr-en-us-1267) |
[microsoft-edge/toc.yml](https://github.com/MicrosoftDocs/edge-developer/blob/gebansal-mv3-update/microsoft-edge/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/manifest-format?branch=pr-en-us-1267) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C2%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202106020607491552-1267%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Suk8d09K%2FLlfR7x0vjuWKTmEmrx7XO3MLTDZKzWs4%2BI%3D&st=2021-06-02T06%3A03%3A53Z&se=2021-07-03T06%3A08%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-02 06:22 UTC, opbld33 commented
Docs Build status updates of commit _[72ee994](https://github.com/MicrosoftDocs/edge-developer/commits/72ee994404b2effbf9e2dda36ac943130796812f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/extensions-chromium/getting-started/manifest-format.md](https://github.com/MicrosoftDocs/edge-developer/blob/gebansal-mv3-update/microsoft-edge/extensions-chromium/getting-started/manifest-format.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/manifest-format?branch=pr-en-us-1267) | [Details](#user-content-60fd1af295c4dbfbb8871912186a8955-3e6ddc58)
[microsoft-edge/extensions-chromium/getting-started/mv2-file-format.md](https://github.com/MicrosoftDocs/edge-developer/blob/gebansal-mv3-update/microsoft-edge/extensions-chromium/getting-started/mv2-file-format.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/mv2-file-format?branch=pr-en-us-1267) | [Details](#user-content-8b79639d42fdc04b2555ba99436a77c9-3e6ddc58)
[microsoft-edge/toc.yml](https://github.com/MicrosoftDocs/edge-developer/blob/gebansal-mv3-update/microsoft-edge/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/manifest-format?branch=pr-en-us-1267) |

<a id="60fd1af295c4dbfbb8871912186a8955-3e6ddc58"></a>
### [microsoft-edge/extensions-chromium/getting-started/manifest-format.md](https://github.com/MicrosoftDocs/edge-developer/blob/gebansal-mv3-update/microsoft-edge/extensions-chromium/getting-started/manifest-format.md)
 - **Line 3, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Manifest file format - Microsoft Edge Development' is duplicated in: 'extensions-chromium/getting-started/manifest-format.md(3,8), extensions-chromium/getting-started/mv2-file-format.md(3,8)'. Titles must be unique within a docset.`````

<a id="8b79639d42fdc04b2555ba99436a77c9-3e6ddc58"></a>
### [microsoft-edge/extensions-chromium/getting-started/mv2-file-format.md](https://github.com/MicrosoftDocs/edge-developer/blob/gebansal-mv3-update/microsoft-edge/extensions-chromium/getting-started/mv2-file-format.md)
 - **Line 3, Column 8**: **[Warning-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Manifest file format - Microsoft Edge Development' is duplicated in: 'extensions-chromium/getting-started/manifest-format.md(3,8), extensions-chromium/getting-started/mv2-file-format.md(3,8)'. Titles must be unique within a docset.`````
 - **Line 20, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C2%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202106020621034252-1267%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=AhmPnZqdMw860MPg9UaCOBAxynzl0ypS%2BtmyABx6pYU%3D&st=2021-06-02T06%3A17%3A16Z&se=2021-07-03T06%3A22%3A16Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-02 06:24 UTC, opbld33 commented
Docs Build status updates of commit _[37803e3](https://github.com/MicrosoftDocs/edge-developer/commits/37803e315f90d08bd3b890fce0850394302b59c1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/extensions-chromium/getting-started/manifest-format.md](https://github.com/MicrosoftDocs/edge-developer/blob/gebansal-mv3-update/microsoft-edge/extensions-chromium/getting-started/manifest-format.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/manifest-format?branch=pr-en-us-1267) | [Details](#user-content-60fd1af295c4dbfbb8871912186a8955-54e3b7c4)
[microsoft-edge/toc.yml](https://github.com/MicrosoftDocs/edge-developer/blob/gebansal-mv3-update/microsoft-edge/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/manifest-format?branch=pr-en-us-1267) |

<a id="60fd1af295c4dbfbb8871912186a8955-54e3b7c4"></a>
### [microsoft-edge/extensions-chromium/getting-started/manifest-format.md](https://github.com/MicrosoftDocs/edge-developer/blob/gebansal-mv3-update/microsoft-edge/extensions-chromium/getting-started/manifest-format.md)
 - **Line 104, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C2%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202106020623382966-1267%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pM4RrLbujr%2FmzttBgkXPnXcVB3CdmWc24eoQNfOjKUw%3D&st=2021-06-02T06%3A19%3A41Z&se=2021-07-03T06%3A24%3A41Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-02 07:45 UTC, opbld31 commented
Docs Build status updates of commit _[0967d1c](https://github.com/MicrosoftDocs/edge-developer/commits/0967d1ca58640fc6cacc22edf78955aa18bda4e4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/extensions-chromium/getting-started/manifest-format.md](https://github.com/MicrosoftDocs/edge-developer/blob/gebansal-mv3-update/microsoft-edge/extensions-chromium/getting-started/manifest-format.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/manifest-format?branch=pr-en-us-1267) | [Details](#user-content-60fd1af295c4dbfbb8871912186a8955-fa4a9a27)
[microsoft-edge/toc.yml](https://github.com/MicrosoftDocs/edge-developer/blob/gebansal-mv3-update/microsoft-edge/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/manifest-format?branch=pr-en-us-1267) |

<a id="60fd1af295c4dbfbb8871912186a8955-fa4a9a27"></a>
### [microsoft-edge/extensions-chromium/getting-started/manifest-format.md](https://github.com/MicrosoftDocs/edge-developer/blob/gebansal-mv3-update/microsoft-edge/extensions-chromium/getting-started/manifest-format.md)
 - **Line 102, Column 151**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../developer-guide/migrate-your-extension-from-manifest-v2-to-v3'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C2%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202106020744455609-1267%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lqTwH%2BmNW%2BPEt4096UDTq1jK58ElM2MRzb1lYFYa7S4%3D&st=2021-06-02T07%3A40%3A55Z&se=2021-07-03T07%3A45%3A55Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-07 23:58 UTC, opbld33 commented
Docs Build status updates of commit _[b4d3f23](https://github.com/MicrosoftDocs/edge-developer/commits/b4d3f23c6f6f7fd414b6bb0f3d8e035072eed6f6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/extensions-chromium/getting-started/manifest-format.md](https://github.com/MicrosoftDocs/edge-developer/blob/gebansal-mv3-update/microsoft-edge/extensions-chromium/getting-started/manifest-format.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/manifest-format?branch=pr-en-us-1267) | [Details](#user-content-60fd1af295c4dbfbb8871912186a8955-8e31db48)
[microsoft-edge/toc.yml](https://github.com/MicrosoftDocs/edge-developer/blob/gebansal-mv3-update/microsoft-edge/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/manifest-format?branch=pr-en-us-1267) |

<a id="60fd1af295c4dbfbb8871912186a8955-8e31db48"></a>
### [microsoft-edge/extensions-chromium/getting-started/manifest-format.md](https://github.com/MicrosoftDocs/edge-developer/blob/gebansal-mv3-update/microsoft-edge/extensions-chromium/getting-started/manifest-format.md)
 - **Line 20, Column 184**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../developer-guide/migrate-your-extension-from-manifest-v2-to-v3'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C7%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202106072357411650-1267%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QlYMXSwQCBBe5Mzp291AAzYsnzgCQiORiDntZYUJzpM%3D&st=2021-06-07T23%3A53%3A25Z&se=2021-07-08T23%3A58%3A25Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-08 00:02 UTC, opbld31 commented
Docs Build status updates of commit _[b756f1e](https://github.com/MicrosoftDocs/edge-developer/commits/b756f1e663820c69d9104b86a2ab6077d8cc3761)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/extensions-chromium/getting-started/manifest-format.md](https://github.com/MicrosoftDocs/edge-developer/blob/gebansal-mv3-update/microsoft-edge/extensions-chromium/getting-started/manifest-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/manifest-format?branch=pr-en-us-1267) |
[microsoft-edge/toc.yml](https://github.com/MicrosoftDocs/edge-developer/blob/gebansal-mv3-update/microsoft-edge/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/manifest-format?branch=pr-en-us-1267) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C8%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202106080001449105-1267%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Xrf8ltuQQb9nwD1qb1tqoxDDh4g1QPcNtr33KGq1v1g%3D&st=2021-06-07T23%3A57%3A56Z&se=2021-07-09T00%3A02%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-08 00:19 UTC, mikehoffms commented on microsoft-edge/extensions-chromium/getting-started/manifest-format.md
> +    "service_worker": ...
added ... like v2

2021-06-08 00:22 UTC, mikehoffms commented on microsoft-edge/extensions-chromium/getting-started/manifest-format.md
> +  "host_permissions": [...],
Noting a diff: the v2 listing lacks [ ] square brackets

2021-06-08 00:23 UTC, mikehoffms commented on microsoft-edge/extensions-chromium/getting-started/manifest-format.md
> +  "version_name": "aString",
Noting a diff: v2 listing has:
"version_name": ...,

2021-06-08 00:26 UTC, mikehoffms commented on microsoft-edge/extensions-chromium/getting-started/manifest-format.md
> +```json
You can see my minor tweaks to the JSON listings at https://github.com/MicrosoftDocs/edge-developer/pull/1267/commits/0587d65abc99089bb8de8e252392a29a782de51b

2021-06-08 18:22 UTC, opbld31 commented
Docs Build status updates of commit _[31d24bb](https://github.com/MicrosoftDocs/edge-developer/commits/31d24bb0e3a9351fe62fddcb4285eab29071b24e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/extensions-chromium/getting-started/manifest-format.md](https://github.com/MicrosoftDocs/edge-developer/blob/gebansal-mv3-update/microsoft-edge/extensions-chromium/getting-started/manifest-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/manifest-format?branch=pr-en-us-1267) |
[microsoft-edge/toc.yml](https://github.com/MicrosoftDocs/edge-developer/blob/gebansal-mv3-update/microsoft-edge/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/manifest-format?branch=pr-en-us-1267) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C8%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202106081821319551-1267%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yHse2FDusG31yCzvCHO%2F3bqCQHX%2Ff8kehTCGmnJ%2BW%2BY%3D&st=2021-06-08T18%3A17%3A09Z&se=2021-07-09T18%3A22%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-08 18:26 UTC, opbld33 commented
Docs Build status updates of commit _[c91f50b](https://github.com/MicrosoftDocs/edge-developer/commits/c91f50bc7e98bdbd6d46273423f9d33195d5a883)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/extensions-chromium/getting-started/manifest-format.md](https://github.com/MicrosoftDocs/edge-developer/blob/gebansal-mv3-update/microsoft-edge/extensions-chromium/getting-started/manifest-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/manifest-format?branch=pr-en-us-1267) |
[microsoft-edge/toc.yml](https://github.com/MicrosoftDocs/edge-developer/blob/gebansal-mv3-update/microsoft-edge/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/manifest-format?branch=pr-en-us-1267) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C8%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202106081825289039-1267%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=awR%2F%2BgacsXWVWCfHDlbhbN3eNIXftOSHRdH%2FD7rSuJ4%3D&st=2021-06-08T18%3A21%3A09Z&se=2021-07-09T18%3A26%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-08 18:27 UTC, mikehoffms approved these changes

2021-06-08 20:13 UTC, Reezaali commented on microsoft-edge/extensions-chromium/getting-started/manifest-format.md
> +    // Required
```suggestion
    // If `background` is included, `service_ worker` is required
```

2021-06-08 20:15 UTC, Reezaali commented on microsoft-edge/extensions-chromium/getting-started/manifest-format.md
> +# Manifest file format
```suggestion
# Manifest file format for extensions
```

2021-06-08 20:21 UTC, Reezaali commented on microsoft-edge/extensions-chromium/getting-started/manifest-format.md
> +  // Pick one (or none)
```suggestion
  // Pick one or none
```

2021-06-08 20:22 UTC, Reezaali commented on microsoft-edge/extensions-chromium/getting-started/manifest-format.md
> +    // Recommended
```suggestion
    // If `background` is included, the following is recommended
```

2021-06-08 20:23 UTC, Reezaali commented on microsoft-edge/extensions-chromium/getting-started/manifest-format.md
> +    // Optional
```suggestion
    // If `background` is included, the following is optional
```

2021-06-08 20:23 UTC, Reezaali commented on microsoft-edge/extensions-chromium/getting-started/manifest-format.md
> +    "matches": ["*://*.example.com/*"]
```suggestion
    "matches": ["*://*.contoso.com/*"]
```

2021-06-08 20:25 UTC, Reezaali requested changes
Please review my comments below. Thank you.

2021-06-08 22:58 UTC, opbld33 commented
Docs Build status updates of commit _[8771a23](https://github.com/MicrosoftDocs/edge-developer/commits/8771a2325e75a8948020936014f698fef8514728)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/extensions-chromium/getting-started/manifest-format.md](https://github.com/MicrosoftDocs/edge-developer/blob/gebansal-mv3-update/microsoft-edge/extensions-chromium/getting-started/manifest-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/manifest-format?branch=pr-en-us-1267) |
[microsoft-edge/toc.yml](https://github.com/MicrosoftDocs/edge-developer/blob/gebansal-mv3-update/microsoft-edge/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/manifest-format?branch=pr-en-us-1267) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C8%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202106082257205840-1267%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kg2DiN4Cb6a6IdAJpwS1rj23D1DMC5URg1WsdU175%2B4%3D&st=2021-06-08T22%3A53%3A00Z&se=2021-07-09T22%3A58%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-08 23:39 UTC, Reezaali approved these changes

2021-06-08 23:40 UTC, opbld33 commented
Docs Build status updates of commit _[72071c2](https://github.com/MicrosoftDocs/edge-developer/commits/72071c20b1e33010ac76d1463048746d67c81003)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/extensions-chromium/getting-started/manifest-format.md](https://github.com/MicrosoftDocs/edge-developer/blob/gebansal-mv3-update/microsoft-edge/extensions-chromium/getting-started/manifest-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/manifest-format?branch=pr-en-us-1267) |
[microsoft-edge/toc.yml](https://github.com/MicrosoftDocs/edge-developer/blob/gebansal-mv3-update/microsoft-edge/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/manifest-format?branch=pr-en-us-1267) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C8%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202106082340091379-1267%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QJFqoJkZZK1J%2FHUlrozbQHjiHuPf4rPR3MebTU57B8Q%3D&st=2021-06-08T23%3A35%3A46Z&se=2021-07-09T23%3A40%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-08 23:41 UTC, merged