Presented Selenium as one possible WebDriver testing framework
MicrosoftDocs/edge-developer pull request #1305
Opened 2021-06-23 19:48 UTC by mikehoffms

2021-06-23 19:48 UTC, opbld31 commented
Docs Build status updates of commit _[1bc4619](https://github.com/MicrosoftDocs/edge-developer/commits/1bc4619440aebcd0864c748e55d1c59be43bad7c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webdriver-chromium/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/webdriver-options/microsoft-edge/webdriver-chromium/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/index?branch=pr-en-us-1305) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C23%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202106231948098205-1305%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=I9zITPM%2Fw8Cooa5xaWXEeAeKHlA8Lr176yTWxS1WBkg%3D&st=2021-06-23T19%3A43%3A37Z&se=2021-07-24T19%3A48%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-23 21:19 UTC, bwalderman requested changes

2021-06-23 21:19 UTC, bwalderman commented on microsoft-edge/webdriver-chromium/index.md
> +[Download the WebDriver language binding of your choice][SeleniumDownloads].  If you are using Selenium, the Microsoft Edge team recommends [Selenium 4.0.0-beta2][NugetPackagesSeleniumWebdriver400bet
I think this link has caused some of the confusion that prompted this bug. It goes to the Selenium download site, so it makes it seem as if the Selenium variants are your only choices as a user. Maybe we should just get rid of this link?

2021-06-23 23:34 UTC, opbld30 commented
Docs Build status updates of commit _[f082037](https://github.com/MicrosoftDocs/edge-developer/commits/f08203736d41465bfdfc64df7a05de8a5c967400)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webdriver-chromium/capabilities-edge-options.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/webdriver-options/microsoft-edge/webdriver-chromium/capabilities-edge-options.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/capabilities-edge-options?branch=pr-en-us-1305) | [Details](#user-content-214e7c5e9fd5cfcd815460777695a0ae-f4699929)
[microsoft-edge/webdriver-chromium/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/webdriver-options/microsoft-edge/webdriver-chromium/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/index?branch=pr-en-us-1305) |

<a id="214e7c5e9fd5cfcd815460777695a0ae-f4699929"></a>
### [microsoft-edge/webdriver-chromium/capabilities-edge-options.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/webdriver-options/microsoft-edge/webdriver-chromium/capabilities-edge-options.md)
 - **Line 16, Column 325**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#choose-a-webdriver-language-binding' in 'webdriver-chromium/index.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C23%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202106232334179156-1305%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YDIeTsJZw4I3LHfO0xFdumdpQ1TRdwWNw6OfZ97YiOU%3D&st=2021-06-23T23%3A29%3A55Z&se=2021-07-24T23%3A34%3A55Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-23 23:48 UTC, opbld33 commented
Docs Build status updates of commit _[cb9baab](https://github.com/MicrosoftDocs/edge-developer/commits/cb9baab12336c910c45027c85f7f7d2e68bf0072)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webdriver-chromium/capabilities-edge-options.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/webdriver-options/microsoft-edge/webdriver-chromium/capabilities-edge-options.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/capabilities-edge-options?branch=pr-en-us-1305) |
[microsoft-edge/webdriver-chromium/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/webdriver-options/microsoft-edge/webdriver-chromium/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/index?branch=pr-en-us-1305) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C23%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202106232347357975-1305%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vV13awY6p9l9UTJRPOrw2Ixh9J9IAPwisw0rOic9Cmg%3D&st=2021-06-23T23%3A43%3A42Z&se=2021-07-24T23%3A48%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-24 00:15 UTC, bwalderman approved these changes
LGTM! Just left a couple suggestions.

2021-06-24 00:15 UTC, bwalderman commented on microsoft-edge/webdriver-chromium/index.md
> +| A WebDriver testing framework | A framework used by test authors to write end-to-end tests and automate browsers.  Provides a language-specific client driver that translates your code into commands
```suggestion
| A WebDriver testing framework | A framework used by test authors to write end-to-end tests and automate browsers.  Provides a language-specific interface that translates your code into commands that Microsoft Edge Driver runs in Microsoft Edge \(Chromium\).  WebDriver testing frameworks exist for all major platforms and languages.  One such framework is Selenium. |
```

2021-06-24 00:15 UTC, bwalderman commented on microsoft-edge/webdriver-chromium/index.md
> +A WebDriver testing framework is used by test authors to write end-to-end tests and automate browsers.  The framework provides a language-specific client driver that translates your code (such as Pyt
```suggestion
A WebDriver testing framework is used by test authors to write end-to-end tests and automate browsers.  The framework provides a language-specific interface that translates your code (such as Python, Java, C#, Ruby, or JavaScript) into commands that Microsoft Edge Driver runs in Microsoft Edge \(Chromium\).  WebDriver testing frameworks exist for all major platforms and languages.
```

2021-06-24 01:08 UTC, opbld32 commented
Docs Build status updates of commit _[48f3b38](https://github.com/MicrosoftDocs/edge-developer/commits/48f3b38be39b8dde149cd3b22a2cd8fc7d400955)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webdriver-chromium/capabilities-edge-options.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/webdriver-options/microsoft-edge/webdriver-chromium/capabilities-edge-options.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/capabilities-edge-options?branch=pr-en-us-1305) |
[microsoft-edge/webdriver-chromium/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/webdriver-options/microsoft-edge/webdriver-chromium/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/index?branch=pr-en-us-1305) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C24%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202106240107398462-1305%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nh3jKP2GDFw0pr2UpWFGy3wfQ%2FmhBR2eBCzPzRYI6jQ%3D&st=2021-06-24T01%3A03%3A51Z&se=2021-07-25T01%3A08%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-29 00:46 UTC, Reezaali requested changes

2021-06-29 00:46 UTC, Reezaali commented on microsoft-edge/webdriver-chromium/index.md
> +| A WebDriver testing framework | A framework used by test authors to write end-to-end tests and automate browsers.  Provides a language-specific interface that translates your code into commands tha
```suggestion
| A WebDriver testing framework | Test authors use a testing framework to write end-to-end tests and automate browsers.  Provides a language-specific interface that translates your code into commands that Microsoft Edge Driver runs in Microsoft Edge \(Chromium\).  WebDriver testing frameworks exist for all major platforms and languages.  One such framework is Selenium. |
```

2021-06-29 00:46 UTC, Reezaali commented on microsoft-edge/webdriver-chromium/index.md
> +After downloading Microsoft Edge Driver, the last component you must download is a WebDriver testing framework.
```suggestion
After downloading Microsoft Edge Driver, the last component you must download is a WebDriver testing framework. Test authors use WebDriver testing frameworks to write end-to-end tests and automate browsers. The framework provides a language-specific interface that translates your code (such as Python, Java, C#, Ruby, or JavaScript) into commands that Microsoft Edge Driver runs in Microsoft Edge \(Chromium\). WebDriver testing frameworks exist for all major platforms and languages.
```

2021-06-29 00:46 UTC, Reezaali commented on microsoft-edge/webdriver-chromium/index.md
> +A WebDriver testing framework is used by test authors to write end-to-end tests and automate browsers.  The framework provides a language-specific interface that translates your code (such as Python,
```suggestion

```

2021-06-29 00:46 UTC, Reezaali commented on microsoft-edge/webdriver-chromium/index.md
> +Even though Microsoft Edge supports IE Mode, you can't use Microsoft Edge Driver with Microsoft Edge to test sites in IE Mode.
```suggestion
To test sites that require Internet Explorer, use [Internet Explorer Driver][GithubSeleniumHqWikiIEDriver] with Internet Explorer.  Internet Explorer Driver is maintained by the Selenium project.  Even though Microsoft Edge supports IE Mode, you can't use Microsoft Edge Driver with Microsoft Edge to test sites in IE Mode.
```

2021-06-29 00:55 UTC, opbld30 commented
Docs Build status updates of commit _[7c33f1f](https://github.com/MicrosoftDocs/edge-developer/commits/7c33f1f572d4142c95a16d94b3d3e0723b8786ec)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-389796c3)

<a id="389796c3"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C29%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202106290055075296-1305%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UiOQCafOBb%2FeghpwUXGWWvcBBY8YdzAjTs1RNS7GqEI%3D&st=2021-06-29T00%3A50%3A24Z&se=2021-07-30T00%3A55%3A24Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-29 01:08 UTC, opbld33 commented
Docs Build status updates of commit _[017c974](https://github.com/MicrosoftDocs/edge-developer/commits/017c97484bf6864e8269df3fcb906fc579c4f456)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webdriver-chromium/capabilities-edge-options.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/webdriver-options/microsoft-edge/webdriver-chromium/capabilities-edge-options.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/capabilities-edge-options?branch=pr-en-us-1305) |
[microsoft-edge/webdriver-chromium/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/webdriver-options/microsoft-edge/webdriver-chromium/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/index?branch=pr-en-us-1305) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C29%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202106290107303521-1305%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DEjEDN8bonuMZWhUuAdViQSt%2Bif354ujzRaTMgfN9M0%3D&st=2021-06-29T01%3A03%3A09Z&se=2021-07-30T01%3A08%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-29 01:16 UTC, Reezaali approved these changes

2021-06-29 01:16 UTC, merged