New paragraph about saving snippets to disk
MicrosoftDocs/edge-developer pull request #1328
Opened 2021-07-12 12:44 UTC by captainbrosset

This fixes #913 by adding some information about how to save snippets to disk.

2021-07-12 12:46 UTC, opbld33 commented
Docs Build status updates of commit _[d849f8b](https://github.com/captainbrosset/edge-developer/commits/d849f8be928788273803630f8a65e214f05b3430)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/devtools-guide-chromium/javascript/snippets.md](https://github.com/captainbrosset/edge-developer/blob/user/pabrosse/saving-snippets/microsoft-edge/devtools-guide-chromium/javascript/snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/snippets?branch=pr-en-us-1328) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C12%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202107121244541608-1328%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-12T07%3A45%3A40Z&ske=2021-07-19T07%3A50%3A40Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-12T12%3A41%3A08Z&se=2021-08-12T12%3A46%3A08Z&sr=b&sp=r&sig=DNq6t5NsA2RVWjDXHvdcEgLr6Sg7AOEJObEP0J06n0A%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-23 18:53 UTC, mikehoffms requested changes
Minimum change: remove ellipses.
Bigger, optional change: throughout article, apply correct usage of 'select' instead of 'choose', per Microsoft Writing Style Guide.  'select' is almost always correct, instead of 'choose', per MWSG.

2021-07-23 18:53 UTC, mikehoffms commented on microsoft-edge/devtools-guide-chromium/javascript/snippets.md
> +1.  Hover on the Snippet name, open the contextual menu \(right-click\), and choose **Save as...**.
```suggestion
1.  Hover on the Snippet name, open the contextual menu \(right-click\), and select **Save as**.  
```
You might want to Edit this Suggestion to continue to use 'choose' per rest of article.  But, "..." should be deleted, per Microsoft Writing Style Guide.  Public version of "Ellipses" page https://docs.microsoft.com/en-us/style-guide/punctuation/ellipses says "When there's an ellipsis in UI, don’t include it in instructions or procedures.  Example: Select Safety, and then Delete browsing history."

2021-07-23 18:53 UTC, mikehoffms commented on microsoft-edge/devtools-guide-chromium/javascript/snippets.md
>  1.  Hover on the Snippet name, open the contextual menu \(right-click\), and choose **Remove**.
If you want to do a word-change throughout the entire article as part of this PR: change some instances of 'choose' to 'select', per Microsoft Writing Style Guide.  Public version of important page "Describing interactions with UI": https://docs.microsoft.com/en-us/style-guide/procedures-instructions/describing-interactions-with-ui

2021-07-26 07:57 UTC, opbld30 commented
Docs Build status updates of commit _[d6e8cfa](https://github.com/captainbrosset/edge-developer/commits/d6e8cfada60231c77745e017d8b99645da11c371)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/devtools-guide-chromium/javascript/snippets.md](https://github.com/captainbrosset/edge-developer/blob/user/pabrosse/saving-snippets/microsoft-edge/devtools-guide-chromium/javascript/snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/snippets?branch=pr-en-us-1328) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C26%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202107260756520904-1328%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T03%3A07%3A56Z&ske=2021-08-02T03%3A12%3A56Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-26T07%3A52%3A34Z&se=2021-08-26T07%3A57%3A34Z&sr=b&sp=r&sig=Ks5HfzTHRmqgnbUTNo1k7KLSiQPHjpGJQeus%2BwhT3aA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-26 08:00 UTC, opbld32 commented
Docs Build status updates of commit _[cfd8e1e](https://github.com/captainbrosset/edge-developer/commits/cfd8e1eca647cb8538e216f7efabb8c7595fbc93)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/devtools-guide-chromium/javascript/snippets.md](https://github.com/captainbrosset/edge-developer/blob/user/pabrosse/saving-snippets/microsoft-edge/devtools-guide-chromium/javascript/snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/snippets?branch=pr-en-us-1328) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C26%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202107260759410901-1328%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T03%3A12%3A15Z&ske=2021-08-02T03%3A17%3A15Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-26T07%3A55%3A24Z&se=2021-08-26T08%3A00%3A24Z&sr=b&sp=r&sig=lxzpBb3rX%2BcZ7KLSyU9MJspNZgLA08X7adXi4JWgmfA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-26 08:03 UTC, captainbrosset commented
Thank you @mikehoffms. I did the change throughout the article to change almost all occurrences of `choose` with `select`. I left `choose` in 3 sentences since they were about choosing a file or snippets name (so, based on the customer's preference).
I also removed the ellipsis.

2021-07-26 22:10 UTC, mikehoffms approved these changes

2021-07-27 18:36 UTC, merged