Remove references to old edge vscode extension
MicrosoftDocs/edge-developer pull request #1340
Opened 2021-07-16 07:57 UTC by captainbrosset

VSCode now has a built-in browser debugger, but our docs where still
mentioning old information about installing an extension to debug edge.
VSCode also has really good documentation about how to configure the
debugger, so there really isn't a need for us to re-do our own
documentation but should instead link to the existing one.

Fixes #1032.

2021-07-16 07:59 UTC, captainbrosset commented
@codepo8 please take a look at this when you get a chance. It seems like our docs about vscode were a bit outdated. 

The index page was mentioning 3 extensions: the debugger for edge, the edge tools, and webhint.
While the last 2 still exist and are definitely things we want to document, the first one is deprecated as vscode has a built-in browser debugger. 
So I removed references to this on the index page.

And I removed most of the docs from the "debug edge" page and instead linked to https://code.visualstudio.com/docs/nodejs/browser-debugging

What do you think?

2021-07-16 08:09 UTC, opbld30 commented
Docs Build status updates of commit _[2ab87ff](https://github.com/captainbrosset/edge-developer/commits/2ab87ff1797ae29f4acb19d9014f27bf54abb8e6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/visual-studio-code/debugger-for-edge.md](https://github.com/captainbrosset/edge-developer/blob/user/pabrosse/vscode-edge/microsoft-edge/visual-studio-code/debugger-for-edge.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/visual-studio-code/debugger-for-edge?branch=pr-en-us-1340) |
[microsoft-edge/visual-studio-code/index.md](https://github.com/captainbrosset/edge-developer/blob/user/pabrosse/vscode-edge/microsoft-edge/visual-studio-code/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/visual-studio-code/index?branch=pr-en-us-1340) |
[microsoft-edge/visual-studio-code/media/vscode-debugger-install.png](https://github.com/captainbrosset/edge-developer/blob/user/pabrosse/vscode-edge/microsoft-edge/visual-studio-code/media/vscode-debugger-install.png) | :white_check_mark:Succeeded | |
[microsoft-edge/visual-studio-code/media/vscode-edge-tools-install.png](https://github.com/captainbrosset/edge-developer/blob/user/pabrosse/vscode-edge/microsoft-edge/visual-studio-code/media/vscode-edge-tools-install.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/visual-studio-code/index?branch=pr-en-us-1340) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202107160757029167-1340%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T08%3A03%3A27Z&ske=2021-07-23T08%3A08%3A27Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T08%3A04%3A39Z&se=2021-08-16T08%3A09%3A39Z&sr=b&sp=r&sig=B8jpfM2Y%2FRyb4XOzSadAB2Nc7WqJA7RFnioffLqCUps%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-16 08:22 UTC, opbld32 commented
Docs Build status updates of commit _[03ea9b7](https://github.com/captainbrosset/edge-developer/commits/03ea9b7dd3dca2f49752b736bcff6bade93827a3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/toc.yml](https://github.com/captainbrosset/edge-developer/blob/user/pabrosse/vscode-edge/microsoft-edge/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/visual-studio-code/debugger-for-edge?branch=pr-en-us-1340) |
[microsoft-edge/visual-studio-code/debugger-for-edge.md](https://github.com/captainbrosset/edge-developer/blob/user/pabrosse/vscode-edge/microsoft-edge/visual-studio-code/debugger-for-edge.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/visual-studio-code/debugger-for-edge?branch=pr-en-us-1340) |
[microsoft-edge/visual-studio-code/index.md](https://github.com/captainbrosset/edge-developer/blob/user/pabrosse/vscode-edge/microsoft-edge/visual-studio-code/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/visual-studio-code/index?branch=pr-en-us-1340) |
[microsoft-edge/visual-studio-code/media/vscode-debugger-install.png](https://github.com/captainbrosset/edge-developer/blob/user/pabrosse/vscode-edge/microsoft-edge/visual-studio-code/media/vscode-debugger-install.png) | :white_check_mark:Succeeded | |
[microsoft-edge/visual-studio-code/media/vscode-edge-tools-install.png](https://github.com/captainbrosset/edge-developer/blob/user/pabrosse/vscode-edge/microsoft-edge/visual-studio-code/media/vscode-edge-tools-install.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/visual-studio-code/index?branch=pr-en-us-1340) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202107160821248650-1340%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T08%3A02%3A21Z&ske=2021-07-23T08%3A07%3A21Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T08%3A17%3A35Z&se=2021-08-16T08%3A22%3A35Z&sr=b&sp=r&sig=89WmUxcKUQRd14wjMdK6%2Bp0mJnN9%2FtGRZ5VRldP6b9M%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-19 21:08 UTC, Reezaali submitted a review, later dismissed

2021-07-19 21:10 UTC, opbld32 commented
Docs Build status updates of commit _[f55c6da](https://github.com/captainbrosset/edge-developer/commits/f55c6da42718bf7c7798677794f8ca5e50590bd0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/toc.yml](https://github.com/captainbrosset/edge-developer/blob/user/pabrosse/vscode-edge/microsoft-edge/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/visual-studio-code/debugger-for-edge?branch=pr-en-us-1340) |
[microsoft-edge/visual-studio-code/debugger-for-edge.md](https://github.com/captainbrosset/edge-developer/blob/user/pabrosse/vscode-edge/microsoft-edge/visual-studio-code/debugger-for-edge.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/visual-studio-code/debugger-for-edge?branch=pr-en-us-1340) |
[microsoft-edge/visual-studio-code/index.md](https://github.com/captainbrosset/edge-developer/blob/user/pabrosse/vscode-edge/microsoft-edge/visual-studio-code/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/visual-studio-code/index?branch=pr-en-us-1340) |
[microsoft-edge/visual-studio-code/media/vscode-debugger-install.png](https://github.com/captainbrosset/edge-developer/blob/user/pabrosse/vscode-edge/microsoft-edge/visual-studio-code/media/vscode-debugger-install.png) | :white_check_mark:Succeeded | |
[microsoft-edge/visual-studio-code/media/vscode-edge-tools-install.png](https://github.com/captainbrosset/edge-developer/blob/user/pabrosse/vscode-edge/microsoft-edge/visual-studio-code/media/vscode-edge-tools-install.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/visual-studio-code/index?branch=pr-en-us-1340) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C19%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202107192109420865-1340%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T02%3A56%3A08Z&ske=2021-07-26T03%3A01%3A08Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-19T21%3A05%3A58Z&se=2021-08-19T21%3A10%3A58Z&sr=b&sp=r&sig=hLeSwD%2Fkj9zs5O24XX900QGR40mwBTLrm0LpThBPGlU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-20 08:22 UTC, captainbrosset commented
@codepo8 mentioned elsewhere that there was already a PR to update the vs code docs. I think I found it: https://github.com/MicrosoftDocs/edge-developer/pull/1053 
Waiting for guidance from Chris on what is the right move before going forward with this PR.

2021-07-23 21:27 UTC, mikehoffms requested changes
Did an Edit pass.

2021-07-23 21:27 UTC, mikehoffms commented on microsoft-edge/visual-studio-code/debugger-for-edge.md
> +description: How to debug Microsoft Edge (Chromium) from Visual Studio Code
update the date: field

2021-07-23 21:27 UTC, mikehoffms commented on microsoft-edge/visual-studio-code/index.md
>  Search the Marketplace for the specific extension and choose **Install**.
update the date: field

2021-07-23 21:27 UTC, mikehoffms commented on microsoft-edge/visual-studio-code/index.md
>  Search the Marketplace for the specific extension and choose **Install**.
change:
navigate to Extensions
to:
navigate to **Extensions**
since it's a UI item to select.

2021-07-23 21:27 UTC, mikehoffms commented on microsoft-edge/visual-studio-code/index.md
>  Search the Marketplace for the specific extension and choose **Install**.
```suggestion
Search the Marketplace for the specific extension and select **Install**.  
```
per https://docs.microsoft.com/en-us/style-guide/procedures-instructions/describing-interactions-with-ui

2021-07-23 21:27 UTC, mikehoffms commented on microsoft-edge/visual-studio-code/index.md
>  Search the Marketplace for the specific extension and choose **Install**.
Change:
lightweight, but powerful 
to:
lightweight but powerful

2021-07-23 21:27 UTC, mikehoffms commented on microsoft-edge/visual-studio-code/index.md
> +   Install the **Microsoft Edge Tools** Visual Studio Code extension
Change:
Hints appear as inline underlines and are summarized
to:
Hints appear as wavy underlines in the text editor, and are summarized

2021-07-26 08:32 UTC, captainbrosset commented
Thanks @mikehoffms for the review. I'll push a couple of new commits with the corresponding fixes.

2021-07-26 08:35 UTC, opbld31 commented
Docs Build status updates of commit _[2111548](https://github.com/captainbrosset/edge-developer/commits/21115483c12180bbca2bb7a5e9a4faf7e66a4415)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/toc.yml](https://github.com/captainbrosset/edge-developer/blob/user/pabrosse/vscode-edge/microsoft-edge/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/visual-studio-code/debugger-for-edge?branch=pr-en-us-1340) |
[microsoft-edge/visual-studio-code/debugger-for-edge.md](https://github.com/captainbrosset/edge-developer/blob/user/pabrosse/vscode-edge/microsoft-edge/visual-studio-code/debugger-for-edge.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/visual-studio-code/debugger-for-edge?branch=pr-en-us-1340) |
[microsoft-edge/visual-studio-code/index.md](https://github.com/captainbrosset/edge-developer/blob/user/pabrosse/vscode-edge/microsoft-edge/visual-studio-code/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/visual-studio-code/index?branch=pr-en-us-1340) |
[microsoft-edge/visual-studio-code/media/vscode-debugger-install.png](https://github.com/captainbrosset/edge-developer/blob/user/pabrosse/vscode-edge/microsoft-edge/visual-studio-code/media/vscode-debugger-install.png) | :white_check_mark:Succeeded | |
[microsoft-edge/visual-studio-code/media/vscode-edge-tools-install.png](https://github.com/captainbrosset/edge-developer/blob/user/pabrosse/vscode-edge/microsoft-edge/visual-studio-code/media/vscode-edge-tools-install.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/visual-studio-code/index?branch=pr-en-us-1340) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C26%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202107260834280308-1340%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T03%3A06%3A48Z&ske=2021-08-02T03%3A11%3A48Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-26T08%3A30%3A10Z&se=2021-08-26T08%3A35%3A10Z&sr=b&sp=r&sig=0z9WV26AsiiC7fqqBWUdnVW1OwDt98xnfOtgyaqAFRk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-29 17:23 UTC, mikehoffms approved these changes

2021-08-05 02:19 UTC, mikehoffms commented
> @codepo8 please take a look at this when you get a chance. It seems like our docs about vscode were a bit outdated.
> 
> The index page was mentioning 3 extensions: the debugger for edge, the edge tools, and webhint.
> While the last 2 still exist and are definitely things we want to document, the first one is deprecated as vscode has a built-in browser debugger.
> So I removed references to this on the index page.
> 
> And I removed most of the docs from the "debug edge" page and instead linked to https://code.visualstudio.com/docs/nodejs/browser-debugging
> 
> What do you think?

@codepo8 - could you please review & approve this PR?

2021-08-24 12:47 UTC, codepo8 approved these changes
This looks good to me, let's remove the content. #sign_off

2021-08-24 21:25 UTC, merged