doc: typo
MicrosoftDocs/edge-developer pull request #1375
Opened 2021-08-05 19:37 UTC by DanishOnGit

fix typo

2021-08-05 19:38 UTC, opbld32 commented
Docs Build status updates of commit _[8244559](https://github.com/DanishOnGit/edge-developer/commits/8244559db27374445aa33bda0e907d5bab062fee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/devtools-guide-chromium/rendering-tools/index.md](https://github.com/DanishOnGit/edge-developer/blob/patch-1/microsoft-edge/devtools-guide-chromium/rendering-tools/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/rendering-tools/index?branch=pr-en-us-1375) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C5%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202108051937392951-1375%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=%2B%2FsmtnuyZAqKMWr4%2Fd8IT%2F97jSFd0JeNo8kvXx7ojWw%3D&st=2021-08-05T19%3A33%3A53Z&se=2021-09-05T19%3A38%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-05 19:41 UTC, vchapel reviewed
"If you notice" would be better English, and should "jank" be "junk" ... or is there a better word, such as "noise" or "clutter" or "errors" ?

2021-08-05 20:25 UTC, DanishOnGit commented
> "If you notice" would be better English, and should "jank" be "junk" ... or is there a better word, such as "noise" or "clutter" or "errors" ?

Yes "If you notice" is better. Or, "If you are noticing..." also works fine imo. Not sure about the word "jank"  though!

2021-08-05 20:27 UTC, vchapel commented
> > "If you notice" would be better English, and should "jank" be "junk" ... or is there a better word, such as "noise" or "clutter" or "errors" ?
> 
> Yes "If you notice" is better. Or, "If you are noticing..." also works fine imo. Not sure about the word "jank" though!

Yes, both introductions are good. We do need a better word than "jank"  B^)

2021-08-05 23:41 UTC, mikehoffms commented on microsoft-edge/devtools-guide-chromium/rendering-tools/index.md
> +If you noticing quite a bit of jank in your JavaScript, you may need to take your analysis to the next level and collect a JavaScript CPU profile.  CPU profiles show where runtime is spent within the
```suggestion
If you notice quite a bit of jank in your JavaScript, you may need to take your analysis to the next level and collect a JavaScript CPU profile.  CPU profiles show where run time is spent within the functions of your page.  Learn how to create CPU profiles in [Speed Up JavaScript Runtime][DevtoolsRenderingToolsJavascriptRuntime].
```
Not sure but also changed "runtime" to "run time" to emphasize time.  Need to check surrounding word-usage of 'runtime', 'run', and 'time', or CPU cycles, per profiling code/ function time.

2021-08-05 23:45 UTC, mikehoffms requested changes
An Edit pass.

2021-08-05 23:47 UTC, mikehoffms commented on microsoft-edge/devtools-guide-chromium/rendering-tools/index.md
> +If you noticing quite a bit of jank in your JavaScript, you may need to take your analysis to the next level and collect a JavaScript CPU profile.  CPU profiles show where runtime is spent within the
Please click Commit suggestion (or apply changes locally, then push).  Then I'll Approve.

2021-08-06 00:43 UTC, opbld30 commented
Docs Build status updates of commit _[48a631d](https://github.com/DanishOnGit/edge-developer/commits/48a631de1e3fc2ae2bb866ca6e0138b23a1ca8e3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/devtools-guide-chromium/rendering-tools/index.md](https://github.com/DanishOnGit/edge-developer/blob/patch-1/microsoft-edge/devtools-guide-chromium/rendering-tools/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/rendering-tools/index?branch=pr-en-us-1375) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C6%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202108060041586616-1375%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=CeFhuta27UC4pnUcrWWU9x2DX4%2FJbWCpgHXa4wj2iiY%3D&st=2021-08-06T00%3A38%3A09Z&se=2021-09-06T00%3A43%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-06 00:45 UTC, mikehoffms approved these changes
An Edit pass.

2021-08-06 16:23 UTC, vchapel approved these changes
LGTM

2021-08-06 17:15 UTC, mikehoffms requested changes
Need to define 'jank' in two articles.

2021-08-06 17:15 UTC, mikehoffms commented on microsoft-edge/devtools-guide-chromium/rendering-tools/index.md
> +If you notice quite a bit of jank in your JavaScript, you may need to take your analysis to the next level and collect a JavaScript CPU profile.  CPU profiles show where runtime is spent within the f
I will (or you could) full-text search "jank" in repo, two articles use the word in visible text, needs to be defined in both articles.  wiktionary: "jank ( uncountable ) ( computing, slang, rare) Perceptible pause in the smooth rendering of a software application 's user interface due to slow operations or poor interface design. quotations ".  I plan to enter Suggestions in two articles in this PR.

2021-08-06 17:28 UTC, mikehoffms commented on microsoft-edge/devtools-guide-chromium/rendering-tools/index.md
> +If you notice quite a bit of jank in your JavaScript, you may need to take your analysis to the next level and collect a JavaScript CPU profile.  CPU profiles show where runtime is spent within the f
```suggestion
If you notice quite a bit of jank (interruptions of rendering) in your JavaScript, you may need to take your analysis to the next level and collect a JavaScript CPU profile.  CPU profiles show where runtime is spent within the functions of your page.  Learn how to create CPU profiles in [Speed up JavaScript runtime][DevtoolsRenderingToolsJavascriptRuntime].
```

2021-08-06 17:30 UTC, opbld30 commented
Docs Build status updates of commit _[13c2f1c](https://github.com/DanishOnGit/edge-developer/commits/13c2f1c5453cc47c3224775a33f0ab2063207e44)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/devtools-guide-chromium/rendering-tools/index.md](https://github.com/DanishOnGit/edge-developer/blob/patch-1/microsoft-edge/devtools-guide-chromium/rendering-tools/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/rendering-tools/index?branch=pr-en-us-1375) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C6%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202108061728562606-1375%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=GRnDf8WbE04psDT4mU8i3QbYXmj7tZhR1cZ9CfXury8%3D&st=2021-08-06T17%3A25%3A10Z&se=2021-09-06T17%3A30%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-06 17:31 UTC, mikehoffms approved these changes

2021-08-06 17:32 UTC, merged

2021-08-06 17:35 UTC, vchapel reviewed
LGTM