Updating the DevTools screenshots to match new Fluent icons 4
MicrosoftDocs/edge-developer pull request #1409
Opened 2021-08-23 13:01 UTC by captainbrosset

This is the 4th PR in a series of PRs to update the DevTools screenshots throughout our docs.

This PR covers the following 2 pages:

TBD

2021-08-23 13:02 UTC, opbld32 commented
Docs Build status updates of commit _[8cbcdca](https://github.com/MicrosoftDocs/edge-developer/commits/8cbcdcaadaf531b6d73fa81d028e9b39a114a866)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/devtools-guide-chromium/device-mode/images/emulated-devices-user-agent-client-hints.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/pabrosse/new-devtools-screenshots-4/microsoft-edge/devtools-guide-chromium/device-mode/images/emulated-devices-user-agent-client-hints.msft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/index?branch=pr-en-us-1409) |
[microsoft-edge/devtools-guide-chromium/device-mode/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/pabrosse/new-devtools-screenshots-4/microsoft-edge/devtools-guide-chromium/device-mode/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/index?branch=pr-en-us-1409) |
[microsoft-edge/devtools-guide-chromium/media/capture-settings-icon.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/pabrosse/new-devtools-screenshots-4/microsoft-edge/devtools-guide-chromium/media/capture-settings-icon.msft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/index?branch=pr-en-us-1409) |
[microsoft-edge/devtools-guide-chromium/media/collect-garbage-icon.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/pabrosse/new-devtools-screenshots-4/microsoft-edge/devtools-guide-chromium/media/collect-garbage-icon.msft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/memory-problems/index?branch=pr-en-us-1409) |
[microsoft-edge/devtools-guide-chromium/media/device-mode-command-menu-throttle.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/pabrosse/new-devtools-screenshots-4/microsoft-edge/devtools-guide-chromium/media/device-mode-command-menu-throttle.msft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/index?branch=pr-en-us-1409) |
[microsoft-edge/devtools-guide-chromium/media/device-mode-network-throttle.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/pabrosse/new-devtools-screenshots-4/microsoft-edge/devtools-guide-chromium/media/device-mode-network-throttle.msft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/index?branch=pr-en-us-1409) |
[microsoft-edge/devtools-guide-chromium/media/device-mode-performance-cpu-throttle.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/pabrosse/new-devtools-screenshots-4/microsoft-edge/devtools-guide-chromium/media/device-mode-performance-cpu-throttle.msft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/index?branch=pr-en-us-1409) |
[microsoft-edge/devtools-guide-chromium/media/device-mode-performance-network-throttle.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/pabrosse/new-devtools-screenshots-4/microsoft-edge/devtools-guide-chromium/media/device-mode-performance-network-throttle.msft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/index?branch=pr-en-us-1409) |
[microsoft-edge/devtools-guide-chromium/media/device-mode-toggle-device-toolbar-click-breakpoint.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/pabrosse/new-devtools-screenshots-4/microsoft-edge/devtools-guide-chromium/media/device-mode-toggle-device-toolbar-click-breakpoint.msft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/index?branch=pr-en-us-1409) |
[microsoft-edge/devtools-guide-chromium/media/device-mode-toggle-device-toolbar-command-menu-network-conditions.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/pabrosse/new-devtools-screenshots-4/microsoft-edge/devtools-guide-chromium/media/device-mode-toggle-device-toolbar-command-menu-network-conditions.msft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/index?branch=pr-en-us-1409) |
[microsoft-edge/devtools-guide-chromium/media/device-mode-toggle-device-toolbar-command-menu-sensors.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/pabrosse/new-devtools-screenshots-4/microsoft-edge/devtools-guide-chromium/media/device-mode-toggle-device-toolbar-command-menu-sensors.msft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/index?branch=pr-en-us-1409) |
[microsoft-edge/devtools-guide-chromium/media/device-mode-toggle-device-toolbar-device-list-edit.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/pabrosse/new-devtools-screenshots-4/microsoft-edge/devtools-guide-chromium/media/device-mode-toggle-device-toolbar-device-list-edit.msft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/index?branch=pr-en-us-1409) |
[microsoft-edge/devtools-guide-chromium/media/device-mode-toggle-device-toolbar-device-list.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/pabrosse/new-devtools-screenshots-4/microsoft-edge/devtools-guide-chromium/media/device-mode-toggle-device-toolbar-device-list.msft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/index?branch=pr-en-us-1409) |
[microsoft-edge/devtools-guide-chromium/media/device-mode-toggle-device-toolbar-device-type-list.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/pabrosse/new-devtools-screenshots-4/microsoft-edge/devtools-guide-chromium/media/device-mode-toggle-device-toolbar-device-type-list.msft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/index?branch=pr-en-us-1409) |
[microsoft-edge/devtools-guide-chromium/media/device-mode-toggle-device-toolbar-handles-highlighted.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/pabrosse/new-devtools-screenshots-4/microsoft-edge/devtools-guide-chromium/media/device-mode-toggle-device-toolbar-handles-highlighted.msft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/index?branch=pr-en-us-1409) |
[microsoft-edge/devtools-guide-chromium/media/device-mode-toggle-device-toolbar-highlighted.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/pabrosse/new-devtools-screenshots-4/microsoft-edge/devtools-guide-chromium/media/device-mode-toggle-device-toolbar-highlighted.msft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/index?branch=pr-en-us-1409) |
[microsoft-edge/devtools-guide-chromium/media/device-mode-toggle-device-toolbar-landscape.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/pabrosse/new-devtools-screenshots-4/microsoft-edge/devtools-guide-chromium/media/device-mode-toggle-device-toolbar-landscape.msft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/index?branch=pr-en-us-1409) |
[microsoft-edge/devtools-guide-chromium/media/device-mode-toggle-device-toolbar-more-options-show-m [...]

2021-08-24 00:53 UTC, mikehoffms requested changes
https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/memory-problems/?branch=pr-en-us-1409
•	Below heading "Visualize memory leaks with Performance panel", add red box in upper right, around FPS, CPU, and HEAP.
•	In "choose the collect garbage force garbage collection button", resize icon to maybe 12px or 16px tall, to match UI and to not push lines apart within paragraph.  Same in "To force garbage collection, choose the collect garbage force garbage collection button while recording."
•	Below "Type Detached in the Class filter textbox to search for detached DOM trees.", The UI in the updated screenshot is mis-painted - resize the UI and retake the capture so the right-pointing triangles are fully rendered.  The sentence below that image uses the word "carats" -- rewriting .md is out of scope for this PR, but ... looking up def'n:  carat - https://www.bing.com/search?q=define%20carat%20typesetting  - "a V-shaped grapheme, usually inverted and sometimes extended, used in proofreading and typography to indicate that additional material needs to be inserted at this point in the text. There is a similar mark, ^, that has a variety of uses in programming, mathematics and other contexts."  Not mentioned there: a carat pointing right, or pivoting from right to down.
•	Below "Expand the carats to investigate a detached tree", add two red boxes, around each upper left down-pointing triangle.
•	In " choose the Stop recording heap profile stop recording button ", make the icon shorter, like 12px or 16px, like in the DevTools UI, or in the UI capture, or like the sentence capital letters.  To not push-apart the line from the line above it, in the paragraph.
•	Below "notice if any blue bars show up on the Allocation instrumentation on timeline, like in the following figure", add red box around the set of blue lines.  Like done in the image below it.
•	Above "Choose the Allocation sampling radio button. If there is a worker on the page, you are able to select that as the profiling target using the dropdown menu next to the Start button.", maybe add red box around Start button.  
•	Same image: Consider making a worker appear if not too time-consuming, then add a red box around the dropdown menu next to the Start button (the dropdown that is supposed to appear if there's a worker).
•	Same image: Why does the Before version show "microsoft-edge-... glitch.me" on the item that's in the Select VM instance box, but the item is merely labelled "(empty)" in the After version of the screenshot?  The result seems contradictory, there is a VM instance, but that instance is (empty).  Its arrow now points down instead of up.
•	Same image: What does "17 600" mean, 17,600 bytes, per UK/US notation?  Maybe add a red box on a column to connect to the sentences.  There's no red box on this image.  Maybe put a red box around one function (createNode()) and its numbers in Self Size & Total Size columns.  That would help interpret the display.

https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/?branch=pr-en-us-1409
•	In section in https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/?branch=pr-en-us-1409#simulate-a-mobile-viewport , in the sentence "Choose Toggle device emulation (Toggle Device Toolbar)" , make the icon shorter, like in the UI and like the height of capital letters of sentence.  The Before version is even bigger/worse. 
•	Consider: that icon in the sentence is dark gray on light gray (the non-selected state), but the screenshot's icon is blue on light gray (the selected state) - should they match?  Screenshot represents the "tool is selected" state so icon is blue foreground, not dark gray foreground.
•	In the image below that sentence, add red box around the Toggle Device Emulation icon/button.  In the Before version of the article, I had to make a concerted effort to see the icon in the screenshot, especially since the mid-sentence icon is a different size (2x) - this proves that a different size of icon in mid-sentence can fail to visually match the screenshot effectively.
•	This tooltip, which is omitted, seems not needed; that 640px is the width is self-evident in practice.  The Before version of image below "Choose a breakpoint to change the width of the viewport so that the media query gets triggered." has a tooltip w/ red box.  The tooltip with a red box in the Before version isn't shown in the After version.  Tip: sometimes you can capture a transient tooltip by pressing PrtScrn rather than Alt Prtscn.  It captures all monitors.  Then paste into Paint, then press Ctrl+PgDn repeatedly to zoom out, then select the small portion of image, paste into fresh Paint, then crop as usual.  
•	In .md file, add "To access the Rotate button, increase the width of the Device Toolbar.".  That is: in the "Note: The Rotate button disappears if your Device Toolbar is narrow.", add text copied & modified from a later section (same situation): "If the Throttle list is hidden, your Device Toolbar is too narrow. To access the Throttle list, increase the width of the Device Toolbar.".  Or delete the image.  This is in section https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/?branch=pr-en-us-1409#rotate-the-viewport-to-landscape-orientation , below "Note: The Rotate button disappears if your Device Toolbar is narrow.", in the .md file, maybe delete(?) "device-mode-toggle-device-toolbar-highlighted.msft.png".  That image is used in multiple sections, including https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/?branch=pr-en-us-1409#simulate-a-mobile-viewport .    
•	In "device-mode-toggle-device-toolbar-options-device-frame-iphone-6.msft.png", consider adding a red box around the top of the phone image, and a red box around the left side of the phone image.  Without that, it took some reading and analysis to understand the point of the pair of images, instead of being explicitly instantly obvious.
•	In "device-mode-toggle-device-toolbar-settings-emulated-devices-add.msft.png", add red box around the "" button, because it wasn't obvious (had to hunt around) what the text/sentence is referring to by "Choose Add custom device."  Rewriting is out of scope, but MWSG says something like "Don't say what kind of UI control it is, unless that's helpful for clarity."  My argument is that the Guide elsewhere says text should make sense without screenshots and vice versa, so the text always should use pattern "Select the Foo button."  Anyway, add red box to help make this connection.
•	In "device-mode-toggle-device-toolbar-rulers.msft.png", add red box around the top ruler and maybe left ruler.  Currently these are 2-col images (small/blurred), and red boxes would help obviate zooming the image to confirm that it shows rulers.
•	In section https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/?branch=pr-en-us-1409#throttle-the-cpu-only , in the sentence "Choose the Performance panel, and choose Capture Settings ( ).", make the icon shorter, like 12px or 16px.  "capture-settings-icon.msft.png"
•	In that section, the sentence "Choose CPU > 4x slowdown or 6x slowdown." mentions the CPU menu so add red box around the word CPU in the screenshot "device-mode-performance-cpu-throttle.msft.png"  , and maybe remove the red box around No throttling", b/c not mentioned in sentence, and add a red box around the 4x and 6x menuitems b/c mentioned in sentence.
•	In section https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/?branch=pr-en-us-1409#throttle-the-network-only , in "device-mode-network-throttle.msft.png", remove red box around "No throttling" (the section tells how to throttle, so don't know if want red box around "No throttling", and the name of the menu per tooltip is "Throttling").  Add red box around Fast 3G & Slow 3G, because those m [...]

2021-09-16 16:07 UTC, opbld33 commented
Docs Build status updates of commit _[82a6a90](https://github.com/MicrosoftDocs/edge-developer/commits/82a6a90b5ad03bb1162275e65fe760eaec275481)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/devtools-guide-chromium/device-mode/images/emulated-devices-user-agent-client-hints.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/pabrosse/new-devtools-screenshots-4/microsoft-edge/devtools-guide-chromium/device-mode/images/emulated-devices-user-agent-client-hints.msft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/index?branch=pr-en-us-1409) |
[microsoft-edge/devtools-guide-chromium/device-mode/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/pabrosse/new-devtools-screenshots-4/microsoft-edge/devtools-guide-chromium/device-mode/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/index?branch=pr-en-us-1409) |
[microsoft-edge/devtools-guide-chromium/media/capture-settings-icon.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/pabrosse/new-devtools-screenshots-4/microsoft-edge/devtools-guide-chromium/media/capture-settings-icon.msft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/index?branch=pr-en-us-1409) |
[microsoft-edge/devtools-guide-chromium/media/clear-icon.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/pabrosse/new-devtools-screenshots-4/microsoft-edge/devtools-guide-chromium/media/clear-icon.msft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/storage/cookies?branch=pr-en-us-1409) |
[microsoft-edge/devtools-guide-chromium/media/collect-garbage-icon.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/pabrosse/new-devtools-screenshots-4/microsoft-edge/devtools-guide-chromium/media/collect-garbage-icon.msft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/memory-problems/index?branch=pr-en-us-1409) |
[microsoft-edge/devtools-guide-chromium/media/delete-icon.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/pabrosse/new-devtools-screenshots-4/microsoft-edge/devtools-guide-chromium/media/delete-icon.msft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/storage/cache?branch=pr-en-us-1409) |
[microsoft-edge/devtools-guide-chromium/media/device-mode-command-menu-throttle.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/pabrosse/new-devtools-screenshots-4/microsoft-edge/devtools-guide-chromium/media/device-mode-command-menu-throttle.msft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/index?branch=pr-en-us-1409) |
[microsoft-edge/devtools-guide-chromium/media/device-mode-network-throttle.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/pabrosse/new-devtools-screenshots-4/microsoft-edge/devtools-guide-chromium/media/device-mode-network-throttle.msft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/index?branch=pr-en-us-1409) |
[microsoft-edge/devtools-guide-chromium/media/device-mode-performance-cpu-throttle.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/pabrosse/new-devtools-screenshots-4/microsoft-edge/devtools-guide-chromium/media/device-mode-performance-cpu-throttle.msft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/index?branch=pr-en-us-1409) |
[microsoft-edge/devtools-guide-chromium/media/device-mode-performance-network-throttle.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/pabrosse/new-devtools-screenshots-4/microsoft-edge/devtools-guide-chromium/media/device-mode-performance-network-throttle.msft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/index?branch=pr-en-us-1409) |
[microsoft-edge/devtools-guide-chromium/media/device-mode-toggle-device-toolbar-click-breakpoint.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/pabrosse/new-devtools-screenshots-4/microsoft-edge/devtools-guide-chromium/media/device-mode-toggle-device-toolbar-click-breakpoint.msft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/index?branch=pr-en-us-1409) |
[microsoft-edge/devtools-guide-chromium/media/device-mode-toggle-device-toolbar-command-menu-network-conditions.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/pabrosse/new-devtools-screenshots-4/microsoft-edge/devtools-guide-chromium/media/device-mode-toggle-device-toolbar-command-menu-network-conditions.msft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/index?branch=pr-en-us-1409) |
[microsoft-edge/devtools-guide-chromium/media/device-mode-toggle-device-toolbar-command-menu-sensors.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/pabrosse/new-devtools-screenshots-4/microsoft-edge/devtools-guide-chromium/media/device-mode-toggle-device-toolbar-command-menu-sensors.msft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/index?branch=pr-en-us-1409) |
[microsoft-edge/devtools-guide-chromium/media/device-mode-toggle-device-toolbar-device-list-edit.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/pabrosse/new-devtools-screenshots-4/microsoft-edge/devtools-guide-chromium/media/device-mode-toggle-device-toolbar-device-list-edit.msft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/index?branch=pr-en-us-1409) |
[microsoft-edge/devtools-guide-chromium/media/device-mode-toggle-device-toolbar-device-list.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/pabrosse/new-devtools-screenshots-4/microsoft-edge/devtools-guide-chromium/media/device-mode-toggle-device-toolbar-device-list.msft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/index?branch=pr-en-us-1409) |
[microsoft-edge/devtools-guide-chromium/media/device-mode-toggle-device-toolbar-device-type-list.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/pabrosse/new-devtools-screenshots-4/microsoft-edge/devtools-guide-chromium/media/device-mode-toggle-device-toolbar-device-type-list.msft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/index?branch=pr-en-us-1409) |
[microsoft-edge/devtools-guide-chromium/media/device-mode-toggle-device-toolbar-handles-highlighted.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/pabrosse/new-devtools-screenshots-4/microsoft-edge/devtools-guide-chromium/media/device-mode-toggle-device-toolbar-handles-highlighted.msft.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/index?branch=pr-en-us-1409) |
[microsoft-edge/devtools-guide-chromium/media/device-mode-toggle-device-toolbar-highlighted.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/pabrosse/new-devtools-screenshots-4/microsoft-edge/devtools-guide-chromium/medi [...]

2021-09-16 16:07 UTC, captainbrosset commented
@mikehoffms thanks so much for the detailed review. I think I addressed all must-haves in the new commit. I left out the "consider" items for now, to keep this PR small enough.

2021-09-16 16:48 UTC, mikehoffms approved these changes

2021-09-16 16:48 UTC, merged