Update index.md
MicrosoftDocs/edge-developer pull request #1480
Opened 2021-09-24 12:26 UTC by chgangwa

Requesting a section to be updated in "Edge Privacy White paper" for the users to learn how to the data is managed when the Travel toggle settings is on for them. This content has been approved and signed off by the Privacy team. Kindly approve and publish.

2021-09-24 12:27 UTC, opbld32 commented
Docs Build status updates of commit _[080d508](https://github.com/chgangwa/edge-developer/commits/080d5080f3af503ed18bff8f82e19753631385f6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/privacy-whitepaper/index.md](https://github.com/chgangwa/edge-developer/blob/patch-1/microsoft-edge/privacy-whitepaper/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/privacy-whitepaper/index?branch=pr-en-us-1480) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C24%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202109241226595459-1480%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-25T12%3A27%3A41Z&sr=b&sp=r&sig=5033gzO0hZhxMwiYH7JCgS8Kr9WnHSWXaHswd7WPmIQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-24 17:25 UTC, opbld33 commented
Docs Build status updates of commit _[6bacd4c](https://github.com/chgangwa/edge-developer/commits/6bacd4c06d394f3b96fbd36ed5f81320b8a28ec8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/privacy-whitepaper/index.md](https://github.com/chgangwa/edge-developer/blob/patch-1/microsoft-edge/privacy-whitepaper/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/privacy-whitepaper/index?branch=pr-en-us-1480) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C24%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202109241724234738-1480%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-25T17%3A25%3A05Z&sr=b&sp=r&sig=LufDCj5%2BKB5KtlYzG2OXp3XcypddNNP8WD0PtBnLbqc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-24 17:37 UTC, mikehoffms commented on microsoft-edge/privacy-whitepaper/index.md
> +The Microsoft Edge travel feature requires sharing of cookie information with Bing. For example, the cookies may be used for debugging, fraud detection, and analytics. When a user visits Bing.com on
@vchapel - curly quotes, &, other fixes needed.  
public version of MWSG but I'd use internal version + Word version: https://docs.microsoft.com/en-us/style-guide/welcome/

2021-09-24 18:29 UTC, opbld32 commented
Docs Build status updates of commit _[44e0a4b](https://github.com/chgangwa/edge-developer/commits/44e0a4b7ca68a878d62ec14625472ca6c6486587)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/privacy-whitepaper/index.md](https://github.com/chgangwa/edge-developer/blob/patch-1/microsoft-edge/privacy-whitepaper/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/privacy-whitepaper/index?branch=pr-en-us-1480) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C24%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202109241828248132-1480%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-25T18%3A29%3A09Z&sr=b&sp=r&sig=45K3%2BhIooyf6JEuDjC4Tdpdc5bAE6OuGxVtddWxutLQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-24 18:30 UTC, mikehoffms commented on microsoft-edge/privacy-whitepaper/index.md
> +<!-- todo: revise/delete/update.  'travel' is not found in Settings in stable or in Canary 96 -->
@chgangwa - the word 'travel' doesn't appear in Settings.  Is this a future feature?  Delete this paragraph?

2021-09-24 18:35 UTC, mikehoffms requested changes
Revise, delete, or comment-out the paragraph about the Travel setting; I'm not seeing such a setting.
Other than that, the Writer/Editor pass is done.

2021-09-24 18:43 UTC, opbld31 commented
Docs Build status updates of commit _[aae7785](https://github.com/chgangwa/edge-developer/commits/aae7785eee3a874d84ff6c8952da93f67c2de00e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/privacy-whitepaper/index.md](https://github.com/chgangwa/edge-developer/blob/patch-1/microsoft-edge/privacy-whitepaper/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/privacy-whitepaper/index?branch=pr-en-us-1480) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C24%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202109241842162658-1480%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-25T18%3A43%3A01Z&sr=b&sp=r&sig=gBYtoaN8aUDxoENw8ZPEh0O5Qg0xp4JOjrTERc416Mo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-24 18:45 UTC, mikehoffms approved these changes

2021-09-24 18:48 UTC, mikehoffms commented
I'm keeping @vchapel as a Reviewer just for awareness in light of other in-process PRs.

2021-09-24 20:04 UTC, vchapel approved these changes
LGTM

2021-11-04 00:58 UTC, mikehoffms commented
@chgangwa - I moved the Travel section down, in alphabetical order like other sections.

2021-11-04 02:13 UTC, mikehoffms commented on microsoft-edge/privacy-whitepaper/index.md
>  Microsoft Edge is made possible by the [Chromium][ChromiumMain] open-source project and other open-source software.  To view all of the software credits, navigate to `edge://credits`.  [Google Chrome
@dalenaMSFT - I removed the dup paragraph.  You pointed it out in a different PR which is currently open.  The dup paragraph came in through a previous PR that's closed/merged to "master" & "live".  The present PR uses the old square brackets convention for URLs (in both copies of the dup paragraph).

2021-11-04 17:59 UTC, opbld30 commented
Docs Build status updates of commit _[90a4f61](https://github.com/chgangwa/edge-developer/commits/90a4f61b1de51ccba6b00907dfe571e1732601dc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/privacy-whitepaper/index.md](https://github.com/chgangwa/edge-developer/blob/patch-1/microsoft-edge/privacy-whitepaper/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/privacy-whitepaper/index?branch=pr-en-us-1480) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C4%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202111041758149669-1480%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-05T17%3A59%3A45Z&sr=b&sp=r&sig=aOfWgU5B5sZWQ%2FKIO5paFnTAn1dlHNDk8VGP74dMiVQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-05 00:10 UTC, opbld33 commented
Docs Build status updates of commit _[1ddf465](https://github.com/chgangwa/edge-developer/commits/1ddf465a4d001e40a5bccbaebd24945cd01f05db)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/privacy-whitepaper/index.md](https://github.com/chgangwa/edge-developer/blob/patch-1/microsoft-edge/privacy-whitepaper/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/privacy-whitepaper/index?branch=pr-en-us-1480) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C5%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202111050010201566-1480%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-06T00%3A10%3A52Z&sr=b&sp=r&sig=TUd5tjs2JZypg%2FId4PGEOvjp2zJY2GbEjhzmQNkAzLc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-05 00:12 UTC, mikehoffms commented on microsoft-edge/privacy-whitepaper/index.md
>  Microsoft Edge is made possible by the [Chromium][ChromiumMain] open-source project and other open-source software.  To view all of the software credits, navigate to `edge://credits`.  [Google Chrome
@dalenaMSFT - please review & approve this PR.

2021-11-05 00:31 UTC, dalenaMSFT requested changes
For the travel section, in the instructions to turn off, can we simplify the first item to just the first part (Navigate to `edge://settings/privacy`), and drop the "one way to..." part?

2021-11-05 00:43 UTC, opbld33 commented
Docs Build status updates of commit _[202f952](https://github.com/chgangwa/edge-developer/commits/202f952ec33cd05fe802011707b6cce3f354176f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/privacy-whitepaper/index.md](https://github.com/chgangwa/edge-developer/blob/patch-1/microsoft-edge/privacy-whitepaper/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/privacy-whitepaper/index?branch=pr-en-us-1480) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C5%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202111050042379860-1480%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-06T00%3A43%3A08Z&sr=b&sp=r&sig=dvidkYQBgYYM1C0%2FoGKE7Gf4U0vsPqu7uO4viPmoNA8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-05 01:17 UTC, mikehoffms commented
> For the travel section, in the instructions to turn off, can we simplify the first item to just the first part (Navigate to `edge://settings/privacy`), and drop the "one way to..." part?

@dalenaMSFT - Fixed.  Please re-review & when ready, approve this PR.

2021-11-05 17:24 UTC, dalenaMSFT approved these changes

2021-11-08 19:04 UTC, merged