Removed remaining commented-out ref links, various cleanup
MicrosoftDocs/edge-developer pull request #1562
Opened 2021-11-06 02:22 UTC by mikehoffms

2021-11-06 02:24 UTC, opbld31 commented
Docs Build status updates of commit _[8400c55](https://github.com/MicrosoftDocs/edge-developer/commits/8400c552bbd321817ca077d0c3cb17a52ff6b17e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/devtools-guide-chromium/console/utilities.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/console/utilities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/console/utilities?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/coverage/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/coverage/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/coverage/index?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/device-mode/orientation.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/device-mode/orientation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/orientation?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/evaluate-performance/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/evaluate-performance/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/evaluate-performance/index?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/javascript/breakpoints.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/javascript/breakpoints.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/breakpoints?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/javascript/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/javascript/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/index?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/network/reference.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/network/reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/network/reference?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/open/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/open/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/open/index?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/remote-debugging/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/remote-debugging/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/remote-debugging/index?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/rendering-tools/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/rendering-tools/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/rendering-tools/index?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/speed/get-started.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/speed/get-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/speed/get-started?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/whats-new/2019/12/devtools.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/whats-new/2019/12/devtools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2019/12/devtools?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/whats-new/2020/05/devtools.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/whats-new/2020/05/devtools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2020/05/devtools?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/whats-new/2020/06/devtools.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/whats-new/2020/06/devtools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2020/06/devtools?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/whats-new/2020/08/devtools.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/whats-new/2020/08/devtools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2020/08/devtools?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/whats-new/2020/11/devtools.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/whats-new/2020/11/devtools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2020/11/devtools?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/whats-new/2021/04/devtools.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/whats-new/2021/04/devtools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2021/04/devtools?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/whats-new/2021/09/devtools.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/whats-new/2021/09/devtools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2021/09/devtools?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/workspaces/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/workspaces/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/workspaces/index?branch=pr-en-us-1562) |
[microsoft-edge/extensions-chromium/getting-started/part1-simple-extension.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/extensions-chromium/getting-started/part1-simple-extension.md) | :white_check_mark:Succeeded  [...]

2021-11-06 03:07 UTC, opbld32 commented
Docs Build status updates of commit _[73afa82](https://github.com/MicrosoftDocs/edge-developer/commits/73afa82eb0832a15dc593ffb1e7bdadff1b0882e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/devtools-guide-chromium/console/utilities.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/console/utilities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/console/utilities?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/coverage/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/coverage/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/coverage/index?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/device-mode/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/device-mode/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/index?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/device-mode/orientation.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/device-mode/orientation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/orientation?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/evaluate-performance/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/evaluate-performance/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/evaluate-performance/index?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/evaluate-performance/performance-reference.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/evaluate-performance/performance-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/evaluate-performance/performance-reference?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/javascript/background-services.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/javascript/background-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/background-services?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/javascript/breakpoints.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/javascript/breakpoints.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/breakpoints?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/javascript/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/javascript/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/index?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/javascript/source-maps.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/javascript/source-maps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/source-maps?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/memory-problems/allocation-profiler.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/memory-problems/allocation-profiler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/memory-problems/allocation-profiler?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/memory-problems/heap-snapshots.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/memory-problems/heap-snapshots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/memory-problems/heap-snapshots?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/memory-problems/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/memory-problems/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/memory-problems/index?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/network/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/network/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/network/index?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/network/reference.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/network/reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/network/reference?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/open/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/open/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/open/index?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/progressive-web-apps/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/progressive-web-apps/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/progressive-web-apps/index?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/remote-debugging/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/remote-debugging/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/remote-debugging/index?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/rendering-tools/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/rendering-tools/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/rendering-tools/index?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/security/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/security/index.md) | :whit [...]

2021-11-08 08:16 UTC, captainbrosset requested changes

2021-11-08 08:16 UTC, captainbrosset commented on microsoft-edge/devtools-guide-chromium/javascript/source-maps.md
> +no longer in original file:
I'm not sure I understand what you mean by "no longer in original file". Can you explain what this line is meant for?

2021-11-08 08:16 UTC, captainbrosset commented on microsoft-edge/devtools-guide-chromium/security/index.md
> +**Mixed content**<!--[mixed content](/web/fundamentals/security/prevent-mixed-content/what-is-mixed-content)--> means that the main origin of a page is secure, but the page requested resources from n
I see you've done this a few times in this PR: removed a commented-out reference link from the bottom of the page, and added it as a commented-out inline link next to the corresponding word.

I don't know if the same concept applies here, but when I was doing development, we'd always delete commented-out code. Code that doesn't run is extremely unlikely to ever be used again, and keeping sections of it commented-out doesn't help anybody.
I tend to think that the same thing applies here. The article is likely to evolve over time and the link will remain commented-out.

I would suggest to either use it here (maybe it is useful for users to go and find out more about mixed content), or delete the comment entirely.
What do you think?

2021-11-08 08:16 UTC, captainbrosset commented on microsoft-edge/devtools-guide-chromium/security/index.md
> +**Mixed content**<!--[mixed content](/web/fundamentals/security/prevent-mixed-content/what-is-mixed-content)--> means that the main origin of a page is secure, but the page requested resources from n
Note that I understand that this PR is already a good cleanup of the remaining ref links. So it is 100% ok to not answer the above question in the scope of this PR. Land it as is, and then figure out what we want to do with the commented-out links.

2021-11-08 21:40 UTC, mikehoffms commented on microsoft-edge/devtools-guide-chromium/memory-problems/index.md
> +<!-- [hngd](https://jsfiddle.net/kaycebasques/tmtbw8ef/) -->
Keeping these commented-out links.  In a later PR, compare the original .md file in the other repo, Find these URLs there, analyze, possibly add a todo comment here, or link to the destinations if available at that time and uncomment the link.

2021-11-08 22:08 UTC, opbld33 commented
Docs Build status updates of commit _[5917793](https://github.com/MicrosoftDocs/edge-developer/commits/59177933ffc22b4760a9e33c5a10a9b84f0a88e0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/devtools-guide-chromium/console/utilities.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/console/utilities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/console/utilities?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/coverage/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/coverage/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/coverage/index?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/device-mode/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/device-mode/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/index?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/device-mode/orientation.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/device-mode/orientation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/orientation?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/evaluate-performance/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/evaluate-performance/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/evaluate-performance/index?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/evaluate-performance/performance-reference.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/evaluate-performance/performance-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/evaluate-performance/performance-reference?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/javascript/background-services.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/javascript/background-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/background-services?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/javascript/breakpoints.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/javascript/breakpoints.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/breakpoints?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/javascript/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/javascript/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/index?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/javascript/source-maps.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/javascript/source-maps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/source-maps?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/memory-problems/allocation-profiler.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/memory-problems/allocation-profiler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/memory-problems/allocation-profiler?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/memory-problems/heap-snapshots.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/memory-problems/heap-snapshots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/memory-problems/heap-snapshots?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/memory-problems/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/memory-problems/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/memory-problems/index?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/network/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/network/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/network/index?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/network/reference.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/network/reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/network/reference?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/open/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/open/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/open/index?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/progressive-web-apps/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/progressive-web-apps/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/progressive-web-apps/index?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/remote-debugging/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/remote-debugging/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/remote-debugging/index?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/rendering-tools/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/rendering-tools/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/rendering-tools/index?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/security/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/security/index.md) | :whit [...]

2021-11-09 08:23 UTC, captainbrosset approved these changes
Approved based on offline conversations. We're keeping the commented-out links for now.

2021-11-09 22:05 UTC, opbld31 commented
Docs Build status updates of commit _[b2aae96](https://github.com/MicrosoftDocs/edge-developer/commits/b2aae963f69acf3effd2e28faabb6ada7b9bb33b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/devtools-guide-chromium/console/utilities.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/console/utilities.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/console/utilities?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/coverage/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/coverage/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/coverage/index?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/device-mode/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/device-mode/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/index?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/device-mode/orientation.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/device-mode/orientation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/device-mode/orientation?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/evaluate-performance/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/evaluate-performance/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/evaluate-performance/index?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/evaluate-performance/performance-reference.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/evaluate-performance/performance-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/evaluate-performance/performance-reference?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/javascript/background-services.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/javascript/background-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/background-services?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/javascript/breakpoints.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/javascript/breakpoints.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/breakpoints?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/javascript/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/javascript/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/index?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/javascript/source-maps.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/javascript/source-maps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/source-maps?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/memory-problems/allocation-profiler.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/memory-problems/allocation-profiler.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/memory-problems/allocation-profiler?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/memory-problems/heap-snapshots.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/memory-problems/heap-snapshots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/memory-problems/heap-snapshots?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/memory-problems/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/memory-problems/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/memory-problems/index?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/network/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/network/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/network/index?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/network/reference.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/network/reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/network/reference?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/open/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/open/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/open/index?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/progressive-web-apps/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/progressive-web-apps/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/progressive-web-apps/index?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/remote-debugging/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/remote-debugging/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/remote-debugging/index?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/rendering-tools/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/rendering-tools/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/rendering-tools/index?branch=pr-en-us-1562) |
[microsoft-edge/devtools-guide-chromium/security/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/remove-remaining-ref-links/microsoft-edge/devtools-guide-chromium/security/index.md) | :whit [...]

2021-11-09 22:05 UTC, merged