updated doc to note missing features
MicrosoftDocs/edge-developer pull request #1609
Opened 2021-12-02 21:15 UTC by jasonstephen15

2021-12-02 21:15 UTC, opbld31 commented
Docs Build status updates of commit _[27af295](https://github.com/MicrosoftDocs/edge-developer/commits/27af2951a7d3cd050484dcece0e771fbb03cdceb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/get-started/winui2.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/jasteph/winuiupdate/microsoft-edge/webview2/get-started/winui2.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui2?branch=pr-en-us-1609) | [Details](#user-content-03166b69ff79ccfc82cb0d5fa4af7f48-84cf83e2)
[microsoft-edge/webview2/get-started/winui.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/jasteph/winuiupdate/microsoft-edge/webview2/get-started/winui.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui?branch=pr-en-us-1609) |

<a id="03166b69ff79ccfc82cb0d5fa4af7f48-84cf83e2"></a>
### [microsoft-edge/webview2/get-started/winui2.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/jasteph/winuiupdate/microsoft-edge/webview2/get-started/winui2.md)
 - **Line 21, Column 130**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /microsoft-edge/webview2/reference/winrt/microsoft_web_webview2_core/corewebview2downloadstartingeventargs?view=webview2-winrt-1.0.1054.31. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C2%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202112022115130331-1609%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-02T21%3A15%3A54Z&sr=b&sp=r&sig=Hbuq6QjJRIuK0hB8aWsFvizUD%2FhFkbBqlCMl84iZkc8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-02 21:27 UTC, vchapel commented
@jasonstephen15 you can see the link suggestion. I'm not sure if you need it to be a specific version or not. Other than that I think it looks good.

2021-12-02 21:28 UTC, vchapel commented on microsoft-edge/webview2/get-started/winui2.md
> +> * Download UI -- Note: in order to maintain compatability, developers should manually disable this feature by intercepting the [download starting event](/microsoft-edge/webview2/reference/winrt/mic
```suggestion
> * Download UI -- To maintain compatibility, developers should manually disable this feature by intercepting the [download starting event](/microsoft-edge/webview2/reference/winrt/microsoft_web_webview2_core/corewebview2downloadstartingeventargs?view=webview2-winrt-1.0.1054.31).
```

2021-12-02 21:56 UTC, opbld32 commented
Docs Build status updates of commit _[4113160](https://github.com/MicrosoftDocs/edge-developer/commits/4113160370ba8c860fa30a80c7266d2ec1899c8f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/get-started/winui2.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/jasteph/winuiupdate/microsoft-edge/webview2/get-started/winui2.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui2?branch=pr-en-us-1609) | [Details](#user-content-03166b69ff79ccfc82cb0d5fa4af7f48-2ef2121a)
[microsoft-edge/webview2/get-started/winui.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/jasteph/winuiupdate/microsoft-edge/webview2/get-started/winui.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui?branch=pr-en-us-1609) |

<a id="03166b69ff79ccfc82cb0d5fa4af7f48-2ef2121a"></a>
### [microsoft-edge/webview2/get-started/winui2.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/jasteph/winuiupdate/microsoft-edge/webview2/get-started/winui2.md)
 - **Line 21, Column 115**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /microsoft-edge/webview2/reference/winrt/microsoft_web_webview2_core/corewebview2downloadstartingeventargs?view=webview2-winrt-1.0.1054.31. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C2%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202112022154447355-1609%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-02T21%3A56%3A35Z&sr=b&sp=r&sig=QDfGxQp5ohqd3RvcTU5vmWrcmlezBIjXOAeG5KDk2PQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-02 22:58 UTC, champnic requested changes

2021-12-02 22:58 UTC, champnic commented on microsoft-edge/webview2/get-started/winui2.md
> +> The WebView2 WinUI Control is actively being developed. There are some features that will be missing or broken. Some of these include:
"WinUI 2"

2021-12-02 22:58 UTC, champnic commented on microsoft-edge/webview2/get-started/winui2.md
> +> * Download UI -- To maintain compatibility, developers should manually disable this feature by intercepting the [download starting event](/microsoft-edge/webview2/reference/winrt/microsoft_web_webv
I think we should expand on why there's a potential "compatibility" issue here.

2021-12-02 22:58 UTC, champnic commented on microsoft-edge/webview2/get-started/winui2.md
> +> * Save Screenshot
I don't think this is an issue is it? It's the host app side of things that needs to make sure they are using UWP functions for saving a file, which they should be doing anyways.

2021-12-09 19:53 UTC, jasonstephen15 commented
@vchapel - this is good to merge

2021-12-09 19:53 UTC, opbld31 commented
Docs Build status updates of commit _[2279b6c](https://github.com/MicrosoftDocs/edge-developer/commits/2279b6c7a7d384199e532e2ed6f47e85d7e8083e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/get-started/winui2.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/jasteph/winuiupdate/microsoft-edge/webview2/get-started/winui2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui2?branch=pr-en-us-1609) | [Details](#user-content-03166b69ff79ccfc82cb0d5fa4af7f48-09f84d03)
[microsoft-edge/webview2/get-started/winui.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/jasteph/winuiupdate/microsoft-edge/webview2/get-started/winui.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui?branch=pr-en-us-1609) |

<a id="03166b69ff79ccfc82cb0d5fa4af7f48-09f84d03"></a>
### [microsoft-edge/webview2/get-started/winui2.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/jasteph/winuiupdate/microsoft-edge/webview2/get-started/winui2.md)
 - **Line 20, Column 1**: **[Warning: merge-conflict]** `````File contains merge conflict markers.`````
 - **Line 22, Column 239**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /microsoft-edge/webview2/reference/winrt/microsoft_web_webview2_core/corewebview2downloadstartingeventargs?view=webview2-winrt-1.0.1054.31. Otherwise, remove the view parameter.`````
 - **Line 25, Column 115**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /microsoft-edge/webview2/reference/winrt/microsoft_web_webview2_core/corewebview2downloadstartingeventargs?view=webview2-winrt-1.0.1054.31. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C9%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202112091952146134-1609%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-09T19%3A53%3A39Z&sr=b&sp=r&sig=y0oY50O4U2eWuVpETvBwTIoAv0IgPXf%2B%2FXrCHLmvyUw%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-09 19:54 UTC, opbld32 commented
Docs Build status updates of commit _[1b26109](https://github.com/MicrosoftDocs/edge-developer/commits/1b2610963aeed1e342986fbc24d363cb760613da)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/get-started/winui2.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/jasteph/winuiupdate/microsoft-edge/webview2/get-started/winui2.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui2?branch=pr-en-us-1609) | [Details](#user-content-03166b69ff79ccfc82cb0d5fa4af7f48-8b2ac376)
[microsoft-edge/webview2/get-started/winui.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/jasteph/winuiupdate/microsoft-edge/webview2/get-started/winui.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui?branch=pr-en-us-1609) |

<a id="03166b69ff79ccfc82cb0d5fa4af7f48-8b2ac376"></a>
### [microsoft-edge/webview2/get-started/winui2.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/jasteph/winuiupdate/microsoft-edge/webview2/get-started/winui2.md)
 - **Line 21, Column 239**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /microsoft-edge/webview2/reference/winrt/microsoft_web_webview2_core/corewebview2downloadstartingeventargs?view=webview2-winrt-1.0.1054.31. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C9%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202112091952279539-1609%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-09T19%3A54%3A18Z&sr=b&sp=r&sig=D1fEM%2FdZyRJwOjgNgIr2PYVNjYQkAAnghiwJRCIibHc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-09 20:10 UTC, vchapel approved these changes
LGTM

2021-12-09 20:46 UTC, opbld30 commented
Docs Build status updates of commit _[bb8a07e](https://github.com/MicrosoftDocs/edge-developer/commits/bb8a07e26b5fcd6ddf0e029616e4a2f14d278c36)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/get-started/winui2.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/jasteph/winuiupdate/microsoft-edge/webview2/get-started/winui2.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui2?branch=pr-en-us-1609) | [Details](#user-content-03166b69ff79ccfc82cb0d5fa4af7f48-66ccd89d)
[microsoft-edge/webview2/get-started/winui.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/jasteph/winuiupdate/microsoft-edge/webview2/get-started/winui.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui?branch=pr-en-us-1609) |

<a id="03166b69ff79ccfc82cb0d5fa4af7f48-66ccd89d"></a>
### [microsoft-edge/webview2/get-started/winui2.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/jasteph/winuiupdate/microsoft-edge/webview2/get-started/winui2.md)
 - **Line 21, Column 239**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /microsoft-edge/webview2/reference/winrt/microsoft_web_webview2_core/corewebview2downloadstartingeventargs?view=webview2-winrt-1.0.1054.31. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C9%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202112092045355825-1609%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-09T20%3A46%3A18Z&sr=b&sp=r&sig=3XCnwQAszPHD760SAGy5cYlzn%2FjHQNMdpdxrZLldTfk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-09 20:56 UTC, opbld30 commented
Docs Build status updates of commit _[8e56b5b](https://github.com/MicrosoftDocs/edge-developer/commits/8e56b5bc462261aca68fd24fe5d3c1c55b5a2d3d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/get-started/winui.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/jasteph/winuiupdate/microsoft-edge/webview2/get-started/winui.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui?branch=pr-en-us-1609) |
[microsoft-edge/webview2/get-started/winui2.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/jasteph/winuiupdate/microsoft-edge/webview2/get-started/winui2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui2?branch=pr-en-us-1609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C9%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202112092055500895-1609%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-09T20%3A56%3A27Z&sr=b&sp=r&sig=Raj2glYpMZTkieeulMjHxUfhz2U3L4E64n9g7Xe9%2Fes%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-09 21:04 UTC, merged