What's New 97
MicrosoftDocs/edge-developer pull request #1664
Opened 2022-01-08 02:28 UTC by mikehoffms

2022-01-08 02:29 UTC, opbld31 commented
Docs Build status updates of commit _[58b3a47](https://github.com/MicrosoftDocs/edge-developer/commits/58b3a4767af4c8c095ddd0d9c1f008fb0eaf214d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/toc.yml](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C8%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202201080228407050-1664%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-08T02%3A29%3A33Z&sr=b&sp=r&sig=hd2pjJ0ELv8SAo%2Fj8hZFnHuxHGjss05%2BJSTpGnAs5Fw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-11 01:18 UTC, opbld32 commented
Docs Build status updates of commit _[8c07afa](https://github.com/MicrosoftDocs/edge-developer/commits/8c07afab77aa7d4ca884d947adb18e65574b0d18)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) | [Details](#user-content-46dfb28603afd7e475fd6962b4a048e5-ce60abd8)
[microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/3d-view-with-color-theme.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/3d-view-with-color-theme.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/detached-elements-tool.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/detached-elements-tool.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/focus-mode.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/focus-mode.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/toc.yml](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |

<a id="46dfb28603afd7e475fd6962b4a048e5-ce60abd8"></a>
### [microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools.md)
 - **Line 32, Column 3**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/memory-problems/dom-leaks' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 32, Column 3**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/memory-problems/dom-leaks' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C11%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202201110116465649-1664%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-11T01%3A18%3A12Z&sr=b&sp=r&sig=ql6mv%2BKb%2FfpWp8NkI4TSCVpEkfrkP82iEkrZ9KKVFz8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-11 01:23 UTC, opbld32 commented
Docs Build status updates of commit _[7343bee](https://github.com/MicrosoftDocs/edge-developer/commits/7343beea56108fb79fb0ab3d0a3a8ffdf877f242)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/3d-view-with-color-theme.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/3d-view-with-color-theme.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/detached-elements-tool.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/detached-elements-tool.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/focus-mode.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/focus-mode.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/toc.yml](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C11%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202201110122193446-1664%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-11T01%3A23%3A10Z&sr=b&sp=r&sig=TiFsZk1Be7fKEwndf4cHkyQdo1CpEElajyGqE5gslQI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-11 18:45 UTC, opbld31 commented
Docs Build status updates of commit _[e02307e](https://github.com/MicrosoftDocs/edge-developer/commits/e02307e5a4dfd9735c1962435d9b9430d4a79039)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/3d-view-with-color-theme.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/3d-view-with-color-theme.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/detached-elements-tool.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/detached-elements-tool.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/extension-settings-launch-arguments.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/extension-settings-launch-arguments.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/focus-mode.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/focus-mode.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/toc.yml](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C11%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202201111843226667-1664%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-11T18%3A45%3A48Z&sr=b&sp=r&sig=vnjoVX5sqlW%2FTGoiXs2oX7%2FXeUk2TjlX1fXO7QAdzTA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-11 18:58 UTC, opbld31 commented
Docs Build status updates of commit _[0487414](https://github.com/MicrosoftDocs/edge-developer/commits/0487414542884d7b898a6a86e3fdb6240a1be8c1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/3d-view-with-color-theme.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/3d-view-with-color-theme.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/detached-elements-tool.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/detached-elements-tool.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/extension-settings-launch-arguments.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/extension-settings-launch-arguments.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/focus-mode.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/focus-mode.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/toc.yml](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C11%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202201111857211509-1664%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-11T18%3A58%3A28Z&sr=b&sp=r&sig=kfs9w6kSTAqg9E7VGsOvOUXS9KYWJHIcyKeFJT%2B07mw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-11 20:21 UTC, zoherghadyali approved these changes

2022-01-11 20:21 UTC, zoherghadyali commented on microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools.md
> +For more information about the issue that was fixed, see [Bug 36842109: 3D View panel blank after DevTools reload](https://dev.azure.com/microsoft/Edge/_workitems/edit/36842109/) and [Pull request 66
```suggestion
```

These are ADO links and would not work for external readers. I maybe meant to leave them as a comment in the ADO work item if you needed extra info for the announcement. This entire paragraph should be removed.

2022-01-11 20:34 UTC, opbld33 commented
Docs Build status updates of commit _[7f8588e](https://github.com/MicrosoftDocs/edge-developer/commits/7f8588e7a48d015eedf5a27214d4b75defb36af5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/3d-view-with-color-theme.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/3d-view-with-color-theme.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/detached-elements-tool.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/detached-elements-tool.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/extension-settings-launch-arguments.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/extension-settings-launch-arguments.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/focus-mode.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/focus-mode.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/toc.yml](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C11%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202201112033504531-1664%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-11T20%3A34%3A40Z&sr=b&sp=r&sig=kLHmKKevh8gfcuhjmv2P%2BguWiA1GxVWnewEQBHKYMeU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-11 21:12 UTC, hxlnt commented
Focus Mode section: No changes, LGTM!

2022-01-11 21:38 UTC, codepo8 commented on microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools.md
> +*  You now get a warning when you use a deprecated launch version of Microsoft Edge, indicating that you'd miss out on features by using a deprecated version of Microsoft Edge.
Let's remove the "by using a deprecated version of Microsoft Edge." as this is about how Edge is launched from the VS Code side, this isn't about the version of Edge. And it means we don't repeat "deprecated".

2022-01-11 21:39 UTC, codepo8 requested changes
One change to the VS Code extension wording.

2022-01-11 22:22 UTC, opbld32 commented
Docs Build status updates of commit _[e3b87df](https://github.com/MicrosoftDocs/edge-developer/commits/e3b87dfc95faba1e9030ef1ce65ec2e8f13f60c7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/3d-view-with-color-theme.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/3d-view-with-color-theme.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/detached-elements-tool.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/detached-elements-tool.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/extension-settings-launch-arguments.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/extension-settings-launch-arguments.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/focus-mode.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/focus-mode.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/toc.yml](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C11%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202201112221319207-1664%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-11T22%3A22%3A24Z&sr=b&sp=r&sig=SLpfDxb8pJc7T%2FAVecxn7xVSwGEmIkQFMhtUkEsdxzg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-12 23:23 UTC, opbld30 commented
Docs Build status updates of commit _[178d1ea](https://github.com/MicrosoftDocs/edge-developer/commits/178d1eabcc625b7f0b477a624b8d2f750032ef05)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/3d-view-with-color-theme.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/3d-view-with-color-theme.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/detached-elements-tool.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/detached-elements-tool.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/extension-settings-launch-arguments.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/extension-settings-launch-arguments.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/focus-mode.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/focus-mode.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/toc.yml](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C12%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202201122321423459-1664%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-12T23%3A23%3A14Z&sr=b&sp=r&sig=8SI3cI9TVCICqy3iZLzbscUXOY8hb%2FjVj3zKQS5UhKg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-12 23:49 UTC, opbld30 commented
Docs Build status updates of commit _[e0d21d3](https://github.com/MicrosoftDocs/edge-developer/commits/e0d21d3bb7743ddbbfeb287f75474c375147bd46)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/3d-view-with-color-theme.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/3d-view-with-color-theme.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/detached-elements-tool.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/detached-elements-tool.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/extension-settings-launch-arguments.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/extension-settings-launch-arguments.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/focus-mode.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/focus-mode.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/toc.yml](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C12%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202201122348336913-1664%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-12T23%3A49%3A20Z&sr=b&sp=r&sig=Dugupo8WlzbA6GRfo9qhYwKzoStRwC9ivMXFvlhIPDU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-13 20:02 UTC, opbld33 commented
Docs Build status updates of commit _[bf7349b](https://github.com/MicrosoftDocs/edge-developer/commits/bf7349bf74dcc2699886195765db7f6a98f25324)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/3d-view-with-color-theme.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/3d-view-with-color-theme.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/detached-elements-tool.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/detached-elements-tool.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/extension-settings-launch-arguments.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/extension-settings-launch-arguments.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/focus-mode.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/devtools-guide-chromium/whats-new/media/2022/01/focus-mode.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |
[microsoft-edge/toc.yml](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-mhoffman/whats-new-97/microsoft-edge/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2022/01/devtools?branch=pr-en-us-1664) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C13%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202201132001251700-1664%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-13T20%3A02%3A52Z&sr=b&sp=r&sig=ge0J6uUaVYUiWLRsVT6uB80wLU%2BuOdTtA%2B1guDY2vQA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-13 20:03 UTC, merged