Release + prerelease notes for Edge 97/99
MicrosoftDocs/edge-developer pull request #1675
Opened 2022-01-13 19:36 UTC by jasonstephen15

2022-01-13 19:37 UTC, jasonstephen15 commented on microsoft-edge/webview2/release-notes.md
> + (ADDED)
@peiche-jessica - this experimental idl diff showed up in the release section of the script. Not sure why

2022-01-13 19:37 UTC, opbld33 commented
Docs Build status updates of commit _[baf1c94](https://github.com/MicrosoftDocs/edge-developer/commits/baf1c9489a87c8792124012d3995c6d0d6dd24c1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/release-notes.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/jasteph/relnotesEdge97/microsoft-edge/webview2/release-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/release-notes?branch=pr-en-us-1675) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C13%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202201131936281425-1675%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-13T19%3A37%3A58Z&sr=b&sp=r&sig=2OxZrSHxjcv4PjaBBPD%2FFCyc%2FKLd6AkwHvlwuQBufuM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-13 21:20 UTC, vchapel commented on microsoft-edge/webview2/release-notes.md
> +//Ask @Jessica
Change code comment "//" to markdown comment "<!-- -->"

2022-01-13 21:26 UTC, vchapel commented on microsoft-edge/webview2/release-notes.md
> +* Added support for themeing:
I believe "themeing" should be spelled "theming" ... but if so we also have a mistake in the TOC at https://docs.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/react-native/theme-config

2022-01-13 21:28 UTC, vchapel commented on microsoft-edge/webview2/release-notes.md
> +* The ProcessInfo APIs which provides more information about WebView2 [processes](/microsoft-edge/webview2/reference/win32/icorewebview2experimentalprocessinfo?view=webview2-1.0.1083-prerelease&prese
Change "which provides" to just "provide"

2022-01-13 21:43 UTC, oggy22 commented on microsoft-edge/webview2/release-notes.md
> +## 1.0.1071.54
1072

2022-01-13 21:43 UTC, oggy22 commented on microsoft-edge/webview2/release-notes.md
> +Release Date: January 10, 2022
13

2022-01-13 21:43 UTC, opbld30 commented
Docs Build status updates of commit _[990068b](https://github.com/MicrosoftDocs/edge-developer/commits/990068bfaab08a4d05174d70a7ecb0db92522a6c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/release-notes.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/jasteph/relnotesEdge97/microsoft-edge/webview2/release-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/release-notes?branch=pr-en-us-1675) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C13%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202201132142402950-1675%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-13T21%3A43%3A31Z&sr=b&sp=r&sig=yIdVmVVxROTYZVR3lerflHH6DgSNVGhXo2wPlZRBm%2BM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-13 21:44 UTC, oggy22 commented on microsoft-edge/webview2/release-notes.md
> +[NuGet package for WebView2 SDK 1.0.1071.54](https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.1071.54-release)
1072

2022-01-13 22:25 UTC, opbld31 commented
Docs Build status updates of commit _[7758546](https://github.com/MicrosoftDocs/edge-developer/commits/7758546f593757fa6ba9a231e04830f383900549)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/release-notes.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/jasteph/relnotesEdge97/microsoft-edge/webview2/release-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/release-notes?branch=pr-en-us-1675) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C13%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202201132224124343-1675%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-13T22%3A25%3A09Z&sr=b&sp=r&sig=4j4jyA3boNrd%2FDmfPRY%2Fuw2Fd4WrIjxpJfDPDR8ysWQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-13 22:48 UTC, opbld30 commented
Docs Build status updates of commit _[8e79e2c](https://github.com/MicrosoftDocs/edge-developer/commits/8e79e2c4e5580246d1b9d59026c790516971e4af)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/release-notes.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/jasteph/relnotesEdge97/microsoft-edge/webview2/release-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/release-notes?branch=pr-en-us-1675) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C13%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202201132247565063-1675%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-13T22%3A48%3A49Z&sr=b&sp=r&sig=BqhlqJD2sjwAW2hVYBVuEx1K9cPmFXQC3m83SG0NqJw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-13 23:03 UTC, opbld31 commented
Docs Build status updates of commit _[33ae7b9](https://github.com/MicrosoftDocs/edge-developer/commits/33ae7b94b88a5763034c59bd1d58d351d47620b4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/release-notes.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/jasteph/relnotesEdge97/microsoft-edge/webview2/release-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/release-notes?branch=pr-en-us-1675) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C13%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202201132303070760-1675%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-13T23%3A03%3A56Z&sr=b&sp=r&sig=fzZ0n%2BjwFpqN8tLyZ0lnPcNQPeBy6YD%2FaTKQ3XU8m88%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-14 01:31 UTC, jasonstephen15 commented
@Reezaali / @mikehoffms - I think this is good to go. I have commented out the prerelease section for now, while we wait for generation of ref docs. @vchapel has done his edit pass, and I sign off.

2022-01-14 01:33 UTC, jasonstephen15 commented
@vchapel mind approving this? we need an approving review before being able to approve.

2022-01-14 01:39 UTC, opbld30 commented
Docs Build status updates of commit _[9f4967f](https://github.com/MicrosoftDocs/edge-developer/commits/9f4967f512824230b07523876cd21cddf3d86319)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/release-notes.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/jasteph/relnotesEdge97/microsoft-edge/webview2/release-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/release-notes?branch=pr-en-us-1675) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C14%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202201140139129416-1675%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-14T01%3A39%3A58Z&sr=b&sp=r&sig=BLO6cFfx11u5IvkQLw4mFcmGS3NanzQZt64fccP%2B58g%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-14 01:50 UTC, Reezaali requested changes

2022-01-14 01:50 UTC, Reezaali commented on microsoft-edge/webview2/release-notes.md
> +*  The [Download Positioning and Anchoring API](/microsoft-edge/webview2/reference/win32/icorewebview2_9?view=webview2-1.0.1072.54&preserve-view=true).  This API enables:
```suggestion
*  The [Download Positioning and Anchoring API](/microsoft-edge/webview2/reference/win32/icorewebview2_9?view=webview2-1.0.1072.54&preserve-view=true) enables:
```

2022-01-14 01:50 UTC, Reezaali commented on microsoft-edge/webview2/release-notes.md
> +[NuGet package for WebView2 SDK 1.0.1072.54](https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.1072.54-release)
Is the link correct?

2022-01-14 01:50 UTC, Reezaali commented on microsoft-edge/webview2/release-notes.md
> +   *  Make changes in response to the dialog opening and closing.
```suggestion
   *  Making changes in response to the dialog opening and closing.
```

2022-01-14 01:50 UTC, Reezaali commented on microsoft-edge/webview2/release-notes.md
> +*  The following [APIs for iframes](/microsoft-edge/webview2/reference/win32/icorewebview2frame2?view=webview2-1.0.1072.54&preserve-view=true) in WebView2:
```suggestion
*  New [APIs for iframes](/microsoft-edge/webview2/reference/win32/icorewebview2frame2?view=webview2-1.0.1072.54&preserve-view=true):
```

2022-01-14 01:52 UTC, opbld33 commented
Docs Build status updates of commit _[283fca4](https://github.com/MicrosoftDocs/edge-developer/commits/283fca415e0f5304ecf576fb803d2aab68bbaecd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/release-notes.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/jasteph/relnotesEdge97/microsoft-edge/webview2/release-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/release-notes?branch=pr-en-us-1675) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C14%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202201140151385273-1675%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-14T01%3A52%3A27Z&sr=b&sp=r&sig=ZG8jpTlr0DRf0guUbOTJPDF%2FVtOaUu6ArlEETl%2FK5Qg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-14 01:53 UTC, opbld33 commented
Docs Build status updates of commit _[495d888](https://github.com/MicrosoftDocs/edge-developer/commits/495d888084d2fae1773153e3dc807a1b25156749)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/release-notes.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/jasteph/relnotesEdge97/microsoft-edge/webview2/release-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/release-notes?branch=pr-en-us-1675) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C14%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202201140151474323-1675%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-14T01%3A53%3A13Z&sr=b&sp=r&sig=%2F53wjYB4JXNMWbnb8p06aiSFm57BfoE99fpS%2FgZ53uo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-14 01:54 UTC, opbld30 commented
Docs Build status updates of commit _[4736ded](https://github.com/MicrosoftDocs/edge-developer/commits/4736deda3231ba1cc6cc3d19d5a8c228259bbf83)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/release-notes.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/jasteph/relnotesEdge97/microsoft-edge/webview2/release-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/release-notes?branch=pr-en-us-1675) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C14%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202201140152421133-1675%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-14T01%3A54%3A09Z&sr=b&sp=r&sig=yxYpyLVCyWInZkzqGbjTL0DqaiP1WFhTrnub07W0VcU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-14 01:58 UTC, vchapel approved these changes
LGTM

2022-01-14 01:59 UTC, Reezaali approved these changes

2022-01-14 01:59 UTC, merged