Changes to move from private preview to Beta
MicrosoftDocs/edge-developer pull request #1790
Opened 2022-03-11 06:44 UTC by yvsubhash

Changes to move this release from Private Preview to Beta

2022-03-11 06:45 UTC, opbld30 commented
Docs Build status updates of commit _[c7b6c9b](https://github.com/MicrosoftDocs/edge-developer/commits/c7b6c9bfa6c0ecff4f614b15546369bed6ca32a9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/extensions-chromium/publish/api/addons-api-reference.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/syedugundla/docs/beta_changes/microsoft-edge/extensions-chromium/publish/api/addons-api-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/addons-api-reference?branch=pr-en-us-1790) |
[microsoft-edge/extensions-chromium/publish/api/using-addons-api.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/syedugundla/docs/beta_changes/microsoft-edge/extensions-chromium/publish/api/using-addons-api.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/using-addons-api?branch=pr-en-us-1790) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C11%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202203110644567814-1790%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-11T06%3A45%3A46Z&sr=b&sp=r&sig=a%2F5nz0RN4CBu8cd81oGgS48Ng%2Fjcs5WCMhqEfv%2BBXa4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-13 15:23 UTC, ashishnirvana1 commented on microsoft-edge/extensions-chromium/publish/api/using-addons-api.md
> +title: Using the Microsoft Edge Add-ons API (is currently in bea)
The spelling of beta is incorrect @yvsubhash

2022-03-14 07:25 UTC, opbld30 commented
Docs Build status updates of commit _[f14b255](https://github.com/MicrosoftDocs/edge-developer/commits/f14b2553bd4cd94775719f67e4349a220c3245c3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/extensions-chromium/publish/api/addons-api-reference.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/syedugundla/docs/beta_changes/microsoft-edge/extensions-chromium/publish/api/addons-api-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/addons-api-reference?branch=pr-en-us-1790) |
[microsoft-edge/extensions-chromium/publish/api/using-addons-api.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/syedugundla/docs/beta_changes/microsoft-edge/extensions-chromium/publish/api/using-addons-api.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/using-addons-api?branch=pr-en-us-1790) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C14%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202203140724396022-1790%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-14T07%3A25%3A33Z&sr=b&sp=r&sig=os8x%2BlUOxwhysZPD%2FLjxaftDxByNfYkxs5SDAAqBuV4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-14 17:00 UTC, opbld30 commented
Docs Build status updates of commit _[4c1c3e1](https://github.com/MicrosoftDocs/edge-developer/commits/4c1c3e1b33c4f24b682567d846d6cf4b623b998c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/extensions-chromium/publish/api/addons-api-reference.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/syedugundla/docs/beta_changes/microsoft-edge/extensions-chromium/publish/api/addons-api-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/addons-api-reference?branch=pr-en-us-1790) |
[microsoft-edge/extensions-chromium/publish/api/using-addons-api.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/syedugundla/docs/beta_changes/microsoft-edge/extensions-chromium/publish/api/using-addons-api.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/using-addons-api?branch=pr-en-us-1790) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C14%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202203141658531145-1790%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-14T17%3A00%3A32Z&sr=b&sp=r&sig=lrIfqHJZYvIqzr0Qn0k75PazxVauweHX7a0KpB%2BVSz4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-14 17:09 UTC, vchapel approved these changes
LGTM

2022-03-16 16:12 UTC, mikehoffms requested changes
Not ready to merge, TOC still says (Preview) instead of (Beta)

2022-03-16 16:12 UTC, mikehoffms commented on microsoft-edge/extensions-chromium/publish/api/addons-api-reference.md
> +title: Microsoft Edge Add-ons API Reference (is currently in beta)
please change "title:" yaml field x2, titles x2, link text in all .md files that point to these articles, and the TOC titles x2, from (is currently in beta) to simply (Beta)

2022-03-17 09:34 UTC, opbld31 commented
Docs Build status updates of commit _[ec7a8f8](https://github.com/MicrosoftDocs/edge-developer/commits/ec7a8f8c14abda92a3ba88563a35f407b420390b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-0766f319)

<a id="0766f319"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C17%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202203170934096169-1790%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-17T09%3A34%3A42Z&sr=b&sp=r&sig=box7l%2FbtKY7C3ICp5PLzxmnKhitIF1wDVtyNKGPLY0s%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-17 09:38 UTC, opbld31 commented
Docs Build status updates of commit _[df1adf0](https://github.com/MicrosoftDocs/edge-developer/commits/df1adf02af1918c92da30c701a527046b6ef810e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/extensions-chromium/publish/api/addons-api-reference.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/syedugundla/docs/beta_changes/microsoft-edge/extensions-chromium/publish/api/addons-api-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/addons-api-reference?branch=pr-en-us-1790) |
[microsoft-edge/extensions-chromium/publish/api/using-addons-api.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/syedugundla/docs/beta_changes/microsoft-edge/extensions-chromium/publish/api/using-addons-api.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/using-addons-api?branch=pr-en-us-1790) |
[microsoft-edge/extensions-chromium/publish/update-extension.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/syedugundla/docs/beta_changes/microsoft-edge/extensions-chromium/publish/update-extension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/update-extension?branch=pr-en-us-1790) |
[microsoft-edge/toc.yml](https://github.com/MicrosoftDocs/edge-developer/blob/user/syedugundla/docs/beta_changes/microsoft-edge/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/addons-api-reference?branch=pr-en-us-1790) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C17%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202203170937076035-1790%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-17T09%3A38%3A44Z&sr=b&sp=r&sig=u4i%2FXx2dL5aF5FQkwevusBjpgzjhXSM98oTjKTEwfqU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-17 09:43 UTC, vchapel approved these changes
LGTM

2022-03-17 21:07 UTC, opbld33 commented
Docs Build status updates of commit _[0a41a9a](https://github.com/MicrosoftDocs/edge-developer/commits/0a41a9af69172fa40268ff2ebd1783fd73ceec7d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/extensions-chromium/publish/api/addons-api-reference.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/syedugundla/docs/beta_changes/microsoft-edge/extensions-chromium/publish/api/addons-api-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/addons-api-reference?branch=pr-en-us-1790) |
[microsoft-edge/extensions-chromium/publish/api/using-addons-api.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/syedugundla/docs/beta_changes/microsoft-edge/extensions-chromium/publish/api/using-addons-api.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/using-addons-api?branch=pr-en-us-1790) |
[microsoft-edge/extensions-chromium/publish/update-extension.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/syedugundla/docs/beta_changes/microsoft-edge/extensions-chromium/publish/update-extension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/update-extension?branch=pr-en-us-1790) |
[microsoft-edge/toc.yml](https://github.com/MicrosoftDocs/edge-developer/blob/user/syedugundla/docs/beta_changes/microsoft-edge/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/addons-api-reference?branch=pr-en-us-1790) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C17%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202203172106057816-1790%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-17T21%3A07%3A04Z&sr=b&sp=r&sig=fj9Skzd1kSG%2B4mA5r2RDtF76iMgGZJFKJA7zElMJgCg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-17 21:07 UTC, mikehoffms approved these changes

2022-03-18 00:44 UTC, merged