Clarify that WV2 receives the same update as edge
MicrosoftDocs/edge-developer pull request #1885
Opened 2022-04-08 17:59 UTC by liminzhu

2022-04-08 18:01 UTC, opbld32 commented
Docs Build status updates of commit _[63a9bee](https://github.com/liminzhu/edge-developer/commits/63a9bee282f8bed7520c82f25cd657fcdf2956dc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/concepts/distribution.md](https://github.com/liminzhu/edge-developer/blob/main/microsoft-edge/webview2/concepts/distribution.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution?branch=pr-en-us-1885) | [Details](#user-content-a5353b0e3d2b4248136739d2434f83a6-26b79592)

<a id="a5353b0e3d2b4248136739d2434f83a6-26b79592"></a>
### [microsoft-edge/webview2/concepts/distribution.md](https://github.com/liminzhu/edge-developer/blob/main/microsoft-edge/webview2/concepts/distribution.md)
 - **Line 122, Column 99**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/deployedge/microsoft-edge-relnote-stable-channel' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 122, Column 189**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/deployedge/microsoft-edge-relnotes-security' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C8%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202204081759163315-1885%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-09T18%3A01%3A20Z&sr=b&sp=r&sig=bQxCiCSPNUmgm8z248oTWeBL0Vc6gJ0v0jlOpN9Vq6I%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-08 19:42 UTC, opbld32 commented
Docs Build status updates of commit _[3236dc2](https://github.com/liminzhu/edge-developer/commits/3236dc206e8078b260d9f0b25134e5fec5775187)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/concepts/distribution.md](https://github.com/liminzhu/edge-developer/blob/main/microsoft-edge/webview2/concepts/distribution.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution?branch=pr-en-us-1885) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C8%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202204081942042002-1885%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-09T19%3A42%3A41Z&sr=b&sp=r&sig=HhI%2Fnx9gKrOkmXYgBYuE9cXDGRS5oN77mGiwjUiNS6w%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-08 19:47 UTC, vchapel approved these changes
Looks Good To Me, let me know if you agree with my changes @liminzhu and if so we can merge and publish.

2022-04-14 21:07 UTC, mikehoffms commented on microsoft-edge/webview2/concepts/distribution.md
> +*  The WebView2 Runtime updates automatically without more effort from you. It recevices the same Microsoft Edge updates described in [Release notes for Microsoft Edge Stable Channel](/deployedge/mic
```suggestion
*  The WebView2 Runtime updates automatically without requiring any action from you. It receives the same Microsoft Edge updates that are described in [Release notes for Microsoft Edge Stable Channel](/deployedge/microsoft-edge-relnote-stable-channel) and [Release notes for Microsoft Edge Security Updates](/deployedge/microsoft-edge-relnotes-security).
```

2022-04-14 21:09 UTC, mikehoffms requested changes
typo fix

2022-04-14 21:19 UTC, opbld32 commented
Docs Build status updates of commit _[e084e39](https://github.com/liminzhu/edge-developer/commits/e084e39243d296bfce00feb589bd943964741872)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/concepts/distribution.md](https://github.com/liminzhu/edge-developer/blob/main/microsoft-edge/webview2/concepts/distribution.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution?branch=pr-en-us-1885) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C14%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202204142119126513-1885%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-15T21%3A19%3A58Z&sr=b&sp=r&sig=4Zp9xdELTxPMdxOpG4sKoxc2HJ62rV%2B2syPu3k%2BGuiw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-14 21:20 UTC, mikehoffms approved these changes

2022-04-14 21:21 UTC, merged