Update extension tutorial to use Manifest V3
MicrosoftDocs/edge-developer pull request #2014
Opened 2022-06-15 23:23 UTC by eclipse439

As requested by multiple users, this PR updates docs to change manifest version to v3, as well as replace any deprecated functions.

I've also added a PR to update the source code linked in the docs here: https://github.com/MicrosoftEdge/MicrosoftEdge-Extensions-Demos/pull/34

Issues requesting update: #2012 #1878

2022-06-15 23:23 UTC, opbld33 commented
Docs Build status updates of commit _[ad716f6](https://github.com/eclipse439/edge-developer/commits/ad716f6e224da6e9041c6ca404a0fa3d25b7f9e7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/extensions-chromium/getting-started/part1-simple-extension.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/getting-started/part1-simple-extension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/part1-simple-extension?branch=pr-en-us-2014) |
[microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/part2-content-scripts?branch=pr-en-us-2014) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/db9f4228-bcf7-7df9-527f-b7c9a032ef40/202206152323082360-2014/BuildReport?accessString=507967b0425b5de1fda212c394532a664284fdcc8807571f13d2bd0588c3727f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-16 08:40 UTC, captainbrosset commented
Thank you so much for the PR @eclipse439! We'll give this a review soon.

2022-06-16 12:33 UTC, ashishnirvana1 approved these changes
Iam fine by these changes, but am not fully sure if these cover everything. Will be nice to get a pass from Utkarsh Patankar as well.

2022-06-16 13:15 UTC, captainbrosset commented
> Iam fine by these changes, but am not fully sure if these cover everything. Will be nice to get a pass from Utkarsh Patankar as well.

Sounds great to me. Are you able to at-mention them here? I don't know what their username is on GitHub.

2022-06-16 15:44 UTC, Reezaali requested changes
Still in review by @ashishnirvana1 to confirm that the tutorial is complete. We also need to implement tabs for MV2 and MV3. 

@mikehoffms  - can you update the doc with the tabs please?

2022-06-16 17:37 UTC, mikehoffms commented
@Reezaali 
I implemented tabs to preserve Manifest V2 code listings.  The Files Changed tab served well, the sequence we used:

1. First, eclipse439 had a chance to view the individual changed lines in the **Files Changed** tab.

2. Then, after I added tabs, the **Files Changed** tab no longer shows individual changed lines, but rather, confirms my correct restoration of V2 code listings: it shows that this PR adds a tab demarcator above the V2 listings (no other changes to V2 listings), and adds whole complete new V3 listings (not depicted as individual line changes).

2022-06-16 17:55 UTC, Reezaali commented
For now, I will leave my review as blocking the merge until we hear back from @ashishnirvana1 to confirm that no additional changes are needed to the tutorial. Thanks!

2022-06-16 18:42 UTC, opbld31 commented
Docs Build status updates of commit _[b7fe1e3](https://github.com/eclipse439/edge-developer/commits/b7fe1e3a8791b3a1efa11a35090eab9aa8130e01)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/extensions-chromium/getting-started/part1-simple-extension.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/getting-started/part1-simple-extension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/part1-simple-extension?branch=pr-en-us-2014) |
[microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/part2-content-scripts?branch=pr-en-us-2014) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/db9f4228-bcf7-7df9-527f-b7c9a032ef40/202206161841242036-2014/BuildReport?accessString=75fa93b92bc9e5fd88433aa811950e7bd8fc6a6aaf0f87d8df6091c0cf8059e9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-16 18:42 UTC, mikehoffms commented on microsoft-edge/extensions-chromium/getting-started/part1-simple-extension.md
> +To test out the completed extension that you are building in this tutorial, download the source code from the [MicrosoftEdge-Extensions-Demos repo > extension-getting-started-part1](https://github.co
@Reezaali - note that the Demos repo has a PR to replace V2 code in .json file by V3.

2022-06-16 18:43 UTC, mikehoffms commented on microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md
> +To see the completed extension package source for this part of the tutorial, go to [MicrosoftEdge-Extensions-Demos repo > extension-getting-started-part2](https://github.com/MicrosoftEdge/MicrosoftEd
re: part 2:
@Reezaali - note that the Demos repo has a PR to replace V2 code in .json file by V3.

2022-06-24 11:00 UTC, sonakshimore commented
Utkarsh has suggested the below changes to the documentation:

1. Change suggested to [Create an extension tutorial, part 1](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/part1-simple-extension?branch=pr-en-us-2014&tabs=v2#step-3-open-a-default-pop-up-dialog) documentation, Step #3 last sentence:

**Old version**: Finally, ensure you register the pop-up in `manifest.json` under `browser_action`, as shown in the following code snippet.
**New version**: Finally, ensure you register the pop-up in `manifest.json` under `browser_action` or `action` in Manifest V2 or Manifest V3, respectively, as shown in the following code snippet.

2. Extension demos on [Before you begin](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/part1-simple-extension?branch=pr-en-us-2014&tabs=v3#before-you-begin) section of documentation:

Since it mentions that the source code has been updated from Manifest V2 to Manifest V3, we should actually update the source code first before we update this documentation.

Could you please review & approve [GitHub PR #34 - Update Edge Extension Tutorials to use Manifest V3 by eclipse439 · MicrosoftEdge/MicrosoftEdge-Extensions-Demos](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftEdge%2FMicrosoftEdge-Extensions-Demos%2Fpull%2F34%2Ffiles&data=05%7C01%7Cv-sonmore%40microsoft.com%7C12c53a58225446cb62fd08da55207eba%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637915895305363912%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lVGQLtt8jHzwfKRpPehW%2FM0pVHZysHAf5wmYbTauaNk%3D&reserved=0)?

2022-06-24 16:04 UTC, Reezaali commented
@mikehoffms - I merged PR34 above as mentioned by @sonakshimore. Thanks.

2022-06-25 02:13 UTC, opbld31 commented
Docs Build status updates of commit _[ed86ec3](https://github.com/eclipse439/edge-developer/commits/ed86ec399c16deba4c81e9d3d1e5c7c0cc5cafa6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/extensions-chromium/getting-started/part1-simple-extension.md](https://github.com/eclipse439/edge-developer/blob/main/microsoft-edge/extensions-chromium/getting-started/part1-simple-extension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/part1-simple-extension?branch=pr-en-us-2014) |
[microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md](https://github.com/eclipse439/edge-developer/blob/main/microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/part2-content-scripts?branch=pr-en-us-2014) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/db9f4228-bcf7-7df9-527f-b7c9a032ef40/202206250212243996-2014/BuildReport?accessString=9cd85f33b9a984b735e41858c057f9eb049039836773bd3b81c6584c6e0da82b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-25 02:23 UTC, opbld32 commented
Docs Build status updates of commit _[dd549aa](https://github.com/eclipse439/edge-developer/commits/dd549aae1a6b5b27d757f5ee79265f7ffd748060)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/extensions-chromium/getting-started/part1-simple-extension.md](https://github.com/eclipse439/edge-developer/blob/main/microsoft-edge/extensions-chromium/getting-started/part1-simple-extension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/part1-simple-extension?branch=pr-en-us-2014) |
[microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md](https://github.com/eclipse439/edge-developer/blob/main/microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/part2-content-scripts?branch=pr-en-us-2014) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/db9f4228-bcf7-7df9-527f-b7c9a032ef40/202206250221583510-2014/BuildReport?accessString=1649c51cfc9be311cce195b4e986f7a1c45a70f222b1aa827ee2915cf5eb2b92).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-25 02:25 UTC, merged

2022-06-25 02:47 UTC, mikehoffms commented on microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md
>  You're probably wondering why, when you pass the `images/stars.jpeg` must you use the `chrome.extension.getURL` chrome Extension API instead of just passing in the relative URL without the extra pref
This V2-specific word|sentence|paragraph needs techreview in future PR.  chrome.extension.getURL is V2-specific.  @ashishnirvana1 @eclipse439