WebView2 Process Model CoreWebView2Environment sharing clarifications
MicrosoftDocs/edge-developer pull request #2093
Opened 2022-08-02 22:11 UTC by david-risney

Got [a question on stackoverflow ](https://stackoverflow.com/questions/73159981/should-i-reuse-the-webview2-environment-for-multiple-webview-instances/73171374) that isn't quite answered by our process model docs around sharing CoreWebView2Environment objects. Updating the process model doc with that clarification.

2022-08-02 22:12 UTC, opbld31 commented
Docs Build status updates of commit _[03dc426](https://github.com/MicrosoftDocs/edge-developer/commits/03dc426fdcb62c9a14967861b6e6125e7cde7416)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/concepts/process-model.md](https://github.com/MicrosoftDocs/edge-developer/blob/process-model-corewebview2environment-sharing-clarification/microsoft-edge/webview2/concepts/process-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/process-model?branch=pr-en-us-2093) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/db9f4228-bcf7-7df9-527f-b7c9a032ef40/202208022211203960-2093/BuildReport?accessString=8416fd4787de5fb1a94f9c28f6f7a30e6378569d32955ea9a485d85e193be291).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-04 18:11 UTC, mikehoffms commented on microsoft-edge/webview2/concepts/process-model.md
> +If you try to create a `CoreWebView2Environment` using a user data folder which another `CoreWebView2Environment` is already using, and you don't configure the two `CoreWebView2Environment` objects t
@JasonAndrewWriter  - fyi.   also Acrolinx would suggest breaking up this long sentence.  If I tried that, I'd use VS Code as a scratchpad in this local .md file, then paste that rewrite into a Suggestion in this PR UI.
```suggestion
If you try to create a `CoreWebView2Environment` using a user data folder which another `CoreWebView2Environment` is already using, and you don't configure the two `CoreWebView2Environment` objects the same, for example if they were created with different `CoreWebView2EnvironmentOptions.Language` values, then the second `CoreWebView2Environment` will fail to create `WebView2` instances. This is true for `CoreWebView2Environment` objects that are in the same process or in different processes.
```

2022-08-04 18:13 UTC, mikehoffms commented on microsoft-edge/webview2/concepts/process-model.md
> +On the other hand, if you create multiple `CoreWebView2Environment` objects configured the same way including sharing the same user data folder, they will all represent the same user data folder and
@JasonAndrewWriter fyi
```suggestion
On the other hand, if you create multiple `CoreWebView2Environment` objects that are configured the same way, including sharing the same user data folder, each `CoreWebView2Environment` object will represent the same user data folder and the same associated collection of processes. Use any of those `CoreWebView2Environment` objects to create a `WebView2` with the one shared user data folder and associated collection of processes.
```

2022-08-04 18:22 UTC, mikehoffms requested changes
@david-risney - pls evaluate my Suggestions wording eg "objects"/"instances"

2022-08-04 18:34 UTC, opbld32 commented
Docs Build status updates of commit _[2e0a42b](https://github.com/MicrosoftDocs/edge-developer/commits/2e0a42b49a8954f7212bf41bc1dc5f95beece101)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/concepts/process-model.md](https://github.com/MicrosoftDocs/edge-developer/blob/process-model-corewebview2environment-sharing-clarification/microsoft-edge/webview2/concepts/process-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/process-model?branch=pr-en-us-2093) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/db9f4228-bcf7-7df9-527f-b7c9a032ef40/202208041833113918-2093/BuildReport?accessString=ef0c0207b5005532dc6828b8d5edc1ec4e16e5b67c7abfc43e2ee31370d29656).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-04 18:35 UTC, opbld33 commented
Docs Build status updates of commit _[10199eb](https://github.com/MicrosoftDocs/edge-developer/commits/10199eb3f0eda1a69c47916985161048aa5e4071)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/concepts/process-model.md](https://github.com/MicrosoftDocs/edge-developer/blob/process-model-corewebview2environment-sharing-clarification/microsoft-edge/webview2/concepts/process-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/process-model?branch=pr-en-us-2093) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/db9f4228-bcf7-7df9-527f-b7c9a032ef40/202208041833263694-2093/BuildReport?accessString=4341b0a83d3947be0e1d4609f99d39855cc7ab1cee78709128b896444d30ee3c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-04 19:49 UTC, JasonAndrewWriter approved these changes

2022-08-04 20:47 UTC, JasonAndrewWriter requested changes
If you create multiple `CoreWebView2Environment` objects that are configured the same way, (including sharing the same user data folder), they will represent the same user data folder and the same associated collection of processes. Use any of these `CoreWebView2Environment` objects to create a `WebView2` with the one shared user data folder and associated collection of processes.

2022-08-04 20:55 UTC, david-risney commented on microsoft-edge/webview2/concepts/process-model.md
> +On the other hand, if you create multiple `CoreWebView2Environment` objects that are configured the same way, including sharing the same user data folder, each of these `CoreWebView2Environment` obje
```suggestion
If you create multiple `CoreWebView2Environment` objects that are configured the same way, (including sharing the same user data folder), they will represent the same user data folder and the same associated collection of processes. Use any of these `CoreWebView2Environment` objects to create a `CoreWebView2` with the one shared user data folder and associated collection of processes.
```

2022-08-04 20:55 UTC, david-risney commented
> If you create multiple `CoreWebView2Environment` objects that are configured the same way, (including sharing the same user data folder), they will represent the same user data folder and the same associated collection of processes. Use any of these `CoreWebView2Environment` objects to create a `WebView2` with the one shared user data folder and associated collection of processes.

I've applied these changes. Thanks!

2022-08-04 20:55 UTC, opbld30 commented
Docs Build status updates of commit _[faec692](https://github.com/MicrosoftDocs/edge-developer/commits/faec6922514d5ae75de26f38549d331c88a51e1a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/concepts/process-model.md](https://github.com/MicrosoftDocs/edge-developer/blob/process-model-corewebview2environment-sharing-clarification/microsoft-edge/webview2/concepts/process-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/process-model?branch=pr-en-us-2093) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/db9f4228-bcf7-7df9-527f-b7c9a032ef40/202208042055076083-2093/BuildReport?accessString=644bd07fd81bd0c031628ee7079b49ff291bfedb944c127437076c916e3c9680).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-04 21:05 UTC, mikehoffms commented on microsoft-edge/webview2/concepts/process-model.md
> +If you create multiple `CoreWebView2Environment` objects that are configured the same way, (including sharing the same user data folder), they will represent the same user data folder and the same as
```suggestion
If you create multiple `CoreWebView2Environment` objects that are configured the same way (including sharing the same user data folder), they will represent the same user data folder and the same associated collection of processes. Use any of these `CoreWebView2Environment` objects to create a `CoreWebView2` with the one shared user data folder and associated collection of processes.
```

2022-08-04 21:06 UTC, opbld33 commented
Docs Build status updates of commit _[04b3b71](https://github.com/MicrosoftDocs/edge-developer/commits/04b3b7162f5b7195cc0ffb4cbefa0553e0a03405)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/concepts/process-model.md](https://github.com/MicrosoftDocs/edge-developer/blob/process-model-corewebview2environment-sharing-clarification/microsoft-edge/webview2/concepts/process-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/process-model?branch=pr-en-us-2093) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/db9f4228-bcf7-7df9-527f-b7c9a032ef40/202208042105460801-2093/BuildReport?accessString=eaf7c0e3caaf84bb12b5b149df571c2d48626f89cd33a10734b5727741ea51d4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-04 21:06 UTC, mikehoffms approved these changes

2022-08-04 21:24 UTC, JasonAndrewWriter approved these changes

2022-08-04 21:32 UTC, mikehoffms commented on microsoft-edge/webview2/concepts/process-model.md
```suggestion

### Multiple environment objects

```

2022-08-04 21:37 UTC, mikehoffms commented on microsoft-edge/webview2/concepts/process-model.md
Can we use h3 headings to label/group some of these 5 paragraphs?

2022-08-04 21:45 UTC, jasonstephen15 approved these changes

2022-08-04 21:53 UTC, opbld32 commented
Docs Build status updates of commit _[07450f2](https://github.com/MicrosoftDocs/edge-developer/commits/07450f2b35fc39ebd5b197ff8490a9fe2ad1e52c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/concepts/process-model.md](https://github.com/MicrosoftDocs/edge-developer/blob/process-model-corewebview2environment-sharing-clarification/microsoft-edge/webview2/concepts/process-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/process-model?branch=pr-en-us-2093) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/db9f4228-bcf7-7df9-527f-b7c9a032ef40/202208042152169036-2093/BuildReport?accessString=99063b166885690f22f9559b615f6a662d1dd4ddc3a77adb03f2346773ecee70).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-04 21:57 UTC, merged