changed date
MicrosoftDocs/edge-developer pull request #2207
Opened 2022-09-26 22:22 UTC by JasonAndrewWriter

I messed up old pull request so made another one.

2022-09-26 22:24 UTC, opbld33 commented
Docs Build status updates of commit _[913b255](https://github.com/MicrosoftDocs/edge-developer/commits/913b2554afd8ed73a96022b4a02d088b4a09b504)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/devtools-guide-chromium/sources/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/sources/index.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/db9f4228-bcf7-7df9-527f-b7c9a032ef40/202209262222493554-2207/BuildReport?accessString=7402017df2545a2d36dbb197f776287255b52d8e4eca9eb1ff3674cfec10fa3b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-26 22:25 UTC, opbld32 commented
Docs Build status updates of commit _[a77d174](https://github.com/MicrosoftDocs/edge-developer/commits/a77d174f698a0798ba6c37859dd560c7bdd19277)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/devtools-guide-chromium/media/content-scripts-tab.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/content-scripts-tab.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/editor-pane.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/editor-pane.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/navigator-pane.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/navigator-pane.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/overrides-tab.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/overrides-tab.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/snippet.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/snippet.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/sources-command-menu-to-open-file.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/sources-command-menu-to-open-file.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/sources-filesystem-tab.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/sources-filesystem-tab.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/sources-page-tab.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/sources-page-tab.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/sources-panes-narrow-layout.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/sources-panes-narrow-layout.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/sources-panes-wide-layout.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/sources-panes-wide-layout.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/sources/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/sources/index.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/db9f4228-bcf7-7df9-527f-b7c9a032ef40/202209262224201232-2207/BuildReport?accessString=5fca17ab164c8b103804a4b5600ac2290ba2340f8c8104a96e0a98023716bfb6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-27 09:47 UTC, captainbrosset requested changes
Thanks Jason.

My main comment on this PR is that you've got the QuickView panel opened at the bottom of DevTools, and that's unnecessarily making the screenshots harder to understand. QuickView shows the Console in your screenshots, but since this article is about the Sources tool, we don't need to be showing the Console. We want the user attention to be focused on the Sources tool and its major parts.

I have a couple of other comments too:

1. Using Snipping Tool on Windows, it's possible to take really nice full window screenshots with the window borders. This makes the screenshots a lot easier to see in an article thanks to the thin border around them. Most of your screenshots have probably been taken when the app window was maximized, and so the screenshots have no window borders around them. I suggest un-maximizing the window first, and then using the Snipping Tool's window mode to capture it. Oh and, if you make your desktop background white when doing this, you'll ensure no distracting pixels end up in the capture next to the borders.
1. Please resize the screenshots to around 1200 or 1300px wide at most.
1. `microsoft-edge/devtools-guide-chromium/media/sources-command-menu-to-open-file.msft.png` needs a red box around the command menu area.
1. The original image `microsoft-edge/devtools-guide-chromium/media/sources-page-tab.msft.png` shows that the debugger is paused on line 33. Your new image isn't paused. Maybe consider running the code to hit that breakpoint. Same for `microsoft-edge/devtools-guide-chromium/media/sources-panes-wide-layout.msft.png`.
1. In `microsoft-edge/devtools-guide-chromium/media/sources-panes-narrow-layout.msft.png` you did not draw the 3rd red box around the right thing. You should hide QuickView and instead open the debugger pane (by clicking the expand/collapse icon in the top-right of your screenshot).

2022-09-27 18:31 UTC, opbld30 commented
Docs Build status updates of commit _[99140ef](https://github.com/MicrosoftDocs/edge-developer/commits/99140ef522c8e6bd34dda8fd4640a1321eee6f39)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/devtools-guide-chromium/media/content-scripts-tab.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/content-scripts-tab.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/editor-pane.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/editor-pane.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/memory-problems-bing-browser-task-manager-javascript-memory.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/memory-problems-bing-browser-task-manager-javascript-memory.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/memory-problems/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/navigator-pane.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/navigator-pane.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/overrides-tab.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/overrides-tab.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/snippet.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/snippet.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/sources-command-menu-to-open-file.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/sources-command-menu-to-open-file.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/sources-filesystem-tab.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/sources-filesystem-tab.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/sources-page-tab.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/sources-page-tab.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/sources-panes-narrow-layout.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/sources-panes-narrow-layout.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/sources-panes-wide-layout.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/sources-panes-wide-layout.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/memory-problems/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/memory-problems/index.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/memory-problems/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/sources/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/sources/index.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/db9f4228-bcf7-7df9-527f-b7c9a032ef40/202209271830123553-2207/BuildReport?accessString=e00c03b0e51b02ee41eabe4261e5628e1186074c46e7640d04777c654c4c35c7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-27 19:13 UTC, opbld31 commented
Docs Build status updates of commit _[d13e91a](https://github.com/MicrosoftDocs/edge-developer/commits/d13e91aa82f0691b583c1b8fa61903260efb2c0f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/devtools-guide-chromium/media/content-scripts-tab.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/content-scripts-tab.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/editor-pane.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/editor-pane.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/memory-problems-bing-browser-task-manager-javascript-memory.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/memory-problems-bing-browser-task-manager-javascript-memory.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/memory-problems/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/navigator-pane.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/navigator-pane.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/overrides-tab.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/overrides-tab.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/snippet.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/snippet.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/sources-command-menu-to-open-file.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/sources-command-menu-to-open-file.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/sources-filesystem-tab.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/sources-filesystem-tab.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/sources-page-tab.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/sources-page-tab.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/sources-panes-narrow-layout.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/sources-panes-narrow-layout.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/sources-panes-wide-layout.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/sources-panes-wide-layout.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/memory-problems/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/memory-problems/index.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/memory-problems/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/sources/index.md](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/sources/index.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/db9f4228-bcf7-7df9-527f-b7c9a032ef40/202209271912237641-2207/BuildReport?accessString=2c6e186d5399cdb63e50deffceb3a03ca96ea4cc3c8341349df1ac286cc6bbf3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-28 17:05 UTC, JasonAndrewWriter commented
I think the Dev-Tools (https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/landing/) is a little confusing.  I am going to try to clean it up a bit it word to hit the feedback given today, redo, and meeting with @captainbrosset  tomorrow super early to get this streamlined.

2022-10-04 13:03 UTC, opbld31 commented
Learn Build status updates of commit _[7b95c8e](https://github.com/MicrosoftDocs/edge-developer/commits/7b95c8e342546610c94d59de869cd55af6cebe28)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/devtools-guide-chromium/media/content-scripts-tab.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/content-scripts-tab.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/edit-css.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/edit-css.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/editing-js-in-editor-pane.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/editing-js-in-editor-pane.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/edit-js.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/edit-js.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/editor-pane.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/editor-pane.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/find-replace.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/find-replace.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/local-modifications.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/local-modifications.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/minified.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/minified.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/navigator-pane.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/navigator-pane.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/overrides-tab.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/overrides-tab.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/pretty-printed.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/pretty-printed.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/snippet.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/snippet.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/sources-command-menu-to-open-file.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/sources-command-menu-to-open-file.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/sources-filesystem-tab.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/sources-filesystem-tab.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/sources-html-editor.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/sources-html-editor.msft.png) | :white_check_mark:Succeeded |n/a (file deleted or renamed) |
[microsoft-edge/devtools-guide-chromium/media/sources-page-tab.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/sources-page-tab.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/sources-panes-narrow-layout.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/sources-panes-narrow-layout.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/sources-panes-wide-layout.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/sources-panes-wide-layout.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/sources-paused-breakpoint-highlight-debug-pane.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-jandrew/new-final-sources-focus-mode/microsoft-edge/devtools-guide-chromium/media/sources-paused-breakpoint-highlight-debug-pane.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/sources/index?branch=pr-en-us-2207) |
[microsoft-edge/devtools-guide-chromium/media/sources-paused-breakpoint-highlights.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user-v-j [...]

2022-10-04 13:03 UTC, captainbrosset commented
Posted some changes: merged from the target branch, added some missing images, fixed some others, and changed some of the instructions.

2022-10-04 13:03 UTC, captainbrosset approved these changes

2022-10-04 13:04 UTC, merged