Update publish-uwp-app-store.md
MicrosoftDocs/edge-developer pull request #2233
Opened 2022-10-06 01:18 UTC by DavidShoe

Update docs on platform support requirements noting we do not support arm32 bit.  But do support 32 / 64 for non arm.

2022-10-06 01:19 UTC, opbld31 commented
Learn Build status updates of commit _[22fb801](https://github.com/MicrosoftDocs/edge-developer/commits/22fb8019f157ed5a014f8d9c61758159437282c0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/how-to/publish-uwp-app-store.md](https://github.com/MicrosoftDocs/edge-developer/blob/DavidShoe-32bit-note/microsoft-edge/webview2/how-to/publish-uwp-app-store.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/publish-uwp-app-store?branch=pr-en-us-2233) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/db9f4228-bcf7-7df9-527f-b7c9a032ef40/202210060118079081-2233/BuildReport?accessString=537513ab6514445e380fff45228968a70a9a3e067e7d5dadbea1c708580df870).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-07 17:13 UTC, JasonAndrewWriter approved these changes

2022-10-10 17:18 UTC, mikehoffms commented on microsoft-edge/webview2/how-to/publish-uwp-app-store.md
> +1. Create the app package, by selecting **Project** > **Publish** > **Create App Packages**.  Select the target configurations.  Note: 32-bit is not supported for Arm due to dependencies on Edge whic
global: ARM allcaps.  
Microsoft Edge (add Microsoft)

2022-10-10 17:18 UTC, mikehoffms commented on microsoft-edge/webview2/how-to/publish-uwp-app-store.md
> +1. Create the app package, by selecting **Project** > **Publish** > **Create App Packages**.  Select the target configurations.  Note: 32-bit is not supported for Arm due to dependencies on Edge whic
```suggestion
1. Create the app package, by selecting **Project** > **Publish** > **Create App Packages**.  Select the target configurations.  Note: 32-bit is not supported for ARM, due to dependencies on Microsoft Edge, which does not support ARM32. 32/64-bit versions of the WebView2 Runtime will work in UWP on non ARM platforms:
```

2022-10-10 17:22 UTC, mikehoffms commented on microsoft-edge/webview2/how-to/publish-uwp-app-store.md
> +1. Create the app package, by selecting **Project** > **Publish** > **Create App Packages**.  Select the target configurations.  Note: 32-bit is not supported for Arm due to dependencies on Edge whic
Are the non-supported configurations listed here in this UI, or not?

2022-10-10 18:35 UTC, mikehoffms commented on microsoft-edge/webview2/how-to/publish-uwp-app-store.md
>     ![Package Selection](publish-uwp-app-store-images/package-selection.png)
```suggestion
1. Create the app package, by selecting **Project** > **Publish** > **Create App Packages**.  Select the target configurations:

   ![Package Selection](publish-uwp-app-store-images/package-selection.png)

   32-bit and 64-bit versions of the WebView2 Runtime will work in UWP on non-ARM platforms.  32-bit is not supported for ARM, due to dependencies on Microsoft Edge, which doesn't support ARM32.
```

2022-10-11 14:45 UTC, JasonAndrewWriter requested changes

2022-10-11 14:45 UTC, JasonAndrewWriter commented on microsoft-edge/webview2/how-to/publish-uwp-app-store.md
> +   32-bit and 64-bit versions of the WebView2 Runtime will work in UWP on non-ARM platforms.  32-bit is not supported for ARM, due to dependencies on Microsoft Edge, which doesn't support ARM32.
32-bit and 64-bit versions of the WebView2 Runtime will work in UWP on non-ARM platforms.  32-bit is not supported for ARM, due to dependencies on Microsoft Edge.

2022-10-12 18:14 UTC, JasonAndrewWriter approved these changes
Made the last changes

2022-10-12 18:15 UTC, opbld33 commented
Learn Build status updates of commit _[bce541d](https://github.com/MicrosoftDocs/edge-developer/commits/bce541de6cbf4273ee8d4af499910914f863ad8d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/how-to/publish-uwp-app-store.md](https://github.com/MicrosoftDocs/edge-developer/blob/DavidShoe-32bit-note/microsoft-edge/webview2/how-to/publish-uwp-app-store.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/publish-uwp-app-store?branch=pr-en-us-2233) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/db9f4228-bcf7-7df9-527f-b7c9a032ef40/202210121814179346-2233/BuildReport?accessString=3d9f8c7704884d07abf6e0b18391cc11a71946974de7ada38bc0754d9409e81b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-13 19:12 UTC, JasonAndrewWriter approved these changes

2022-10-13 19:15 UTC, JasonAndrewWriter approved these changes

2022-10-13 20:18 UTC, opbld32 commented
Learn Build status updates of commit _[21cf17b](https://github.com/MicrosoftDocs/edge-developer/commits/21cf17bcda662cfe7462ad775c9c0049741f6a16)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/how-to/publish-uwp-app-store.md](https://github.com/MicrosoftDocs/edge-developer/blob/DavidShoe-32bit-note/microsoft-edge/webview2/how-to/publish-uwp-app-store.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/publish-uwp-app-store?branch=pr-en-us-2233) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/db9f4228-bcf7-7df9-527f-b7c9a032ef40/202210132017518400-2233/BuildReport?accessString=551a5fb303d721dc08d1407f17b00a298c2c51b605169497a58c76479adb606b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-13 20:19 UTC, merged