future tense
MicrosoftDocs/edge-developer pull request #2243
Opened 2022-10-10 22:31 UTC by mikehoffms

2022-10-10 22:33 UTC, opbld30 commented
Learn Build status updates of commit _[df6d5c4](https://github.com/mikehoffms/edge-developer/commits/df6d5c42b0a6434252a2628c990df60cec696698)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/extensions-chromium/developer-guide/manifest-v3.md](https://github.com/mikehoffms/edge-developer/blob/user/mikehoffms/v2-sunset/microsoft-edge/extensions-chromium/developer-guide/manifest-v3.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/manifest-v3?branch=pr-en-us-2243) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/db9f4228-bcf7-7df9-527f-b7c9a032ef40/202210102231377439-2243/BuildReport?accessString=2c5a42da274c566e0fb76f607e402cd299b4c36af6e4d88c53c4b996e2bc5b5f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-19 05:58 UTC, jeremytuck5 requested changes
commit

2022-10-19 05:58 UTC, jeremytuck5 commented on microsoft-edge/extensions-chromium/developer-guide/manifest-v3.md
> +This timeline is subject to change. This article will be updated as the milestones draw nearer.  Chrome has revised the timeline for Manifest V2 sunset, and we are about to update this article to ref
commit

2022-10-19 05:58 UTC, jeremytuck5 commented on microsoft-edge/extensions-chromium/developer-guide/manifest-v3.md
> +| January 2023 | Microsoft Partner Center will no longer accept updates to existing Manifest V2 extensions. Developers can submit updates for migrating a Manifest V2 extension to Manifest V3. | Micro
commit

2022-10-27 17:15 UTC, mikehoffms commented
This PR is superseded by https://github.com/MicrosoftDocs/edge-developer/pull/2258/

2022-10-27 17:15 UTC, closed without merging