users/v-jandrew/new-focus-mode images of reference
MicrosoftDocs/edge-developer pull request #2246
Opened 2022-10-11 17:20 UTC by JasonAndrewWriter

I redid the pr because I have the images saved on my laptop and it was easier to fix than fixing the merge.

2022-10-11 17:21 UTC, opbld31 commented
Learn Build status updates of commit _[c7c44fb](https://github.com/MicrosoftDocs/edge-developer/commits/c7c44fb3f85549293fcf1b3b0e3981ae7a5307f2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/devtools-guide-chromium/javascript/reference.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/javascript/reference.md) | :warning:Warning | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) | [Details](#user-content-d9e93f323e1ad162b76d0d918cf9ac07-8dfd2cca)
[microsoft-edge/devtools-guide-chromium/media/javascript-glitch-debug-js-sources-get-started-inputs-are-empty.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-glitch-debug-js-sources-get-started-inputs-are-empty.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-glitch-debug-js-sources-get-started-inputs-are-empty-copy-stack-trace.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-glitch-debug-js-sources-get-started-inputs-are-empty-copy-stack-trace.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-source-page-continue-to-here.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-source-page-continue-to-here.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-source-page-debugger-restart-frame.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-source-page-debugger-restart-frame.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-source-page-debugger-step-into-next-function-call.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-source-page-debugger-step-into-next-function-call.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-source-page-debugger-step-out-of-current-function.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-source-page-debugger-step-out-of-current-function.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-source-page-debugger-step-over-next-function-call.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-source-page-debugger-step-over-next-function-call.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-sources-get-started-js-force-script-runtime.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-sources-get-started-js-force-script-runtime.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-sources-get-started-js-resume-script-runtime.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-sources-get-started-js-resume-script-runtime.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-sources-get-started-js-scope.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-sources-get-started-js-scope.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-sources-get-started-js-watch.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-sources-get-started-js-watch.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-sources-html-minified.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-sources-html-minified.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-sources-html-non-minified.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-sources-html-non-minified.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-sources-main-min-js-threads.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-sources-main-min-js-threads.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-sources-page-js-breakpoint- reference-30.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-sources-page-js-breakpoint-%20reference-30.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/media/javascript-sources-page-js-breakpoint-%20reference-30.msft.png?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-sources-page-js-b [...]

2022-10-11 17:32 UTC, opbld30 commented
Learn Build status updates of commit _[c761ff8](https://github.com/MicrosoftDocs/edge-developer/commits/c761ff8c2af647e4268a235d1a9ec8a68926c3f7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/devtools-guide-chromium/javascript/reference.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/javascript/reference.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-glitch-debug-js-sources-get-started-inputs-are-empty.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-glitch-debug-js-sources-get-started-inputs-are-empty.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-glitch-debug-js-sources-get-started-inputs-are-empty-copy-stack-trace.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-glitch-debug-js-sources-get-started-inputs-are-empty-copy-stack-trace.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-source-page-continue-to-here.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-source-page-continue-to-here.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-source-page-debugger-restart-frame.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-source-page-debugger-restart-frame.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-source-page-debugger-step-into-next-function-call.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-source-page-debugger-step-into-next-function-call.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-source-page-debugger-step-out-of-current-function.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-source-page-debugger-step-out-of-current-function.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-source-page-debugger-step-over-next-function-call.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-source-page-debugger-step-over-next-function-call.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-sources-get-started-js-force-script-runtime.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-sources-get-started-js-force-script-runtime.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-sources-get-started-js-resume-script-runtime.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-sources-get-started-js-resume-script-runtime.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-sources-get-started-js-scope.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-sources-get-started-js-scope.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-sources-get-started-js-watch.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-sources-get-started-js-watch.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-sources-html-minified.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-sources-html-minified.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-sources-html-non-minified.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-sources-html-non-minified.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-sources-main-min-js-threads.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-sources-main-min-js-threads.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-sources-page-js-breakpoint-30.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-sources-page-js-breakpoint-30.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/breakpoints?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-sources-page-js-breakpoint-reference-30.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-ref [...]

2022-10-17 17:29 UTC, mikehoffms commented on microsoft-edge/devtools-guide-chromium/javascript/reference.md
> +1. In the **Navigator** pane, select your file, to open it in the **Ed0itor** pane.
```suggestion
1. In the **Navigator** pane, select your file, to open it in the **Editor** pane.
```

2022-10-17 17:32 UTC, opbld32 commented
Learn Build status updates of commit _[c43847d](https://github.com/MicrosoftDocs/edge-developer/commits/c43847d6fc1f127f71eb11020a339dafecd4ffd5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/devtools-guide-chromium/javascript/reference.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/javascript/reference.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-glitch-debug-js-sources-get-started-inputs-are-empty.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-glitch-debug-js-sources-get-started-inputs-are-empty.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-glitch-debug-js-sources-get-started-inputs-are-empty-copy-stack-trace.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-glitch-debug-js-sources-get-started-inputs-are-empty-copy-stack-trace.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-source-page-continue-to-here.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-source-page-continue-to-here.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-source-page-debugger-restart-frame.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-source-page-debugger-restart-frame.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-source-page-debugger-step-into-next-function-call.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-source-page-debugger-step-into-next-function-call.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-source-page-debugger-step-out-of-current-function.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-source-page-debugger-step-out-of-current-function.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-source-page-debugger-step-over-next-function-call.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-source-page-debugger-step-over-next-function-call.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-sources-get-started-js-force-script-runtime.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-sources-get-started-js-force-script-runtime.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-sources-get-started-js-resume-script-runtime.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-sources-get-started-js-resume-script-runtime.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-sources-get-started-js-scope.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-sources-get-started-js-scope.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-sources-get-started-js-watch.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-sources-get-started-js-watch.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-sources-html-minified.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-sources-html-minified.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-sources-html-non-minified.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-sources-html-non-minified.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-sources-main-min-js-threads.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-sources-main-min-js-threads.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/reference?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-sources-page-js-breakpoint-30.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-reference-images/microsoft-edge/devtools-guide-chromium/media/javascript-sources-page-js-breakpoint-30.msft.png) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/javascript/breakpoints?branch=pr-en-us-2246) |
[microsoft-edge/devtools-guide-chromium/media/javascript-sources-page-js-breakpoint-reference-30.msft.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/v-jandrew/new-focus-mode-ref [...]

2022-10-21 07:48 UTC, captainbrosset requested changes
Sorry about the delay. I took a look today, and I think we unfortunately need to redo these screenshots. There are a few things that need to be changed:

* The most important is that the **Quick View** section (at the bottom) is visible in all screenshots. Unless an article is specifically about **Quick View**, then we should hide it (by pressing `ESC`) before taking screenshots. It unnecessarily makes screenshots busier and harder to understand. But, also, **Quick View** is changing very soon, and the more we show it, the more screenshots we'll have to redo later, after it has changed.
* It feels strange to see different demo pages in every screenshot. It would be better to just stick to one demo page and use it throughout the article.
* Most screenshots show a few distracting pixels beyond the window borders. To achieve cleaner results, it's necessary to hide desktop icons and all other windows, and then choose a white background. This way, the Edge window sits on solid white, and it makes the final images much cleaner.
* The last 3 screenshots of the article have not been updated in this PR and still show non-focus mode UI and dark theme.

I would advise leaving this PR for the moment, and then picking it up again once **Quick View** has been changed. So I'd actually advise closing it for now, and we can then work on it again in a few time.

2022-10-21 15:14 UTC, closed without merging