Added missing APIs for .NET and WinRT
MicrosoftDocs/edge-developer pull request #2417
Opened 2023-01-23 19:00 UTC by nishitha-burman

Added missing APIs for .NET and WinRT

AB#43067509

2023-01-23 19:36 UTC, mikehoffms commented on microsoft-edge/webview2/release-notes.md
> +* [CoreWebView2Profile Class](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2profile?view=webview2-dotnet-1.0.1619-prerelease)
```suggestion
* [CoreWebView2Profile Class](/dotnet/api/microsoft.web.webview2.core.corewebview2profile?view=webview2-dotnet-1.0.1619-prerelease&preserve-view=true)
```

2023-01-23 19:38 UTC, mikehoffms commented on microsoft-edge/webview2/release-notes.md
> +   * [CoreWebView2Profile.setPermissionStateAsync Method](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2profile.setpermissionstateasync?view=webview2-dotnet-1.0
```suggestion
   * [CoreWebView2Profile.SetPermissionStateAsync Method](/dotnet/api/microsoft.web.webview2.core.corewebview2profile.setpermissionstateasync?view=webview2-dotnet-1.0.1619-prerelease&preserve-view=true)
```

2023-01-23 19:38 UTC, mikehoffms commented on microsoft-edge/webview2/release-notes.md
> +* [CoreWebView2Profile Class](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/winrt/microsoft_web_webview2_core/corewebview2profile?view=webview2-winrt-1.0.1619-prerelease)
```suggestion
* [CoreWebView2Profile Class](/microsoft-edge/webview2/reference/winrt/microsoft_web_webview2_core/corewebview2profile?view=webview2-winrt-1.0.1619-prerelease&preserve-view=true)
```

2023-01-23 19:39 UTC, mikehoffms commented on microsoft-edge/webview2/release-notes.md
> +   * [CoreWebView2Profile.GetNonDefaultPermissionSettingsAsync Method](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/winrt/microsoft_web_webview2_core/corewebview2profile?view=w
```suggestion
   * [CoreWebView2Profile.GetNonDefaultPermissionSettingsAsync Method](/microsoft-edge/webview2/reference/winrt/microsoft_web_webview2_core/corewebview2profile?view=webview2-winrt-1.0.1619-prerelease&preserve-view=true#getnondefaultpermissionsettingsasync)
```

2023-01-23 19:40 UTC, mikehoffms commented on microsoft-edge/webview2/release-notes.md
> +   * [CoreWebView2Profile.setPermissionStateAsync Method](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/winrt/microsoft_web_webview2_core/corewebview2profile?view=webview2-winrt
```suggestion
   * [CoreWebView2Profile.SetPermissionStateAsync Method](/microsoft-edge/webview2/reference/winrt/microsoft_web_webview2_core/corewebview2profile?view=webview2-winrt-1.0.1619-prerelease&preserve-view=true#setpermissionstateasync)
```

2023-01-23 19:41 UTC, mikehoffms requested changes
finished review pass.  finalized link urls, uppercased Set method name.

2023-01-24 22:53 UTC, mikehoffms approved these changes

2023-01-24 23:08 UTC, JasonAndrewWriter approved these changes

2023-01-25 00:15 UTC, merged