user/-j-andrew/test&automation-edit
MicrosoftDocs/edge-developer pull request #2431
Opened 2023-01-30 16:54 UTC by JasonAndrewWriter

2023-02-10 18:42 UTC, zoherghadyali requested changes

2023-02-10 18:42 UTC, zoherghadyali commented on microsoft-edge/test-and-automation/test-and-automation.md
> +| Webhint | Checks your code for best practices and common errors, to test and improve accessibility, performance, cross-browser and PWA compatibility, and security of your site. |
```suggestion
| webhint | Checks your code for best practices and common errors, to test and improve accessibility, performance, cross-browser and PWA compatibility, and security of your site. |
```
webhint is intentionally not capitalized. See https://webhint.io/

2023-02-10 18:42 UTC, zoherghadyali commented on microsoft-edge/origin-trials/index.md
> +See the [Microsft Edge Origin Trials Developer Console](https://developer.microsoft.com/en-us/microsoft-edge/origin-trials/) to see a list of the available origin trials and register your origin to g
```suggestion
See the [Microsoft Edge Origin Trials Developer Console](https://developer.microsoft.com/en-us/microsoft-edge/origin-trials/) to see a list of the available origin trials and register your origin to give them a try.  You can also provide feedback on the design of the API, your use cases, or your experience using the APIs to browser engineers and the web standard community.
```
This had a typo

2023-02-10 18:42 UTC, zoherghadyali commented on microsoft-edge/origin-trials/index.md
> +Web content's origin is defined by the scheme (protocol), hostname (domain), and port of the URL used to access it. Two objects have the same origin only when the scheme, hostname, and port all match
```suggestion
```
I don't think we need this content. We can cut this sentence.

2023-02-10 18:42 UTC, zoherghadyali commented on microsoft-edge/origin-trials/index.md
>  You can use Origin Trials to try out experimental APIs on live sites for a limited period of time.  When using Origin Trials, users of Microsoft Edge that visit your site may run code that uses exper
```suggestion
You can use Origin Trials to try out experimental APIs on live sites for a limited period of time.  When using Origin Trials, users of Microsoft Edge that visit your site may run code that uses experimental APIs.  To access the experimental APIs on each user machine, you don't need to go to `edge://flags` and turn on feature flags.

Instead, you register the origin (for example, `https://www.example.com:443`) that you want to use the experimental feature on and you'll be issued a token that you add to the code of your website.
```

2023-02-10 23:36 UTC, mikehoffms commented on microsoft-edge/origin-trials/index.md
> +See the [Microsoft Edge Origin Trials Developer Console](https://developer.microsoft.com/en-us/microsoft-edge/origin-trials/) to see a list of the available origin trials and register your origin to
```suggestion
To see a list of the available origin trials and register your origin to give them a try, see [Microsoft Edge Origin Trials Developer Console](https://developer.microsoft.com/microsoft-edge/origin-trials/).  You can also provide feedback to browser engineers and the web standard community about the design of the API, your use cases, or your experience using the APIs .
```
* Used pattern "To do X, see Y."
* Removed en-us/
* Pulled end of sentence 2 toward the start.  Up to you which sequence of phrases, here's an experiment.

https://developer.microsoft.com/microsoft-edge/origin-trials/

2023-02-10 23:39 UTC, mikehoffms commented on microsoft-edge/test-and-automation/devtools-protocol.md
> +Use the DevTools Protocol to instrument, inspect, debug, and profile browsers, including Microsoft Edge.  By [building Microsoft Edge on the Chromium open-source project](https://github.com/Microsoft
```suggestion
Use the DevTools Protocol to instrument, inspect, debug, and profile browsers, including Microsoft Edge.  By building Microsoft Edge on the Chromium open-source project, the Microsoft Edge DevTools Protocol matches the APIs of the Chrome DevTools Protocol.  For information about the Chromium open-source project, see [Microsoft Edge and Chromium Open Source: Our Intent](https://github.com/MicrosoftEdge/MSEdge/blob/master/README.md).
```
Standard link pattern to show the destination text as link text. Corp style says do that if possible.

2023-02-10 23:44 UTC, mikehoffms commented on microsoft-edge/test-and-automation/test-and-automation.md
> +Use the DevTools Protocol to instrument, inspect, debug, and profile browsers, including Microsoft Edge. By [building Microsoft Edge on the Chromium open-source project](https://github.com/MicrosoftE
```suggestion
Use the DevTools Protocol to instrument, inspect, debug, and profile browsers, including Microsoft Edge.  By building Microsoft Edge on the Chromium open-source project, the Microsoft Edge DevTools Protocol matches the APIs of the Chrome DevTools Protocol.  For information about the Chromium open-source project, see [Microsoft Edge and Chromium Open Source: Our Intent](https://github.com/MicrosoftEdge/MSEdge/blob/master/README.md).
```
instance 2 of the above comment

2023-02-10 23:47 UTC, mikehoffms commented on microsoft-edge/test-and-automation/test-and-automation.md
> +See the [Microsft Edge Origin Trials Developer Console](https://developer.microsoft.com/en-us/microsoft-edge/origin-trials/) to see a list of the available origin trials and register your origin to g
```suggestion
To see a list of the available origin trials and register your origin to give them a try, see the [Microsft Edge Origin Trials Developer Console](https://developer.microsoft.com/microsoft-edge/origin-trials/).  You can also provide feedback to browser engineers and the web standard community about the design of the API, your use cases, or your experience using the APIs.
```

2023-02-13 18:29 UTC, mikehoffms commented on microsoft-edge/origin-trials/index.md
> +Instead, you register the origin (for example, `https://www.example.com:443`) that you want to use the experimental feature on and you'll be issued a token that you add to the code of your website.
```suggestion
Instead, you register the origin (for example, `https://www.contoso.com:443`) that you want to use the experimental feature on and you'll be issued a token that you add to the code of your website.
```

2023-02-13 22:01 UTC, zoherghadyali approved these changes

2023-02-13 22:51 UTC, merged