update WPF and WinForms sample doc
MicrosoftDocs/edge-developer pull request #2554
Opened 2023-04-19 04:30 UTC by ElyssaJyu

give an instruction to switch runtime for testing upcoming API in WPF and WinForms sample.

2023-04-19 06:20 UTC, ElyssaJyu commented
@peiche-jessica @novac42 I cannot add reviewers, help to review, plz.

2023-04-19 17:33 UTC, mikehoffms commented on microsoft-edge/webview2/samples/webview2windowsformsbrowser.md
> +2. To test the experimental APIs ahead of time and ensure WebView2 app's forward-compatibility, see [Approaches to making your app use a specific browser channel](../how-to/set-preview-channel.md#app
```suggestion
1. To test the experimental APIs ahead of time and ensure your WebView2 app's forward-compatibility, see [Approaches to making your app use a specific browser channel](../how-to/set-preview-channel.md#approaches-to-making-your-app-use-a-specific-browser-channel) in _Test upcoming APIs and features_. Follow the steps in that section, and then return to this page and continue the steps below.
```

2023-04-19 17:33 UTC, mikehoffms commented on microsoft-edge/webview2/samples/webview2wpfbrowser.md
> +2. To test the experimental APIs ahead of time and ensure WebView2 app's forward-compatibility, see [Approaches to making your app use a specific browser channel](../how-to/set-preview-channel.md#app
```suggestion
1. To test the experimental APIs ahead of time and ensure your WebView2 app's forward-compatibility, see [Approaches to making your app use a specific browser channel](../how-to/set-preview-channel.md#approaches-to-making-your-app-use-a-specific-browser-channel) in _Test upcoming APIs and features_. Follow the steps in that section, and then return to this page and continue the steps below.
```

2023-04-19 17:34 UTC, mikehoffms requested changes
Writer/Editor pass

2023-04-19 22:22 UTC, peiche-jessica approved these changes

2023-04-20 03:23 UTC, novac42 approved these changes

2023-04-20 03:25 UTC, mikehoffms approved these changes

2023-04-24 17:35 UTC, merged