Update the add-ons appeal stats
MicrosoftDocs/edge-developer pull request #2690
Opened 2023-07-10 13:01 UTC by captainbrosset

This PR updates the appeal stats for Microsoft Edge Add-ons policy for FY2022.

* Before: https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/store-policies/developer-policies#microsoft-edge-add-ons-appeal-statistics-for-fy2021
* After:

2023-07-10 17:05 UTC, mikehoffms approved these changes

2023-07-10 17:09 UTC, mikehoffms requested changes
undo of test approval, which gave gray checkmark not green yet

2023-07-10 17:13 UTC, mikehoffms approved these changes

2023-07-11 05:14 UTC, AbhisekhMSFT commented
> This PR updates the appeal stats for Microsoft Edge Add-ons policy for FY2022.
> 
> * Before: https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/store-policies/developer-policies#microsoft-edge-add-ons-appeal-statistics-for-fy2021
> * After: https://review.learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/store-policies/developer-policies?branch=pr-en-us-2690#edge-add-ons-certification-complaint-and-appeal-process
> 
> AB#45465975

Approved

2023-07-11 05:15 UTC, AbhisekhMSFT approved these changes

2023-07-11 05:17 UTC, AbhisekhMSFT approved these changes

2023-07-11 05:19 UTC, AbhisekhMSFT reviewed
Approved

2023-07-11 07:55 UTC, merged