Adding link to MDA as requested by the Edge team
MicrosoftDocs/edge-developer pull request #2750
Opened 2023-08-02 08:34 UTC by batamig

2023-08-02 17:29 UTC, apryzgoda approved these changes
Edge Privacy Approved

2023-08-02 19:05 UTC, mikehoffms requested changes
Writer/Editor pass.  requested changing link text from "applications" to "apps" per consistent use of that in destination article.

2023-08-02 19:05 UTC, mikehoffms commented on microsoft-edge/privacy-whitepaper/index.md
> +* [Microsoft Defender for Cloud Applications](/defender-cloud-apps/what-is-defender-for-cloud-apps)
```suggestion
* [Microsoft Defender for Cloud App](/defender-cloud-apps/what-is-defender-for-cloud-apps)
```
https://learn.microsoft.com/en-us/defender-cloud-apps/what-is-defender-for-cloud-apps
Actual destination page title: "Microsoft Defender for Cloud Apps overview"
# hits on "cloud applications" in that page: 0
# hits on "cloud apps" in that page: 34

2023-08-03 16:58 UTC, mikehoffms approved these changes

2023-08-07 05:37 UTC, batamig commented on microsoft-edge/privacy-whitepaper/index.md
> +| Microsoft Defender for Cloud Apps | [Session policies](/defender-cloud-apps/session-policy-aad) |
```suggestion
| Microsoft Defender for Cloud Apps (Preview) | [Session policies](/defender-cloud-apps/session-policy-aad) |
```

2023-08-07 13:24 UTC, batamig commented
#sign-off

2023-08-07 18:06 UTC, jlam3 approved these changes

2023-08-07 18:26 UTC, apryzgoda approved these changes
Edge Privacy Approved

2023-08-07 22:17 UTC, merged