Remove the Command Palette experiment docs
MicrosoftDocs/edge-developer pull request #3059
Opened 2024-02-14 09:20 UTC by captainbrosset

This PR removes the documentation for the **Command Palette** experimental feature, as the feature is being removed from Edge in version 123.

2024-02-14 09:33 UTC, captainbrosset commented
`File microsoft-edge/devtools-guide-chromium/experimental-features/edge-command-palette.md with URL /microsoft-edge/devtools-guide-chromium/experimental-features/edge-command-palette was deleted without redirection. To avoid broken links, add a redirection.`

Once we have a What's New entry that mentions the feature removal, I will add a redirect to it.

2024-02-28 17:53 UTC, mikehoffms commented on microsoft-edge/devtools-guide-chromium/experimental-features/edge-command-palette.md
define a redirect for this removed .md file
@captainbrosset

2024-02-28 17:53 UTC, mikehoffms requested changes
define a redirect for the removed .md file

2024-03-27 13:52 UTC, mikehoffms approved these changes
Approved PR after tested the redirect.

2024-03-27 14:38 UTC, merged