Add row "Insecure downloads over HTTP" in "Site compatibility-impacting changes"
MicrosoftDocs/edge-developer pull request #3160
Opened 2024-05-14 18:08 UTC by mikehoffms

2024-05-15 20:13 UTC, dchege711 approved these changes

2024-05-16 00:51 UTC, dchege711 requested changes
@mikehoffms There is a new request to use more generic language. Undoing my 👍 for now. Kindly see Teams thread for more context.

2024-05-16 01:43 UTC, dchege711 approved these changes

2024-05-16 08:05 UTC, captainbrosset approved these changes

2024-05-16 14:45 UTC, merged