VS 2022 fully supported for WebView2
MicrosoftDocs/edge-developer pull request #3242
Opened 2024-08-01 21:36 UTC by mikehoffms

2025-01-21 09:53 UTC, captainbrosset requested changes

2025-01-21 09:53 UTC, captainbrosset commented on microsoft-edge/webview2/samples/webview2apissample.md
> +   **Fetch and pull commits**
```suggestion
   **Pull commits**
```

2025-01-21 09:53 UTC, captainbrosset commented on microsoft-edge/webview2/samples/webview2apissample.md
> +
```suggestion
```

2025-01-21 09:53 UTC, captainbrosset commented on microsoft-edge/webview2/samples/webview2apissample.md
> +
It's enough to just pull. Git pull does fetch and then merge in the background. So, when you run git pull, you don't need to have run fetch before.

2025-01-21 09:53 UTC, captainbrosset commented on microsoft-edge/webview2/samples/webview2apissample.md
> +   Returns: `Switched to branch 'test'`
1. Create a working branch and switch to it:

   ```
   git checkout -b test
   ```

   Returns: `Switched to branch 'test'`


Creating a new branch and switching to it can be done with just one command

2025-01-21 09:53 UTC, captainbrosset commented on microsoft-edge/webview2/samples/webview2apissample.md
> +You are now free to modify the code in your working branch, without altering the code that's in the "main" branch of the repo.  Later you might want to switch back to the "main" branch, or create a d
```suggestion
You are now free to modify the code in your working branch, without altering the code that's in the "main" branch of the repo.  Later you might want to switch back to the "main" branch, for example to pull new commits, or create a different branch based off the "main" branch.
```

2025-01-21 16:03 UTC, mikehoffms commented on microsoft-edge/webview2/samples/webview2apissample.md
> +   Returns: `Switched to branch 'test'`
result:
```
   **Create a working branch**

1. Create a working branch and switch to it:

   ```
   git checkout -b test
   ```

   Returns: `Switched to branch 'test'`
```

2025-01-21 16:07 UTC, mikehoffms commented on microsoft-edge/webview2/samples/webview2apissample.md
> +You are now free to modify the code in your working branch, without altering the code that's in the "main" branch of the repo.  Later you might want to switch back to the "main" branch, or create a d
not the best example? bc:
if you're in "test" branch and issue "git pull" cmd, it pulls commits for all branches?

2025-01-21 21:19 UTC, mikehoffms commented on microsoft-edge/webview2/samples/webview2apissample.md
> +You are now free to modify the code in your working branch, without altering the code that's in the "main" branch of the repo.  Later you might want to switch back to the "main" branch, or create a d
added the phrase

2025-01-22 15:04 UTC, mikehoffms reviewed
LGTM - Content Developer

2025-01-24 05:42 UTC, soumamazu approved these changes
LGTM - Dev

2025-01-28 08:11 UTC, captainbrosset approved these changes

2025-01-29 07:39 UTC, merged