Convert Extensions tutorial articles to sample articles
MicrosoftDocs/edge-developer pull request #3327
Opened 2024-12-04 00:11 UTC by mikehoffms

2025-01-10 23:55 UTC, mikehoffms commented on microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md
> +Each content script (`popup.js` and `content.js`) runs in an individual sandbox, which means that the jQuery that's injected into the initial popup page isn't shared with the current webpage.
@captainbrosset pls critically review the wording in these two h4 sections:

https://github.com/MicrosoftDocs/edge-developer/blob/user/mikehoffms/extension-samples/microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md#how-jquery-support-is-added-jqueryminjs

Each content script (popup.js and content.js) runs in an individual sandbox, which means that the jQuery that's injected into the initial popup page isn't shared with the current webpage.

Even if the browser tab has JavaScript running on it on the loaded web page, any content that's injected doesn't have access to that JavaScript. The injected JavaScript only has access to the actual DOM that's loaded in that browser tab.

2025-01-13 11:24 UTC, captainbrosset requested changes

2025-01-13 11:24 UTC, captainbrosset commented on microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md
This comment is for 271-273 and 295-300, and is out of scope, because it impacts the source code.

We should explain why we need a unique ID at all (in this case, it's to be able to find the image element again later and delete it, I think). And I really don't see the reason to list 2 options if we leave one alone, very enigmatically, without saying one.
Finally, and more importantly, we can replace the entire `guidGenerator` function with just one function call: `crypto.randomUUID()`. This now works across all browsers, and is far superior than using Math.random a bunch of times.

2025-01-13 11:24 UTC, captainbrosset commented on microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md
> +`/content-scripts/content.js` (complete listing):
This code snippet isn't shown anywhere else in the code, so I don't think this line is necessary./ The sentence on line 310 seems like a  sufficient lead-in text.

2025-01-13 11:24 UTC, captainbrosset commented on microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md
> +* The manifest (below) specifies that `web_accessible_resources` of type `.jpg` match all URLs.
```suggestion
* The manifest (below) specifies that `web_accessible_resources` of type `.jpeg` match all URLs.
```

2025-01-13 11:24 UTC, captainbrosset commented on microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md
> +In the `content_scripts` key section, the `matches` attribute is set to `<all_urls>`, which means that `.js` (or `.css`) files that are specified in In the `content_scripts` key section are injected
```suggestion
In the `content_scripts` key section, the `matches` attribute is set to `<all_urls>`, which means that `.js` (or `.css`) files that are specified in the `content_scripts` key section are injected into all browser tab pages when each tab is loaded.  The allowed files types that can be injected are JavaScript (`.js`) and CSS (`.css`).  
```

2025-01-13 11:24 UTC, captainbrosset commented on microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md
> +`jquery.min.js` is a predefined, minified file to support jQuery expressions starting with `$` in `popup.js` and `content.js`.
JQuery is only used in content.js, not in popup.js.

```suggestion
`jquery.min.js` is a predefined, minified file to support jQuery expressions starting with `$` in `content.js`.
```

2025-01-13 11:24 UTC, captainbrosset commented on microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md
> +Each content script (`popup.js` and `content.js`) runs in an individual sandbox, which means that the jQuery that's injected into the initial popup page isn't shared with the current webpage.
```suggestion
The content script (`content.js`) runs in its own sandbox, which means that the jQuery that's injected in `content.js` isn't shared with the current webpage.
```

2025-01-13 11:24 UTC, captainbrosset commented on microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md
> +Even if the browser tab has JavaScript running on it on the loaded web page, any content that's injected doesn't have access to that JavaScript.  The injected JavaScript only has access to the actual
```suggestion
Even if the browser tab contains a web page that runs JavaScript code, the `content.js` script that's injected in that browser tab by the extension doesn't have access to that JavaScript code.  The injected content script only has access to the DOM of the web page.
```

2025-01-13 23:34 UTC, mikehoffms commented on microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md
> +`popup.html` is specified in the manifest file as the initial, default webpage to display in the extension popup.  This webpage contains a title, instructions, and a **Display** button.
result:
```
`popup.html` is specified in the manifest file as the webpage to display in the 
extension's initial popup.  This small webpage contains a title, instructions, and 
a **Display** button.
```

2025-01-13 23:37 UTC, mikehoffms commented on microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md
> +## The default initial popup webpage (`popup.html`)
live version of Part 2 article contains "default" 1x:
https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/part2-content-scripts
```
    "action": {
        "default_popup": "popup/popup.html"
    },
```

2025-01-13 23:39 UTC, mikehoffms commented on microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md
> +## The default initial popup webpage (`popup.html`)
live version of Part 1 article contains "default" 3x:
https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/part1-simple-extension#step-3-open-a-default-pop-up-dialog

hit 1: 
You create this type of extension by doing the following:
* Create a manifest.json file.
* Add icons for launching the extension.
* Open a default pop-up dialog.

hit 2: 
* H2 heading: "Step 3: Open a default pop-up dialog"

hit 3: manifest file:
```
  "action": {
        "default_popup": "popup/popup.html"
    }
```

2025-01-13 23:46 UTC, mikehoffms commented on microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md
> +## The default initial popup webpage (`popup.html`)
result:
```
## The initial popup webpage (`popup.html`)

`popup.html` is specified in the manifest file as the webpage to display in the extension's 
initial popup.  The manifest file contains the key field `"default_popup": "popup/popup.html"`.  
This sample's `popup.html` file is a small webpage that contains a title, instructions, and a **Display** button.
```

2025-01-13 23:53 UTC, mikehoffms commented on microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md
> +This code sends a message to the content script (`content.js`) that's temporarily injected into the browser tab.  To do that, the following code adds an `onclick` event to the pop-up **Display** butt
result:
```
`popup.js` sends a message to the content script (`content.js`) that's temporarily injected 
into the browser tab.  To do that, `popup.js` adds an `onclick` event to the pop-up webpage's  
**Display** button, which has the ID `sendmessageid`:
```

2025-01-13 23:56 UTC, mikehoffms commented on microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md
>  const sendMessageId = document.getElementById("sendmessageid");
result:
```
In the following `popup.js` code, the sample uses `chrome.tabs.query` to find the current 
browser tab, and then uses `chrome.tabs.sendMessage` to send a message to that tab.
```

2025-01-14 00:02 UTC, mikehoffms commented on microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md
result:
```
<!-- 
todo:
requires PR in docs repo + PR in Extension repo.  in a couple passages (formerly 
lines 271-273 and 295-300):

add: "A unique ID is needed, to be able to find the image element again later and 
delete it."

don't list 2 options if we leave one alone, enigmatically

replace guidGenerator function with a single call of `crypto.randomUUID()`.  works 
in all browsers, better than using `Math.random` multiple times
-->
```

2025-01-14 00:04 UTC, mikehoffms commented on microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md
> +`/content-scripts/content.js` (complete listing):
removed line:
``/content-scripts/content.js` (complete listing):`

2025-01-14 00:07 UTC, mikehoffms commented on microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md
> +Even if the browser tab has JavaScript running on it on the loaded web page, any content that's injected doesn't have access to that JavaScript.  The injected JavaScript only has access to the actual
result: the Suggested change, except webpage not web page

2025-01-14 00:10 UTC, mikehoffms commented on microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md
> +Even if the browser tab has JavaScript running on it on the loaded web page, any content that's injected doesn't have access to that JavaScript.  The injected JavaScript only has access to the actual
@captainbrosset - corp style: webpage is one word
https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/w/web-world-wide-web-www - "The following terms that include _web_ are one word: webpage, website,"

2025-01-14 00:14 UTC, mikehoffms commented on microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md
> +Each content script (`popup.js` and `content.js`) runs in an individual sandbox, which means that the jQuery that's injected into the initial popup page isn't shared with the current webpage.
had to pick "injected by content.js" or "injected into content.js".  result:
```
The content script (`content.js`) runs in its own sandbox, which means that 
the jQuery that's injected into `content.js` isn't shared with the current webpage.
```
@captainbrosset

2025-01-14 00:17 UTC, mikehoffms commented on microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md
> +`jquery.min.js` is a predefined, minified file to support jQuery expressions starting with `$` in `popup.js` and `content.js`.
popup.js contains line that contains `$`:
```
imageDivId: `${guidGenerator()}`,
```
@captainbrosset - keep mention of popup.js?

2025-01-14 00:20 UTC, mikehoffms commented on microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md
> +In the `content_scripts` key section, the `matches` attribute is set to `<all_urls>`, which means that `.js` (or `.css`) files that are specified in In the `content_scripts` key section are injected
result, without "In", and with 'manifest' at start:
```
In the `content_scripts` key section of the manifest file, the `matches` attribute is set to `<all_urls>`, which means that `.js` (or `.css`) files that are specified in the
```

2025-01-14 00:24 UTC, mikehoffms commented on microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md
> +Each content script (`popup.js` and `content.js`) runs in an individual sandbox, which means that the jQuery that's injected into the initial popup page isn't shared with the current webpage.
result:
```
The content script (`content.js`) runs in its own sandbox, which means that the jQuery that's injected into `content.js` isn't shared with the current webpage.
...
Even if the browser tab contains a webpage that runs JavaScript code, the `content.js` script that's injected in that browser tab by the extension doesn't have access to that JavaScript code.  The injected content script only has access to the DOM of the webpage.
```

2025-01-14 00:30 UTC, mikehoffms commented on microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md
> +   jquery.min.js
result:
```
<!-- 
todo:
create docs repo PR + Extension repo PR:
remove jQuery
sample uses jQuery just for the $ selector:  $("body"))
change to document.querySelector
-->
```

2025-01-14 00:36 UTC, mikehoffms commented on microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md
> +description: Uses JavaScript to insert a .png file below the <body> start-tag of the current webpage.
result: 
```
description: Uses JavaScript to insert a .jpeg image file inside the <body> element 
of the current webpage.
```
hit count on .png: only in /icons/ dir.
hit count on .jpg: 0

2025-01-14 00:41 UTC, mikehoffms commented on microsoft-edge/extensions-chromium/getting-started/part1-simple-extension.md
> +The popup (`popup.html`) is registered as the default popup in `manifest.json` under `action`:
result:
```
The popup (`popup.html`) is registered as the `"default_popup"` in `manifest.json`, in the `action` key section:

`manifest.json` (portion)
```

2025-01-14 00:43 UTC, mikehoffms commented on microsoft-edge/extensions-chromium/getting-started/part1-simple-extension.md
> +## The default pop-up dialog (`popup.html`)
result:
```
## The pop-up dialog (`popup.html`)
```

2025-01-14 01:08 UTC, mikehoffms commented on microsoft-edge/extensions-chromium/getting-started/part1-simple-extension-images/part1-badge1.png
result:
![image](https://github.com/user-attachments/assets/6502f0d2-1af8-4fb2-b35c-61b9520526ec)

2025-01-14 08:49 UTC, captainbrosset approved these changes
Approved, but let's remove the mention of popup.js where we discuss jQuery, since that file doesn't use jQuery.

2025-01-14 08:49 UTC, captainbrosset commented on microsoft-edge/extensions-chromium/getting-started/part2-content-scripts.md
> +`jquery.min.js` is a predefined, minified file to support jQuery expressions starting with `$` in `popup.js` and `content.js`.
These are 2 different use of `$`:

* `$(...)`
* `${...}`

The former is the jQuery selector function. The latter is a placeholder which can be used in JS template strings.

If popup.js only contains the latter, then it doesn't actually uses jQuery, and therefore doesn't need it.

2025-01-14 17:10 UTC, merged