Usr/jasteph/debugdoc
MicrosoftDocs/edge-developer pull request #887
Opened 2020-09-03 18:24 UTC by jasonstephen15

Adding in VSCode Section to debugging doc

2020-09-03 18:25 UTC, opbld30 commented
Docs Build status updates of commit _[094309f](https://github.com/MicrosoftDocs/edge-developer/commits/094309f4b5d69e1489a1f5063ece043fdaf80be1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/howto/debug.md](https://github.com/MicrosoftDocs/edge-developer/blob/usr/jasteph/debugdoc/microsoft-edge/webview2/howto/debug.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C3%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202009031824394838-887%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NOJB80Fv0rCDY1WQzBw2nMjLvzviLdgkiAklR0pdLwk%3D&st=2020-09-03T18%3A20%3A22Z&se=2020-10-04T18%3A25%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-03 18:25 UTC, jasonstephen15 commented
@Reezaali I know we already made some revisions in a previous word doc, was wondering if you still had that handy?

2020-09-05 16:34 UTC, opbld31 commented
Docs Build status updates of commit _[aa35bb3](https://github.com/MicrosoftDocs/edge-developer/commits/aa35bb385265adb7a289d1803351f77c1e74b1f5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/howto/debug.md](https://github.com/MicrosoftDocs/edge-developer/blob/usr/jasteph/debugdoc/microsoft-edge/webview2/howto/debug.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C5%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202009051634017212-887%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=79MESUw%2FmWHqeKQGNBRpDaTILYU7cUv8eWlTLqYzkjE%3D&st=2020-09-05T16%3A29%3A37Z&se=2020-10-06T16%3A34%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-14 22:09 UTC, DavidShoe approved these changes

2020-09-16 23:38 UTC, opbld32 commented
Docs Build status updates of commit _[136ebe4](https://github.com/MicrosoftDocs/edge-developer/commits/136ebe47cc33686284b78720a9173583326b1ed5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/howto/debug.md](https://github.com/MicrosoftDocs/edge-developer/blob/usr/jasteph/debugdoc/microsoft-edge/webview2/howto/debug.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202009162337083257-887%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pJf%2Bb9AH1kQ70dNxnHv3QvedWj0TXHLnIMadYM5nfVo%3D&st=2020-09-16T23%3A33%3A02Z&se=2020-10-17T23%3A38%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-16 23:53 UTC, opbld33 commented
Docs Build status updates of commit _[1eded42](https://github.com/MicrosoftDocs/edge-developer/commits/1eded4217d94111e8f8371d6c1c0766489c5f710)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/howto/debug.md](https://github.com/MicrosoftDocs/edge-developer/blob/usr/jasteph/debugdoc/microsoft-edge/webview2/howto/debug.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C16%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202009162353094386-887%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Ved58naAQcDPS%2BY1jr6AzcgMZaUI3Et6ML9wPBMjh5M%3D&st=2020-09-16T23%3A48%3A42Z&se=2020-10-17T23%3A53%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-18 01:00 UTC, Reezaali requested changes

2020-09-18 04:22 UTC, opbld33 commented
Docs Build status updates of commit _[d64154c](https://github.com/MicrosoftDocs/edge-developer/commits/d64154c2ee8ed865476be38bb8db5813bbe342d2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/howto/debug.md](https://github.com/MicrosoftDocs/edge-developer/blob/usr/jasteph/debugdoc/microsoft-edge/webview2/howto/debug.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C18%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202009180421297506-887%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=I7jUlzscMPfKyj8MvJiC47o4X7nAbdTIsIK3IlXmf0o%3D&st=2020-09-18T04%3A17%3A24Z&se=2020-10-19T04%3A22%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-18 04:22 UTC, opbld31 commented
Docs Build status updates of commit _[a3e3d01](https://github.com/MicrosoftDocs/edge-developer/commits/a3e3d01f2a84921349b5f2f0c2ad53348ff59d7b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/howto/debug.md](https://github.com/MicrosoftDocs/edge-developer/blob/usr/jasteph/debugdoc/microsoft-edge/webview2/howto/debug.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C18%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202009180421434466-887%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cpW5XvBfphwtblkG%2Bk8i%2FuQgW2gHFR6Wrc2hgHN87Ho%3D&st=2020-09-18T04%3A17%3A56Z&se=2020-10-19T04%3A22%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-18 04:24 UTC, opbld32 commented
Docs Build status updates of commit _[967c0c0](https://github.com/MicrosoftDocs/edge-developer/commits/967c0c0a8fc2e02f13ff602bace3935d652577ac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/howto/debug.md](https://github.com/MicrosoftDocs/edge-developer/blob/usr/jasteph/debugdoc/microsoft-edge/webview2/howto/debug.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C18%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202009180424056095-887%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=J5bolTytYDNd4b0y6S5zIsqH963022b%2B5CykYEt%2FaBQ%3D&st=2020-09-18T04%3A19%3A58Z&se=2020-10-19T04%3A24%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-18 04:25 UTC, opbld31 commented
Docs Build status updates of commit _[46cb1b6](https://github.com/MicrosoftDocs/edge-developer/commits/46cb1b67f39a8cab31988f93b6df97776b7673de)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/howto/debug.md](https://github.com/MicrosoftDocs/edge-developer/blob/usr/jasteph/debugdoc/microsoft-edge/webview2/howto/debug.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C18%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202009180424286864-887%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=f3CjZmFYgsZXKQc3RSHTAI%2BkM6POpbEUcQ1Yu9N9ljI%3D&st=2020-09-18T04%3A20%3A57Z&se=2020-10-19T04%3A25%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-18 04:27 UTC, opbld31 commented
Docs Build status updates of commit _[0c27448](https://github.com/MicrosoftDocs/edge-developer/commits/0c2744811d91c968b8d8ab966f04196c365e35d8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/howto/debug.md](https://github.com/MicrosoftDocs/edge-developer/blob/usr/jasteph/debugdoc/microsoft-edge/webview2/howto/debug.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C18%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202009180426021207-887%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=J02%2Fm%2B899o8E%2BfRUxO8sUdnjjpn61pJgmwFMj152kE8%3D&st=2020-09-18T04%3A22%3A01Z&se=2020-10-19T04%3A27%3A01Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-18 04:27 UTC, opbld32 commented
Docs Build status updates of commit _[0c27448](https://github.com/MicrosoftDocs/edge-developer/commits/0c2744811d91c968b8d8ab966f04196c365e35d8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/howto/debug.md](https://github.com/MicrosoftDocs/edge-developer/blob/usr/jasteph/debugdoc/microsoft-edge/webview2/howto/debug.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C18%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202009180426124271-887%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QFnpXhAvbnhXuK3%2BxiOEeTHZJa65a5QuCw2Lt9kNJjE%3D&st=2020-09-18T04%3A22%3A46Z&se=2020-10-19T04%3A27%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-18 04:29 UTC, opbld33 commented
Docs Build status updates of commit _[7f7af63](https://github.com/MicrosoftDocs/edge-developer/commits/7f7af630d8d13990f8fa7b1510516ab36d497657)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/howto/debug.md](https://github.com/MicrosoftDocs/edge-developer/blob/usr/jasteph/debugdoc/microsoft-edge/webview2/howto/debug.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C18%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202009180428361336-887%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=09N5oLfhloUlqqJxWw3SXzA%2FtYiagQ2kOhJOE3InUtk%3D&st=2020-09-18T04%3A24%3A28Z&se=2020-10-19T04%3A29%3A28Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-18 20:48 UTC, Reezaali commented on microsoft-edge/webview2/howto/debug.md
> +*   Targeted Webview debugging.
In some WebView2 applications, you may use more than one WebView2 control. To pick the WebView2 control to debug in this situation you can use targeted webview2 debugging

2020-09-18 22:55 UTC, opbld30 commented
Docs Build status updates of commit _[df134dd](https://github.com/MicrosoftDocs/edge-developer/commits/df134dd046bccf32ee96d4a0f1a1d7ddbd89704d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/howto/debug.md](https://github.com/MicrosoftDocs/edge-developer/blob/usr/jasteph/debugdoc/microsoft-edge/webview2/howto/debug.md) | :bulb:Suggestion | | [Details](#user-content-de862f17-3c473a75)

<a id="de862f17-3c473a75"></a>
### [microsoft-edge/webview2/howto/debug.md](https://github.com/MicrosoftDocs/edge-developer/blob/usr/jasteph/debugdoc/microsoft-edge/webview2/howto/debug.md)
 - **Line 103, Column 1**: **[Suggestion-[code-block-indented](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-indented?branch=master)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```). NOTE: This Suggestion will become a Warning in late September, 2020.`````
 - **Line 172, Column 1**: **[Suggestion-[code-block-indented](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-indented?branch=master)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```). NOTE: This Suggestion will become a Warning in late September, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C18%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202009182254579063-887%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8OSX2XAqvUAY%2FdyDUVGNK97fTk74GvvVEhPlxHQNFzA%3D&st=2020-09-18T22%3A50%3A52Z&se=2020-10-19T22%3A55%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-21 04:44 UTC, Reezaali approved these changes

2020-09-21 16:34 UTC, jasonstephen15 commented
#sign-off

2020-09-21 16:57 UTC, opbld31 commented
Docs Build status updates of commit _[286ce6b](https://github.com/MicrosoftDocs/edge-developer/commits/286ce6b7480c25fb612ad1e13552131524f7c368)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/howto/debug.md](https://github.com/MicrosoftDocs/edge-developer/blob/usr/jasteph/debugdoc/microsoft-edge/webview2/howto/debug.md) | :bulb:Suggestion | | [Details](#user-content-de862f17-1ff630d3)

<a id="de862f17-1ff630d3"></a>
### [microsoft-edge/webview2/howto/debug.md](https://github.com/MicrosoftDocs/edge-developer/blob/usr/jasteph/debugdoc/microsoft-edge/webview2/howto/debug.md)
 - **Line 103, Column 1**: **[Suggestion-[code-block-indented](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-indented?branch=master)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```). NOTE: This Suggestion will become a Warning in late September, 2020.`````
 - **Line 172, Column 1**: **[Suggestion-[code-block-indented](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-indented?branch=master)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```). NOTE: This Suggestion will become a Warning in late September, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C21%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202009211656437299-887%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5o6aTP7%2BXLHCk7FnDMmZ295KRA60sDH%2BlWqHBGwymio%3D&st=2020-09-21T16%3A52%3A36Z&se=2020-10-22T16%3A57%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-21 17:09 UTC, opbld32 commented
Docs Build status updates of commit _[d7f14ae](https://github.com/MicrosoftDocs/edge-developer/commits/d7f14aeb75d1e9878b2b6a9b9ac8f636f5721dde)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/howto/debug.md](https://github.com/MicrosoftDocs/edge-developer/blob/usr/jasteph/debugdoc/microsoft-edge/webview2/howto/debug.md) | :bulb:Suggestion | | [Details](#user-content-de862f17-f3d76dcb)

<a id="de862f17-f3d76dcb"></a>
### [microsoft-edge/webview2/howto/debug.md](https://github.com/MicrosoftDocs/edge-developer/blob/usr/jasteph/debugdoc/microsoft-edge/webview2/howto/debug.md)
 - **Line 103, Column 1**: **[Suggestion-[code-block-indented](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-indented?branch=master)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```). NOTE: This Suggestion will become a Warning in late September, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C21%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202009211708375440-887%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FMFbMyfHFeZikY1XHgHwfW1tPU8f4340HZMQ4Tt1yHI%3D&st=2020-09-21T17%3A04%3A29Z&se=2020-10-22T17%3A09%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-21 17:10 UTC, opbld33 commented
Docs Build status updates of commit _[d971975](https://github.com/MicrosoftDocs/edge-developer/commits/d971975d4e266922696fd2d15c9e756a993862cc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/webview2/howto/debug.md](https://github.com/MicrosoftDocs/edge-developer/blob/usr/jasteph/debugdoc/microsoft-edge/webview2/howto/debug.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C21%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202009211709563604-887%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=wfoWInCCgaG3caIekVM%2BNaRt1AujQQp14NTbBKTPi8k%3D&st=2020-09-21T17%3A05%3A39Z&se=2020-10-22T17%3A10%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-21 17:17 UTC, jasonstephen15 commented
#sign-off

2020-09-21 17:28 UTC, jm-trd-ms commented
#sign-off and merged.

2020-09-21 17:29 UTC, merged