Added shopping
MicrosoftDocs/edge-developer pull request #991
Opened 2020-11-06 17:08 UTC by lilliankravitz

Removed shopping from collections to its own section. Updated sync and autofill

2020-11-06 17:08 UTC, opbld31 commented
Docs Build status updates of commit _[9ebe2a9](https://github.com/MicrosoftDocs/edge-developer/commits/9ebe2a9bc8c1e3ab1c4e64fc0024f989defb716d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-3f774dea)

<a id="3f774dea"></a>
###
 - **[Error-RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C6%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202011061708184949-991%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GXE779N%2BMu5fRsPsfMnzh%2FcSaSnRIzglbu3v5ceW3EM%3D&st=2020-11-06T17%3A03%3A50Z&se=2020-12-07T17%3A08%3A50Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-06 17:53 UTC, Reezaali requested changes

2020-11-06 17:53 UTC, Reezaali commented on microsoft-edge/privacy-whitepaper.md
> +Autofill in Microsoft Edge helps you be more productive by letting you save passwords, payment info, addresses, and other form entry data like birthday.  When you visit a site and start to fill out a
```suggestion
Autofill in Microsoft Edge helps you be more productive by letting you save passwords, payment information, addresses, and other form entry data, for example birthdays.  When you visit a site and start to fill out a form, Microsoft Edge uses form fill info to match your saved autofill data to the form.  Microsoft Edge offers form entry data you previously saved when you encounter similar forms.  Passwords and credit card info are only saved with your explicit permission for each password and card.  
```

2020-11-06 17:53 UTC, Reezaali commented on microsoft-edge/privacy-whitepaper.md
> +Microsoft Edge helps you find coupons and better prices while shopping online.  To help you find coupons while shopping online, Microsoft Edge downloads a list of shopping domains locally to the clie
```suggestion
Microsoft Edge helps you find coupons and better prices while shopping online.  To help you find coupons while shopping online, Microsoft Edge downloads a list of shopping domains locally to the client from the Microsoft shopping service.  When you go to a website, Microsoft Edge determines if the site you're on is a shopping domain.  If the site is determined to be a shopping domain, Microsoft Edge will send the URL with no personally identifiable information to the Microsoft shopping service.  The shopping service will return any available coupons for that site.  
```

2020-11-06 17:53 UTC, Reezaali commented on microsoft-edge/privacy-whitepaper.md
> +When you're applying coupons, cookies will be stored on your device to correctly attribute the coupon provider.  Cookies will be saved by our trusted coupon providers only after a coupon is successfu
```suggestion
When you're applying coupons, cookies will be stored on your device to correctly attribute the coupon provider.  Cookies will be saved by our trusted coupon providers only after a coupon is successfully applied on the cart.  After the coupons are applied, information about the success of the coupons will be sent back to the Microsoft shopping service to help us understand which coupons succeeded or failed.  Data sent to the Microsoft shopping service is sent over HTTPS with a randomly generated identifier which changes per coupon lookup.  
```

2020-11-06 17:53 UTC, Reezaali commented on microsoft-edge/privacy-whitepaper.md
> +To help you find the best price while shopping online and using Collections, Microsoft Edge determines locally if the page or collection item you're viewing is a product detail page.  If you're looki
```suggestion
To help you find the best price while shopping online and using Collections, Microsoft Edge determines if the page or collection item you're viewing is a product detail page.  If you're looking at a product detail page, Microsoft Edge sends the details of the product to the shopping service, including the URL with no personally identifiable information, price, product image, product name, ratings, and reviews. Also, information about Microsoft Edge and your operating system version is sent to the service.  This data is sent over HTTPS with a randomly generated identifier.  The Microsoft shopping service will return prices from other retailers for the same product.  
```

2020-11-06 17:53 UTC, Reezaali commented on microsoft-edge/privacy-whitepaper.md
> +The shopping service is turned on by default for all users.  You can turn off shopping in Microsoft Edge by going to `edge://settings/privacy` and turning off **Save time and money with Shopping in M
```suggestion
The shopping service is turned on by default for all users.  To change the shopping setting in Microsoft Edge, navigate to `edge://settings/privacy`, and then turn off **Save time and money with Shopping in Microsoft Edge**.  InPrivate browsing uses the shopping setting of the profile that launched the InPrivate session.  
```

2020-11-07 15:56 UTC, lilliankravitz commented on microsoft-edge/privacy-whitepaper.md
> +Microsoft Edge helps you find coupons and better prices while shopping online.  To help you find coupons while shopping online, Microsoft Edge downloads a list of shopping domains locally to the clie
too definitive.

2020-11-07 15:56 UTC, opbld31 commented
Docs Build status updates of commit _[b28c41a](https://github.com/MicrosoftDocs/edge-developer/commits/b28c41aedc6e51ce832c36f888ab574a5b1c1c7d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/media/whitepaper-media/shopping.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/likravit/docs/whitepaper110620/microsoft-edge/media/whitepaper-media/shopping.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/privacy-whitepaper?branch=pr-en-us-991) |
[microsoft-edge/privacy-whitepaper.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/likravit/docs/whitepaper110620/microsoft-edge/privacy-whitepaper.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/privacy-whitepaper?branch=pr-en-us-991) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C7%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202011071555545737-991%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1UPjnX5djR1RaIUdMOemqxjAiCjePNt5MKs3vagwg9Q%3D&st=2020-11-07T15%3A51%3A47Z&se=2020-12-08T15%3A56%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-07 15:57 UTC, opbld33 commented
Docs Build status updates of commit _[202bfac](https://github.com/MicrosoftDocs/edge-developer/commits/202bfacfd3841c54c88a24866c907b2198380d3f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/media/whitepaper-media/shopping.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/likravit/docs/whitepaper110620/microsoft-edge/media/whitepaper-media/shopping.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/privacy-whitepaper?branch=pr-en-us-991) |
[microsoft-edge/privacy-whitepaper.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/likravit/docs/whitepaper110620/microsoft-edge/privacy-whitepaper.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/privacy-whitepaper?branch=pr-en-us-991) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C7%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202011071556582121-991%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Wa5cRenpOqoVV9h28Z0Ogrqor9PngQcveFxRHILXIGc%3D&st=2020-11-07T15%3A52%3A30Z&se=2020-12-08T15%3A57%3A30Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-07 15:57 UTC, lilliankravitz commented on microsoft-edge/privacy-whitepaper.md
> +To help you find the best price while shopping online and using Collections, Microsoft Edge determines locally if the page or collection item you're viewing is a product detail page.  If you're looki
same. too definitive.

2020-11-07 15:58 UTC, opbld33 commented
Docs Build status updates of commit _[6ffa304](https://github.com/MicrosoftDocs/edge-developer/commits/6ffa30474acae3b0d5f20b8c7341ef2ba556e1ce)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/media/whitepaper-media/shopping.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/likravit/docs/whitepaper110620/microsoft-edge/media/whitepaper-media/shopping.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/privacy-whitepaper?branch=pr-en-us-991) |
[microsoft-edge/privacy-whitepaper.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/likravit/docs/whitepaper110620/microsoft-edge/privacy-whitepaper.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/privacy-whitepaper?branch=pr-en-us-991) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C7%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202011071557253767-991%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8iOu5UDVV6PV%2B5oz9%2F4gxpuX%2FuFtdmOqcG9LMoh%2BBTo%3D&st=2020-11-07T15%3A53%3A09Z&se=2020-12-08T15%3A58%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-10 22:37 UTC, opbld33 commented
Docs Build status updates of commit _[6c64e7d](https://github.com/MicrosoftDocs/edge-developer/commits/6c64e7d63d10d8b24ed21a0124b7ac848bca1ad5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/media/whitepaper-media/shopping.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/likravit/docs/whitepaper110620/microsoft-edge/media/whitepaper-media/shopping.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/privacy-whitepaper?branch=pr-en-us-991) |
[microsoft-edge/privacy-whitepaper.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/likravit/docs/whitepaper110620/microsoft-edge/privacy-whitepaper.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/privacy-whitepaper?branch=pr-en-us-991) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C10%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202011102236597803-991%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GjIZzne6xjFFZ8yPxFUdIOm3y6R05Uca4V3802xPBfY%3D&st=2020-11-10T22%3A32%3A34Z&se=2020-12-11T22%3A37%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-10 22:52 UTC, opbld32 commented
Docs Build status updates of commit _[e746a4f](https://github.com/MicrosoftDocs/edge-developer/commits/e746a4fb5a1f828de5d85e58978f2848c3af7e5c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/media/whitepaper-media/shopping.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/likravit/docs/whitepaper110620/microsoft-edge/media/whitepaper-media/shopping.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/privacy-whitepaper?branch=pr-en-us-991) |
[microsoft-edge/privacy-whitepaper.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/likravit/docs/whitepaper110620/microsoft-edge/privacy-whitepaper.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/privacy-whitepaper?branch=pr-en-us-991) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C10%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202011102251257630-991%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=OXJpkeqOUPDwWTKaCXkO%2B5wGlHp9MjejphJCXb9vjs8%3D&st=2020-11-10T22%3A46%3A59Z&se=2020-12-11T22%3A51%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-10 23:05 UTC, opbld30 commented
Docs Build status updates of commit _[69f7293](https://github.com/MicrosoftDocs/edge-developer/commits/69f7293e92ae5b67379086f0f77c07c2d698e9d6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoft-edge/media/whitepaper-media/shopping.png](https://github.com/MicrosoftDocs/edge-developer/blob/user/likravit/docs/whitepaper110620/microsoft-edge/media/whitepaper-media/shopping.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/privacy-whitepaper?branch=pr-en-us-991) |
[microsoft-edge/privacy-whitepaper.md](https://github.com/MicrosoftDocs/edge-developer/blob/user/likravit/docs/whitepaper110620/microsoft-edge/privacy-whitepaper.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/microsoft-edge/privacy-whitepaper?branch=pr-en-us-991) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C10%5Cdb9f4228-bcf7-7df9-527f-b7c9a032ef40%5CPullRequest%5C202011102305083433-991%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ZgUA6YmQVPAFslXFM1sPZObgOMPWcgPNzqPw%2BbZ9hnQ%3D&st=2020-11-10T23%3A00%3A42Z&se=2020-12-11T23%3A05%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/db9f4228-bcf7-7df9-527f-b7c9a032ef40?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-10 23:06 UTC, Reezaali approved these changes

2020-11-10 23:10 UTC, jm-trd-ms commented
#sign-off offline and merged.

2020-11-10 23:11 UTC, merged